### ISSUE TITLE
Misaya combo don't work

### ISSUE THREAD

**Issue by HeheheM** [berbb/PortAIO#1]
Misaya combo don't work in diana script

**Comment by berbb** [comment]
It should be working, its the exact same code as the original. You have to be in a certain range for the misaya combo to work, if you are not in that range it will do the normal combo. But it's okay, I'll be dual-porting Nechrito Diana soon :)

**Comment by HeheheM** [comment]
Ok, thanks. Viktor cast "E" on min. range only.
