### ISSUE TITLE
Request: Evade # port

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#100]
Best Evade in EB Official is EvadeIC but it not working properly for me: sometimes doesn't dodge, running to skillshot,...
And we have EzEvade here but evade spell not working properly as it should. It's always activate if user choose "Activation time" mode.
So will Evade # be ported in near future? We still don't have a good evade here!

**Comment by lgndz** [comment]
If ezEvade is not using evade spells, it would be prudent to create and issue concerning that - rather then porting a whole nother evade... Especially since ezEvade is very full featured

**Comment by berbb** [comment]
Sure, but not a priority.
