### ISSUE TITLE
PortAIO Discord

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#101]
PortAIO Discord
---
**Unlimited Link** - https://discord.gg/0zNgmm6ziPGAU8yz

Guests are only able to post in the #guests-post-here-first channel and will be made a Member once they provide the following and is approved:
- Elobuddy Username
- Github Username

---

- Do not ask for any roles other than Member; they will be assigned to you if you are right for the job.
- Issues/suggestions/concerns are not to be posted in the Discord if you wish for them to be seen by Berb. The Discord is just to confirm that the issue is not just on your end/communicate with others to see if your suggestion/concern is worthwhile enough to post on GitHub.

@berbb 
If you don't want there being a Discord for PortAIO then just delete this post.

**Comment by berbb** [comment]
I don't mind, feel free - +1

**Comment by Xelamats** [comment]
@berbb 

I take it you won't be joining us right now. In that case, I'll keep this warm for you until you do.
![keepitwarm](https://cloud.githubusercontent.com/assets/8278110/15004779/21fad018-1170-11e6-9b34-b1dc2eedc76a.png)

**Comment by Xelamats** [comment]
Got messaged on Discord by someone using your name. Just want to make sure it is you before giving them any permissions.

@berbb

**Comment by berbb** [comment]
@Xelamats Yep, It's me.

**Comment by Monnq** [comment]
Could you update the link, please? The one you provided stopped working.

**Comment by Xelamats** [comment]
@Monnq That's odd. Anyways, I've updated it for you.

**Comment by Monnq** [comment]
Thanks, it worked :)

**Comment by GreatWhite181** [comment]
@Xelamats sorry, a bit of a newbie to Discord but I want to help out too! I joined the group and posted my EB and git user, then the group disappeared and I can't add it again.

**Comment by Xelamats** [comment]
@GreatWhite181 Link doesn't work anymore for you? Try this one: https://discord.gg/0zNgmm6ziPGAU8yz
