### ISSUE TITLE
Auto attack stuttering with every champion

### ISSUE THREAD

**Issue by ZangiefWins** [berbb/PortAIO#102]
Hello. I remember there was an option in bansharp.common named "enable missile check", that would cause auto attack stuttering to me if enabled. And, since berb.common is (I think) a bansharp.common port, and this is enabled by default, it might be causing this to me. Can you please check if that is in berb.common? If it is, can you please disable this or add an option in the menu to disable it? Thanks a lot!

**Comment by Muse30** [comment]
missile check is from l# orbwalker and that is not ported so the problem is not from portAIO

**Comment by ZangiefWins** [comment]
So, any idea on what can be causing this? Can you tell me your orbwalker configs?

**Comment by Muse30** [comment]
I use default eb settings... maybe try deleting your appdata or reinstalling

**Comment by ZangiefWins** [comment]
I don't remember the default settings, what is the default delay between movements and extra windup time?

**Comment by berbb** [comment]
Honestly this is something for the EB but, *my* windup is on 60, and my delay on movements is 600.
