### ISSUE TITLE
Missfortune broken

### ISSUE THREAD

**Issue by Dunkka** [berbb/PortAIO#102]
the script doesn't work and glitches out, looks like it happens after it casts Q on the enemy

Here's a vid: https://www.dropbox.com/s/s614bb2czcwt96o/test.mp4?dl=0  (sry 4 shitty quality kek)

Addons used: https://gyazo.com/192739cb5fa79e7022ec2c0dd4f0cbac

Console doesn't show any errors, if you need more info i'm willing to post

**Comment by Xelamats** [comment]
Just confirmed broken on my end as well.

**Comment by berbb** [comment]
Should be fixed, check it out,
