### ISSUE TITLE
Bug Champion: Singed

### ISSUE THREAD

**Issue by Shazelol** [berbb/PortAIO#104]
Singed is bugged again, when I use Q manually, this assembly "ElSinged" Desactivate Q.

**Comment by dsljkeee** [comment]
just disable auto q in q setting

**Comment by Shazelol** [comment]
Auto-Q, ElSinged doesn't "Auto-Q". Q in singed only works in combo. For W and E works very well.

**Comment by Muse30** [comment]
fixed
