### ISSUE TITLE
[Simple] Suggestion for Port: Autolvlup

### ISSUE THREAD

**Issue by ryroy** [berbb/PortAIO#104]
I think a simple autolvlup port would be a great little addition to your already flawless addon. If it doesn't seem like much of a bother, consider doing it ^^

**Comment by Xelamats** [comment]
LOL. I honestly don't think you need one. It's not hard to do it yourself. Ctrl + QWER and you've leveled it up. Skill leveling order is very easy to remember too.

**Comment by iNubbish** [comment]
What about for botting uses >~< @Xelamats

**Comment by Xelamats** [comment]
Most of the addons I use for that (ports) have them already built into them. If you truly want an Autolvlup, you don't need a port.. There is a perfectly functional one on Elobuddy. Works fine for botting.

**Comment by ryroy** [comment]
@Xelamats the addon on EB is not working atm. I'm currently using Autobuddy without movement or shop settings as a band aid. I'm using it for botting and the current ARAM bot addon that im using (that is ported and was on EB a few days ago) doesn't have autolevelup. Nevertheless it doesn't seem like something that takes up too much resource or effort to implement, so i made the suggestion.

**Comment by Xelamats** [comment]
Not bashing your suggestion. Just speaking what I believe.

----

I see it like:
- Have him port an Addon that will have to be updated once it is broken (just like the one on Elobuddy needs to be right now)
- You just wait for the Elobuddy one to be updated.

Option One = more work for him; once it breaks, gotta wait for the update.
Option Two = no work for him; just gotta wait for the update.

**Comment by ryroy** [comment]
the EB one is currently in patch 6.6, i don't think it's going to get updated any time soon. But ay what do i know, i'm just an unexperienced pleb anyway ^^"

Do you know of any good ports with autoleveling included then? honestly just curious here

**Comment by Xelamats** [comment]
https://github.com/KoalaHuman/EloBuddy

That's autosharp. It had autolevel working from what I saw before. Used it on 6.7 to up a few accounts before I got lazy and started cracking them, lol.

**Comment by hardique** [comment]
I think berbb`s work should be focused on addons that are done by L# devs and has nothing similar on EB,imo.

**Comment by ryroy** [comment]
@Xelamats i've been using it since the last patch and i can safely say that it didn't have an autolevel working, and the autolevel that's encouraged to be played with Autosharp in EB's post isn't functional atm.

**Comment by berbb** [comment]
Added to to-do list, no guarantee's tho.
