### ISSUE TITLE
Sejuani problem + elutility stuff

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#105]
-Elsejuani:When I disable e usage it doesn't use w too and when I disable w usage it use w & e
-Elutility: using smite to kill enemy or drags + what is ability tracker?

**Comment by dankmemer420** [comment]
Ability tracker tracks the abilities of enemy's and allies including what skill they're maxing and the cooldown of the spell. If you're asking if it uses smite to secure kills and drags, it does.

**Comment by Sharpino** [comment]
they're not working with me

**Comment by dankmemer420** [comment]
Have you cleared appdata? Seems like a general fix for PortAIO bugs.

**Comment by Sharpino** [comment]
will try and report back

**Comment by berbb** [comment]
Please update, I just fixed the ElSejuani Bug. I'm assuming you're talking about the Ability Tracker from ElUtilitySuite. 

The ability tracker from ElUtilitySuite tracks the time for many spells and items, it'll tell you  when Zhonya's will run out, when Akali's W runs out, when Yasuo's WindWall runs out etc...

**Comment by Sharpino** [comment]
It's not injecting now 
http://postimg.org/image/dbcjr7kmz/
