### ISSUE TITLE
Disable PortAIO Logo

### ISSUE THREAD

**Issue by DannyTheGod** [berbb/PortAIO#105]
Can I ?

**Comment by Muse30** [comment]
no.. and why? it only shows for like 5 seconds

**Comment by chienhao10** [comment]
is cool, but i saw the gif one, that gif looks lame....

**Comment by DannyTheGod** [comment]
because i want to stream with EB

**Comment by Xelamats** [comment]
@DannyTheGod You'll get banned no matter what. Streaming with any scripting platform is obvious af. Use streammode and it should make it go away.

@chienhao10 T_T I cry. To be honest, I just wanted to see if he could actually put a GIF in-game. I know it's crap. Lots of hate <3.

**Comment by berbb** [comment]
Done.

**Comment by DannyTheGod** [comment]
tks xD
