### ISSUE TITLE
Eat My Cass best prediction ?

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#106]
What is the best prediction for this scripts ? Because i tried OKTW and SDK on very high but missing sometimes ulti and Q W when enemy target cant be hitted.

**Comment by Lemonadez** [comment]
They dont miss. Your opponent is just good or have script evade on..

**Comment by Haxory** [comment]
SPred worked fine for me

**Comment by NentoR** [comment]
Missing ult a lot of times believe me. I will try SPred and give feedback.

**Comment by Lemonadez** [comment]
I just tested it against Bot and ult didnt miss at all. (SDK/L#). So Im guessing your opponent have evade.

**Comment by NentoR** [comment]
Nope i am sure they not have. Just casting sometime without calculate range.

**Comment by NentoR** [comment]
And now Eat my cass is removed nice :)

**Comment by berbb** [comment]
@NentoR The author of the script sent a DMCA to the github. It was either leave it or get sued.

**Comment by NentoR** [comment]
Can you explain this better ?

**Comment by berbb** [comment]
The author of the script, ChewyMoon, has a license on his script, it basically acts as a copyright. He reported my github for having content that goes against his license. Github sent me a DMCA notice and that I have 24 hours to remove his content before my github gets shutdown and a possibility of being sued.

**Comment by NentoR** [comment]
So no more Eat my Cass :( Good Alternative for it ?

**Comment by berbb** [comment]
Go on the discord and there's a link to it.
