### ISSUE TITLE
ElUtilSuite: Zhonya Problem

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#107]
Hey, yesterday I was playing against Zed. I had Zhonya usage enabled in ElUtility settings. Unfortunately, the Zhonya's active was triggered too early, so the immunity of my champion ended like 1< second before the Zed's mark exploded, so I still got the damage. Could you take a look at it? Will be grateful.

**Comment by berbb** [comment]
Fixed, increased the delay.
