### ISSUE TITLE
Vayne's Condemn

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#108]
Vayne condemn misses for me like 6/10 times ..
Is there anything that can be done with that to improve its accuracy?
I have tried with many different settings, yet every time I play her, the results are the same

**Comment by DannyTheGod** [comment]
try OKTW condemn

**Comment by berbb** [comment]
I've had success with SAC Condemn and 360 Hikicarry. But when using SAC make sure you edit the settings in "E Settings" such as accuracy.
