### ISSUE TITLE
Elutlity: Smite not working on drags and enemies

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#109]
Cleared appdata but still same problem

**Comment by DrHouse12** [comment]
Smite not working because smite addon is disabled right now, idk why. Berb ?

**Comment by Sharpino** [comment]
@berbb pls check this too

Champion: Gangplank
http://postimg.org/image/cxcgwze0r/

**Comment by lightduy94** [comment]
And Blade of Ruined King not working too!

**Comment by berbb** [comment]
Botrk and other items should be fixed. Testing smite rn,

**Comment by KiriharaSenpai** [comment]
@berbb can you check heal usage thanks for your hard work berbb

**Comment by berbb** [comment]
Fixed Smite on Enemies, KS and new Drags.
