### ISSUE TITLE
Lee Sin

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#11]
Doesnt Q as often in combo mode.

**Comment by dankmemer420** [comment]
It actually almost never Q's in combo mode unless it's an upclose target.

**Comment by berbb** [comment]
Will check it out, thanks.

**Comment by berbb** [comment]
Should be better, I've tweak the code to use EB's realtime prediction

**Comment by dankmemer420** [comment]
Will test and get back to you.
