### ISSUE TITLE
Olaf Q range

### ISSUE THREAD

**Issue by nightsole** [berbb/PortAIO#110]
Been playing Olaf for a while now , i dont know if the ported version of Olaf is outdated but you guys need to check the range on Olaf's Q, thing is in combo he throws the axe at a short distance and not the full length which causes the enemy counterpart to escape eventually.

**Comment by KiriharaSenpai** [comment]
yea you re right q predictio needs a tweak

**Comment by SidaRevamped** [comment]
fixed i created a pull request

**Comment by nightsole** [comment]
thanks
