### ISSUE TITLE
Crashing on respawn

### ISSUE THREAD

**Issue by CPT-imp** [berbb/PortAIO#115]
Game is crashing while respawning. Also tried with clean appdata.

_// Berb its awesome dude, nice work_

**Comment by berbb** [comment]
This is an error that I can't fix because it's not happening on my end.

**Comment by Xelamats** [comment]
We should start collecting some data.

@CPT-imp 
**Operating System (ex. Windows 7 Ultimate x64)**:
**Do you keep it updated?**:
**Have you installed these https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/#entry159210**:
**Do you have Microsoft Visual C++ Redistributable installed? What versions?**:

**Comment by rpgfreak128** [comment]
@CPT-imp Under Port Core setting tick off Skinhack that fixed it for me let me know

**Comment by terry3041** [comment]
Disable the skin hack solve my problem :)
You may have a try

**Comment by dankmemer420** [comment]
Yeah, skinhack was causing alot of crashes for me too.

**Comment by CPT-imp** [comment]
Uh okay thank you guys.

**Comment by Xelamats** [comment]
@CPT-imp 

Did it work for you too?

**Comment by lgndz** [comment]
Reporting in that disabling skin hack resolved this for me as well.

Do not use skin hack

**Comment by Xelamats** [comment]
@berbb 

Looks like this is solved. You can close this and put this fix on the ReadMe.
