### ISSUE TITLE
Fps Drop

### ISSUE THREAD

**Issue by Jokiblack** [berbb/PortAIO#116]
I have fps drop in last pach using ezreal, kog, missfortune. Only use Champ addont, no utility

**Comment by Xelamats** [comment]
Been playing kogmaw fine with no drops. Haven't tried the others.

**Comment by Jokiblack** [comment]
In 6.8. 0 drops :S

**Comment by berbb** [comment]
I was just testing the re-ported version riven I'm currently getting it also, I'm usually at 120-190. I'm straight up at 90-110 right now. Turned off ElUtility (which uses the most FPS in the pack) and no change to FPS, it's definitely not a PortAIO problem but it needs to be fixed.
