### ISSUE TITLE
i downloaded to local but cant install

### ISSUE THREAD

**Issue by chienhao10** [berbb/PortAIO#116]
i have installed common and today's update i cant install from local, but from git is fine.

log:
            Considered AssemblyFoldersEx locations.
            For SearchPath "{GAC}".
            Considered "Berb.Common", which was not found in the GAC.
            For SearchPath "{RawFileName}".
            Considered treating "Berb.Common, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL" as a file name, but it didn't exist.
            For SearchPath "bin\Release\".
            Considered "bin\Release\Berb.Common.winmd", but it didn't exist.
            Considered "bin\Release\Berb.Common.dll", but it didn't exist.
            Considered "bin\Release\Berb.Common.exe", but it didn't exist.

    Champion\Aatrox\Program.cs(13,20): error CS0246: The type or namespace name 'LeagueSharp' could not be found (are you missing a using directive or an assembly reference?)
    Champion\Aatrox\Program.cs(12,18): error CS0246: The type or namespace name 'LeagueSharp' could not be found (are you missing a using directive or an assembly reference?)
    Champion\Aatrox\Program.cs(14,15): error CS0246: The type or namespace name 'LeagueSharp' could not be found (are you missing a using directive or an assembly reference?)
    Champion\Aatrox\Program.cs(9,7): error CS0246: The type or namespace name 'LeagueSharp' could not be found (are you missing a using directive or an assembly reference?)
    Champion\Ahri\Program.cs(13,17): error CS0246: The type or namespace name 'LeagueSharp' could not be found (are you missing a using directive or an assembly reference?)

the rest are alll the same with namespace does not exist

**Comment by berbb** [comment]
Compile Berb.Common and find the .dll from bin/Release or bin/Debug and just add it as a reference.

**Comment by chienhao10** [comment]
so i just copied the Berb.Common.dll to Addons\Libraries and it worked now for your git and local
but i translated some of the addons and upload to my git, it just wont install from remote.

**Comment by chienhao10** [comment]
Processing resource file "Properties\Resources.resx" into "obj\Release\PortAIO.Properties.Resources.resources".
    C:\Users\huang_000\AppData\Roaming\EloBuddy\Repositories\8C8583AF\Breb移植系列\移植合集\Properties\Resources.resx(587,5): error MSB3103: Invalid Resx file. Could not find file 'C:\Users\huang_000\AppData\Roaming\EloBuddy\Repositories\8C8583AF\Breb移植系列\移植合集\Resources\Thumbs.db'. Line 587, position 5.

C:\Users\huang_000\AppData\Roaming\EloBuddy\Repositories\8C8583AF\Breb移植系列\移植合集\Properties\Resources.resx(587,5): error MSB3103: Invalid Resx file. Could not find file 'C:\Users\huang_000\AppData\Roaming\EloBuddy\Repositories\8C8583AF\Breb移植系列\移植合集\Resources\Thumbs.db'. Line 587, position 5.

**Comment by chienhao10** [comment]
everything is same in local and git it just keep having that error and i didnt change anything in resources

**Comment by berbb** [comment]
Check if Thumbs.db is still in resources folder.

**Comment by chienhao10** [comment]
yes your are right.... how did you get that file on there..github just wont realize the file.....
