### ISSUE TITLE
suddenly it stopped working 

### ISSUE THREAD

**Issue by 420imyello** [berbb/PortAIO#118]
hello i have a problem that portaio addon doesn't inject suddenly 

i removed the addon and berb common and installed them again without any hope :(

**Comment by 420imyello** [comment]
i think it is working but not shown only in menu cuz caitlyn did auto ult on low hp so its working but i cant find port in menu

thanks :)

**Comment by Muse30** [comment]
nothing we can really do.. try deleting your appdata

**Comment by 420imyello** [comment]
i deleted it and still not injecting it was working fine and the other addons are working fine

any tip that i can do ?

**Comment by berbb** [comment]
Refer to "P: My Menu is bugged, fix pls." in this thread : 
https://www.elobuddy.net/topic/3110-faq-troubleshooting-read-before-posting-a-thread-0512/

But yeah as @Muse30 said, this isn't a problem on PortAIO's side. It seems to working good : http://image.prntscr.com/image/aaddacc6e863420a86e420da8be4d0ad.png

**Comment by 420imyello** [comment]
@berbb maybe its not PortAIO problem but it was working with me more than 1 week and suddenly without doing anything it stopped  and other addons still working fine with me

i tried everything in the post of the troubleshooting and still nth so i hope you have another tips that i can do :(

thanks
