### ISSUE TITLE
The champion configuration do not appear in the EB menu

### ISSUE THREAD

**Issue by ySpark3** [berbb/PortAIO#118]
(Sorry for the bad english)
I can't change de config addons because they dont appear in the EB menu.

**Comment by berbb** [comment]
Screenshot?

**Comment by ySpark3** [comment]
How i can explain? When a I ll play the champ can combo, harras all this things, but i cant configure.

**Comment by Xelamats** [comment]
@ySpark3 

Explain it the best you can in English and then in your language. Maybe someone here knows the language and can translate for you. That or use google translate XD

Do you have problems with it harassing the enemy even after you unticked auto harrass? Is there nothing that pops up when you press Shift for the champion (look in all of the settings)? What exactly is wrong?
