### ISSUE TITLE
Sivir scripts bugs - DrHouse12

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#12]
Hey, i found new bugs in sivir scripts.

OneKeyToWin: 
- sivir not using E shield for spells
- not using spells for laneclear

Exor Sivir
- not using E shield

**Comment by TheKushStyle** [comment]
OneKeyToWin

- Sivir won't attack (Prob Something with after/before attack.)

**Comment by SidaRevamped** [comment]
Ok i'm on it

**Comment by berbb** [comment]
https://github.com/berbb/PortAIO/commit/ae59f90b982061a9a30553cf8d1cb4c0fbc2b693
