### ISSUE TITLE
autosharp

### ISSUE THREAD

**Issue by fluut** [berbb/PortAIO#120]
it keeps moving to the mouse as if im pressing an orbwalk key without pressing any, and if i disable moving to the mouse in the eb orbwalker it just hugs the turret 24/7. it was a custom on aram, had elutility and autosharp enabled only

**Comment by berbb** [comment]
If I read the code right, it needs allies/enemies to function correctly. I do not recommend testing AutoSharp right now, I haven't fully tested it yet in a norm because the queue time is so long right now.
