### ISSUE TITLE
Suggestion about PortAIO

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#121]
PortAIO should save setting for each champion. Like Kalista, i want to use EB addons so i tick "Only Ultilities" mode, i use Jinx PortAIO.
So next time i load PortAIO with Kalista, it will only use Ultilities. And for Jinx and other champion not played yet, it still load Champion + Ultilities mode.

I'm testing Kalista and will feedback soon

**Comment by berbb** [comment]
Not sure if Menu Saving Config is like that.
