### ISSUE TITLE
Lulu script causes low FPS

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#124]
Sometimes even as low as 5fps,pls fix

**Comment by berbb** [comment]
Yes, I love reports like these, thanks for telling me when or how you think it happens, or what time in the game this happens or in what stage of the game this happens.

**Comment by lyn690697457** [comment]
After the script is loaded, it is so, I even tried to open the script only hero, but still useless
Especially when more than one person as long as the combo will drop very serious

**Comment by berbb** [comment]
I'm not sure how that's suppose to help me...

**Comment by lyn690697457** [comment]
Sorry to bring you in trouble，OK no problem。FPS does not reduce the

**Comment by lyn690697457** [comment]
ty

**Comment by berbb** [comment]
No, no, no I'm not trying to down you. If the script is bringing FPS Drops, I want to know when it drops (teamfights, laning phase, or even at base etc...) and what you're using in the script that makes the FPS drop.

**Comment by lyn690697457** [comment]
leave the base and When combo。
When just entered the game，Only in the spring when it 5FPS。
I do not know why

**Comment by lyn690697457** [comment]
（teamfights, laning phase, or even at base etc ）These will lead to，When I entered the game only 5FPS。T-T
