### ISSUE TITLE
ElRengar doent use Q in combo

### ISSUE THREAD

**Issue by krychol49** [berbb/PortAIO#125]
As i said before sometimes when I press space (combo) rengar doesn't want to attack enemy champions he just running next to them.

**Comment by berbb** [comment]
Orbwalker problem. Disable stick to target...

**Comment by krychol49** [comment]
It is disabled

**Comment by berbb** [comment]
It's not a PortAIO problem then because no where in the code disables attacking or issues a movement command and it will always cast Q when your ferocity is less than or equal to 4 as long as you can move and there's someone in your AA range. Try clearing appdata.

**Comment by Sharpino** [comment]
He is casting it but very clunky

**Comment by KiriharaSenpai** [comment]
btw nathan updated his rengar can you check it out berbb

**Comment by berbb** [comment]
Alright updated,
