### ISSUE TITLE
Kalista E failed a lot of time

### ISSUE THREAD

**Issue by 3ackdoor** [berbb/PortAIO#125]
E calculation doesn't seem to work good ,it doesn't kill enemies and leaves them with a little HP left.

**Comment by berbb** [comment]
It'd be great to tell me which Kalista you're using out of the three...

**Comment by 3ackdoor** [comment]
Sorry, I used Kalista:Rework but how to change to another kalista script?

**Comment by IlikeBaconLol** [comment]
U can go on PORTAIO misc in the eb menu and here u will see a toggle title for change of addons
