### ISSUE TITLE
Irelia God crashing

### ISSUE THREAD

**Issue by PunchingJay** [berbb/PortAIO#126]
IreliaGod Dualport addon is crashing when doing Combo. Its always crashing for me when pressing combo and irelia is doing her E. Logs are showing nothing :( 

- Little suggestion : can you add for laneclear only q on unkillabe minions like in the " main " port?

thank you

**Comment by Muse30** [comment]
I dont see that option on the original

**Comment by PunchingJay** [comment]
In Challengerseries I can choose " Q farm mode to " only unkillable "

**Comment by Muse30** [comment]
oh well thats from other script not for ireliagod but I guess I can add it and for the crash I will test soon
