### ISSUE TITLE
Miss Fortune Issues

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#126]
randomly uses E even on the areas without any enemies
and q is broken
doesn't go through a minion standing in front of the targeted enemy
she casts it on enemies
not on minions :/
awaiting a fix :D

**Comment by fluut** [comment]
just played a game with her, seems fine. make sure you set it to sdk pred in the oktw menu

**Comment by Lurker7** [comment]
ahh so it's all about changing the pred to the sdk one, huh?
I was basically completely sure that it doesn't work since it basically wasn't casting any prediction based spell correctly with all predictions that I tested it with, that is all of the available ones except sdk ...
Sorry for incovenience then :S
