### ISSUE TITLE
Veigar R Prediction Too Early

### ISSUE THREAD

**Issue by iNubbish** [berbb/PortAIO#127]
Champion Name - Veigar

Issue/Problems - Veigar keeps casting R really early, so essentially not being used as an execution.
I feel like it's for keeping them in range of Q to get stacks off of that, but I personally prefer it to just execute them. No champions that I casted R on were using Zhonya's to clarify, simply were just standing there dueling as usual. Yasuo for example.

**Comment by berbb** [comment]
Is "When can be Kill, Only use R" on?

**Comment by iNubbish** [comment]
Yes

**Comment by berbb** [comment]
I pushed an update that should fix this but leaving this cause I haven't tested.

**Comment by iNubbish** [comment]
Alrighty then, thanks berb <3 I'll keep this issue open while testing

**Comment by iNubbish** [comment]
Recently played a game with Veigar. The prediction is iffy, it sometimes gets a good R execution, othertimes it's pretty early. A full Combo tends to give a reliable R execution, but when it comes to say walking up to someone and R'ing I'd say 65/45 chance of getting a good execution.

**Comment by berbb** [comment]
Should be perfect now.
