### ISSUE TITLE
Don't cast any spells

### ISSUE THREAD

**Issue by Hiirko** [berbb/PortAIO#128]
i was playing with Ezreal and Ekko and don't cast any spell in combo

**Comment by GreatWhite181** [comment]
@Hiirko I think this is an EB problem. I was getting this with Yasuo on portAIO, so I tried aka's Yasuo by itself and that wasn't casting either.

**Comment by CPT-imp** [comment]
Having the same problem on different champs (yasuo, ez etc.)

**Comment by StefanBulka** [comment]
Me too :(

**Comment by berbb** [comment]
Why does this same group have the problems I don't experience? qq. I can't fix it because it's not happening to me, it's using spells for me.
