### ISSUE TITLE
Could that be ported?

### ISSUE THREAD

**Issue by ThugDogeNulled** [berbb/PortAIO#128]
https://www.joduska.me/forum/topic/139477-orbwalker-addon-orbwalking-without-automatic-movement/

https://www.youtube.com/watch?v=vaCPC-auOaw
https://www.youtube.com/watch?v=YRvCnHbtlEc

With this we basically orbwalk manually, the orbwalker just hit the targets, the movement is made manually, seems like an awesome humanizer.

**Comment by iNubbish** [comment]
Is disabling "Move to Mouse" in advanced orbwalker settings literally not the same thing?

**Comment by ThugDogeNulled** [comment]
Yeah, i hadn't noticed that function, thank you, i'm gonna use that
