### ISSUE TITLE
Lee sin addons

### ISSUE THREAD

**Issue by 98181735** [berbb/PortAIO#129]
Valrave crashes when i press spacebar
ElLee q prediction needs improve 
Freshbooster 60-70% of qs are missed does not matter if i set hitchance from 1 to 6

**Comment by berbb** [comment]
Valvrave is known to crash, I'm still investigating a fix. And I pushed updates that should improve FreshBooster and ElLee.

**Comment by dankmemer420** [comment]
It still seems wonky to me aswell, even after the update. Is there anyway to make the pred like valvrave? valvrave q pred is so good for lee.
