### ISSUE TITLE
[*********] NEW L# ORBWALKER ISSUES HERE

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#13]
R.I.P

**Comment by Wa1L** [comment]
Is there a way to use EB orbwalker ? i tried to make orblwaker to NOPE in PortAIO Menu but still loads L# Orbwalker and the L# Orbwalker misses Every single CS for me

**Comment by berbb** [comment]
nope. what's your ping and who are you playing?

**Comment by Wa1L** [comment]
Ping Around 80-100 , Played Jayce with OKTW

**Comment by berbb** [comment]
Alright, I just tested and it's a Jayce-only error, the calculations are wrong for him I'll push a fix for the calculation ASAP.

**Comment by samigod** [comment]
i don't know if this is a legit request or no , but i used elobuddy's orbwalker with autobuddy and PortAIO but now i can't do so because it seems like autobuddy doesn't work with L# orbwalker , so i'm asking if i have something wrong or it's normal to have this ?

**Comment by WayToDie** [comment]
It is possible to completely **disable Elobuddy ORBWALKER**? because I do not use any scripts that use it
