### ISSUE TITLE
Graves Menü Fix Please

### ISSUE THREAD

**Issue by toughra** [berbb/PortAIO#130]
Graves Q is there another option

**Comment by Dunkka** [comment]
What's wrong with it?

**Comment by Xelamats** [comment]
Can you provide more information? Like what needs to be Fixed in the menu?

"Graves Q is there another option" Is Graves Q in the menu broken? How is it broken? Like if you untick to use it it'll still use it or what?

**Comment by berbb** [comment]
Auto Q + Harass is the only thing in the original OKTW menu, which is why it's the only thing on this port.
