### ISSUE TITLE
annie doesn't work

### ISSUE THREAD

**Issue by fluut** [berbb/PortAIO#131]
combo, laneclear, harass doesn't do anything other than autoattacks, all 4 preds tested in oktw

**Comment by Dunkka** [comment]
Hi, i just tested this and everything works for me

**Comment by fluut** [comment]
do you use oktw? if so what settings?

**Comment by rman200** [comment]
annie is really buggy and missing a lot of features, just play another champ

**Comment by Dunkka** [comment]
i use Spredict i think its called, pretty much everything is default

**Comment by berbb** [comment]
You were most likely playing in One For All, luckily I fixed it. Update please!
