### ISSUE TITLE
Port Suggestion / Easy-Good Addition

### ISSUE THREAD

**Issue by voidsurfer** [berbb/PortAIO#132]
Hey, since Sebby OKTW is already ported i take it that SebbyLib is also ported. Hence you could easily port Sebby Ban War :)

I think it would be good since there are not any humanizers on the EB platform that performs the same operations.

**Comment by Xelamats** [comment]
What does it actually do? Tried searching it up on google but found nothing really about what it fully does.

**Comment by voidsurfer** [comment]
It limits both clicks/spells and maximum amounts of packets sent to the server from your client.

**Comment by berbb** [comment]
Sure. Added to to-do list.
