### ISSUE TITLE
ElUtility Suite/hi i am gosu

### ISSUE THREAD

**Issue by hardique** [berbb/PortAIO#132]
@berbb @Muse30 

1.ElUtil - QSS/Cleanse  : sometimes,there aren`t important spells right there which it should clean/qss.For example - Ryze W,Malphite R and others.

2.hi i am gosu Vayne - since 28-29.05.2016 stopped using Q in combo mode.

Thanks guys,if any other info needed-will answer.

**Comment by Muse30** [comment]
hi i am gosu Q working fine

**Comment by hardique** [comment]
nvm,cleared Appdate-working fine.
another question,can u add list of gapclosers for using condemn (hi i am gosu)?cuz sometimes it is very usefull and sometimes like using when trundle uses W :D

**Comment by berbb** [comment]
Adding a list for gapcloser would force us to re-code how gapclosers work to get a menu option and use the menu option.
