### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by Requital** [berbb/PortAIO#133]
OKTW Pred and Spred dont seem to work like L# ones. For ex. Jinx and Ez miss many skillshots while harrasing or even in combo.

**Comment by fluut** [comment]
use sdk/common, they are better. i prefer sdk

**Comment by Meroto3** [comment]
+1. OKTW and SPred just DON'T work. If you want to test this, just pick Ez, tell your friend to walk in a straight line and try to hit some Qs in combo mode or harass. It shots where the enemy was, not where it will be. SDK pred is working fine, so use it.

**Comment by Requital** [comment]
aight thanks for helping

**Comment by SamisDaShine** [comment]
Oktw ---> SDK
