### ISSUE TITLE
LCS/iLucian bugs

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#135]
LCS Lucian; Did not use extended Q during the entire game
iLucian: Console spammed with this:
========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.Common.Spell.IsInRange(GameObject obj, Single range)
   at iLucian.Lucian.AutoHarass()
   at iLucian.Lucian.OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================

**Comment by dankmemer420** [comment]
LCS works flawlessly for me, have you tried clearing appdata and trying again?

**Comment by IlikeBaconLol** [comment]
LCs lucian has a lot of problem if you dont clear appdata often but he is so opppppppp when u do

**Comment by Monnq** [comment]
I've cleared my AppData folder still, no extended Q :/
