### ISSUE TITLE
The Snowball logic is kinda messed up

### ISSUE THREAD

**Issue by ryroy** [berbb/PortAIO#137]
Not sure if error in port or if its the actual script, but im like literally always taking the snowball if it hits a champion. No matter if they're under turret, if im 1v5, it will always take it if it hits a champion, which is overall pretty bad unless you're 31/3/10 on swain *cough cough* portaio is broken *cough cough*.

**Comment by berbb** [comment]
It's the ElUtilitySuite, you should disable it, I don't think the logic is good either. Just turn it off and self cast it xD

**Comment by ryroy** [comment]
actually i prefer having it ticked than not because I'm botting and it would be troublesome to change the summoners since volibot and ezbot don't change the summoners in aram >.> but yeah, feelsbadman, thanks for the heads up anyway ^^ how do you feel about adding an autoshop/level port with a toggle to your aio?

**Comment by berbb** [comment]
@ryroy Already have level in my to-do but I wouldn't mind porting an auto buy either :)

**Comment by ryroy** [comment]
@berbb oh, please do! Looking forward to it ^^ it'd ease my life a ton, right now I'm loading autobuddy without movement so that it buys stuff and levels up in aram
