### ISSUE TITLE
"Please check the logs" Cant install PortAIO

### ISSUE THREAD

**Issue by xxJordanbroxx** [berbb/PortAIO#138]
Every time I remotely install port aio, it says check the logs, I've tried deleting appdata and it sill happens

**Comment by Xelamats** [comment]
Try these:

**Compile Errors**
Make sure you have Berb.Common installed @ https://github.com/berbb/EloBuddy

If you still recieve compile errors refer here : https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/

**Comment by xxJordanbroxx** [comment]
Yep, done all those and it still occurs.

**Comment by xxJordanbroxx** [comment]
I cant install the new update thought i have version "129"of PortAIO and that version WILL install

**Comment by xxJordanbroxx** [comment]
This is what it sais in the logs "**Project "C:\Users\Jordan\Downloads\niggers\PortAIO-master\PortAIO.csproj" (default targets):

Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
Target CoreResGen:**"

**Comment by Xelamats** [comment]
Uninstall MS Build Tools and try reinstalling it. 

"in which case you may be able to resolve this by installing the appropriate version of MSBuild"

**Comment by xxJordanbroxx** [comment]
http://prntscr.com/b17f19 
Have done everything. Is there any other way to update my exsiting "129" version of portAIO without redownloading?

**Comment by berbb** [comment]
Make sure Berb.Common is the latest update. If your local version Berb.Common isn't update then the latest version of PortAIO won't work.

**Comment by Xelamats** [comment]
@berbb 

Unsure how it was fixed but we ended up getting it to install.
