### ISSUE TITLE
VHR Q Normal mode crash

### ISSUE THREAD

**Issue by hardique** [berbb/PortAIO#138]
Using Normal mode for Q in VHR crashes game.
enemies-shyvana,ww,galio,fiddle,irelia.
team-udyr,darius,ryze,morgana.

condemn style-crashes with any .
utility addons ON : ezEvade,NabTracker,ElUtil,Gank Alert.

upd : tested a little bit more-seems like galio is the reason of crash.

**Comment by berbb** [comment]
I have no idea why Galio would be the source of the crashing but will check it out.

**Comment by KiriharaSenpai** [comment]
can you try that run portaio in champonly mode`

**Comment by hardique** [comment]
Will try to check it out once more ,but in that game it was crashing when pressing combo against galio/very near galio .smth like that.will update and tell if it happens again
