### ISSUE TITLE
Jhin not working (Gamemode tested)

### ISSUE THREAD

**Issue by Dunkka** [berbb/PortAIO#139]
Tested with One for All gamemode

Had a problem with last game mode (Hexakill) where only utilities worked, didn't bother reporting because it was the last day of the game mode

**Comment by Dunkka** [comment]
Lux broken too (one for all tested aswell)

**Comment by Xelamats** [comment]
Berb - Today at 7:54 PM
One thing, some champion scripts on PortAIO are not compatible with One For All because of menu issues.

**Comment by berbb** [comment]
Fixed, Jhin to work with OFA.
