### ISSUE TITLE
Vayne Hunter Reborn crash

### ISSUE THREAD

**Issue by RainGK** [berbb/PortAIO#14]
Heya, thanks for coming back to the project, a lot of us missed ya.

Champion Name (eg. Ahri) / Utility (eg. Evade) : Vayne

If this is an issue about a champion, is this Champion dual-port supported (Check via PortAIO Misc)? If yes which one? : Vayne Hunter Reborn

Issue/Problems (Try to be as detailed as possible) : The game freezes when AAing an enemy champion in combo mode, I've only had this occur to me when AAing a Lucian, I haven't seen anyone else with this issue so it might be me.

**Comment by berbb** [comment]
Just tested and I'm not receiving any crashes. This may just be on your end but I'll keep this open just in case someone else has the issue. If someone else has this issue I'll look more into it.

**Comment by hardique** [comment]
same here,no crashes with VHR

**Comment by RainGK** [comment]
Just tested, might have been fixed in one of your commits, thanks either way man.
