### ISSUE TITLE
OneKeyToWin menu error (Jinx,Graves,Ashe,Cait)

### ISSUE THREAD

**Issue by toughra** [berbb/PortAIO#141]
there is another option from auto shapes, for example, jinx (q) and (e) they don't have the abilities

ss : http://imgur.com/9UDW3gq

**Comment by berbb** [comment]
Have you updated PortAIO recently?

**Comment by toughra** [comment]
No,

 it was like yesterday I'm updating right now

**Comment by toughra** [comment]
fixed the problem
