### ISSUE TITLE
Nabbtracker makes FPS Drop

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#142]
I have about ~80 FPS and with Nabbtracker, it still 80 FPS but sometimes, it drop to 10 FPS for no reason for about 5 seconds then back to normal. Then sometimes later it keep drop to 10 FPS then back to normal again.
Please check it!

**Comment by lightduy94** [comment]
P/s: I disabled Nabbtracker and use Mastermind, then it not happened again.

**Comment by berbb** [comment]
This should not be happening at all, the code for the text drawings are as simple as it can get and should not impact the game at all. Although, it may be the ward tracker that's causing the FPS.

I updated it so that you can disable the Ward Tracker.
