### ISSUE TITLE
The cheater issue

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#143]
I know this isn't an important issue and i actually don't use it but i think i should let u guys know since noone reported it yet. The cheater utility appears to be broken ( it works but like 15 minutes into the game it says that everyone in the game is using L# common)

**Comment by fluut** [comment]
thecheater is barely accurate anymore, it's only good for having a rough idea who is probably scripting when they have like 80+ detections

**Comment by inphratiic** [comment]
i know, like i said i don't use it, i'm just reporting that isn't working properly

**Comment by fluut** [comment]
as i told you, it's working semi-proper, and the port is 100% fine. berb didn't add this so it can 100% track every single scripter 100% accurate, that part is long past it's time. it not working properly is not an issue, that's how it is.

**Comment by inphratiic** [comment]
u didn't understand me mate, i'm not criticizing berb neither saying it's his fault , he probably already knew it wasn't working properly , creating the issue also informs other users of the state of that script. Created this just to let people know they can't trust on the script ( yeah this for the scripters who go wild on chat calling other guys scripters when they get owned xD). Also have to admit that you have a point on saying this isn't a issue so i'm going to close it
