### ISSUE TITLE
vayne

### ISSUE THREAD

**Issue by SamisDaShine** [berbb/PortAIO#144]
Who is the best? Hi I'm gosu/Vayne Hunter Reborn?

Give op settings! 😂

**Comment by hardique** [comment]
imho,i prefer VHR with normal tumble and marksman/revolution condemn.
for me hi i am gosu is a little bit slow with condemn,but it is still good.

**Comment by DjVrip** [comment]
I prefer i am gosu, I tested VHR but I find that the default settings was really bad, I would have to test the settings to hardique ^^

**Comment by hardique** [comment]
@DjVrip nvm,dude.i came back to i am gosu.VHR is crashing for me when using Normal mode for Tumble and I don`t like Reborn one.
Also Shine# condemn is not that good and VH Revo casted today 2 times too late in very important moment,so I came back to hi_i_am_gosu.

The only problem for me was AntiGapcloser in it,but I solved it by unticking everything in core menu-gapclosers.

**Comment by DjVrip** [comment]
@hardique hi im gosu is godlike for vayne ^^
