### ISSUE TITLE
Lux random E cast

### ISSUE THREAD

**Issue by DrogonRocks** [berbb/PortAIO#145]
Hi Berbb 
Lux addon working like a beast, prediction is almost perfect, but i found one problem, sometimes it cast E when im recalling, when im in the base, walking, farming (even tho i untick E for farm), but most of the time it happens when im recalling so i have to recall again, besides that everything is working good
console error here:
http://prnt.sc/b1c7y4

**Comment by berbb** [comment]
Fixed, let me know if it's still happening.
