### ISSUE TITLE
Lucian semi-manual R,W prediction

### ISSUE THREAD

**Issue by hardique** [berbb/PortAIO#149]
Berbb,after porting VHR and fixing other issues,please,take a look at Luc.
when using semi-manual R key,it starts to ult,but cancels after 1-2 secs aproximatelly.

and in combo mode logic for W is weird,sometimes it shoots it anyway,when there is an enemy running away at 100 hp.

Thanks in advance and waiting for VHR :D

**Comment by hardique** [comment]
seems like i find out ...
if u accidently press semi-manual key one more time  when already using it-it will be canceled.

the only issue-not using W to kill an enemy at low hp,which can be killed with W.

**Comment by berbb** [comment]
Fixed the issue with W, it should use W when the target HP is lower than W's damage. I can't really do much about FPS drops.

**Comment by hardique** [comment]
thanks ,dude.
