### ISSUE TITLE
L# orb

### ISSUE THREAD

**Issue by cuncon1432** [berbb/PortAIO#15]
I can not be turned off L # orb (, or if used , L # orb it should shut down eb orb) .I need you to fix it

**Comment by cuncon1432** [comment]
I passed nope still not been

**Comment by cuncon1432** [comment]
![image](https://cloud.githubusercontent.com/assets/18423481/16877787/0ab2d016-4ad4-11e6-9570-9284062574f3.png)
:( 2 orb in game , 
affect me.

**Comment by dankmemer420** [comment]
You can only use the L# Orbwalker atm he hasn't removed it.

**Comment by cuncon1432** [comment]
use L# orb ( don't atk with tap V )
![image](https://cloud.githubusercontent.com/assets/18423481/16878500/fa48f2e8-4ad6-11e6-861c-3b84abe0c98d.png)
don't L# orb ( it's a great return average )
![image](https://cloud.githubusercontent.com/assets/18423481/16878557/2f70cc98-4ad7-11e6-9145-cdb6d21fc260.png)
(or if used , L # orb it should shut down eb orb ) :D
