### ISSUE TITLE
Lee Sin insec

### ISSUE THREAD

**Issue by Dunkka** [berbb/PortAIO#150]
It was working before, now it just places a ward to get to the target and kicks him away from you
am i doing something wrong?

**Comment by berbb** [comment]
How often is this happening?

**Comment by KiriharaSenpai** [comment]
this issue same on original addon a lot of users gave feedback about that issue to brian hope he gonna fix that but theres a fix for that clear your appdata per every game

**Comment by berbb** [comment]
Yeah, Valvrave hasn't had an update in a while, just wait for Brian @ L# to update it and I'll get right on it.
