### ISSUE TITLE
crashing with teemo

### ISSUE THREAD

**Issue by fluut** [berbb/PortAIO#152]
normal draft, enabled stuff:
- ss:teemo (teemo isn't dual port)
- elutility
- nabbtracker
- skinhack
- recalltracker
- gankalerter
- evade
- traptracker

**Comment by inphratiic** [comment]
can u explain what were u doing  when the crash happened?

**Comment by fluut** [comment]
i was holding spacebar chasing a ryze, didn't have any active items, had flash and tp, and idk how to open the console

**Comment by pellep12** [comment]
You enable the console in elobuddy..
In-game Settings > Enable Console

**Comment by berbb** [comment]
There's nothing special in Teemo's code that causes it to crash, My only suspect would be SkinHack (which caused crashes before) and ElUtility. I'll investigate this moreover on ElUtility.
