### ISSUE TITLE
D_RekSai

### ISSUE THREAD

**Issue by Demisemo** [berbb/PortAIO#153]
Jungle timeDo not use I Q / E Clear 

When will kill each other

He would have been boring

**Comment by Muse30** [comment]
what? sorry I cant understand you

**Comment by Demisemo** [comment]
@Muse30  In the Jungle Clear will not work QWE 

W would have been very strange, you test

**Comment by Muse30** [comment]
will check

**Comment by Muse30** [comment]
fixed
