### ISSUE TITLE
Vayne Reborn sometimes doesn't use AA or spell in everymode (combo, harass, laneclear)

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#153]
Vayne Reborn sometimes doesn't use AA or spell in everymode (combo, harass, laneclear)

**Comment by iiChopper** [comment]
For me works perfectly mate.

**Comment by KiriharaSenpai** [comment]
yes sometimes it does like that not attacking target just waiting for you to do a autoattack

**Comment by iiChopper** [comment]
i am not experiencing any problems at this moment

**Comment by hardique** [comment]
had same issue,happens sometimes.

**Comment by ySpark3** [comment]
Just press f5

**Comment by berbb** [comment]
I've updated it so it would fix some problems that would "mayce" endorse this behavior.
