### ISSUE TITLE
Caitlyn

### ISSUE THREAD

**Issue by 420imyello** [berbb/PortAIO#154]
OKTW

 auto W in bush is not working 
 and auto R still early 
Thanks :)

**Comment by berbb** [comment]
Updated to fix Auto R, I changed the method of calculating the targets health. But I haven't checked Auto W bush yet.

**Comment by 420imyello** [comment]
i tested the auto R it's closer and better but still miss sometimes 

ty :)

**Comment by xxbattonxx** [comment]
well dont want it to be exactly perfect then you have sure fire chance getting caught

**Comment by berbb** [comment]
@420imyello What do you mean by missed? Like it hits someone else or the damage is off?

**Comment by 420imyello** [comment]
@berbb the damage is off :(

**Comment by Muse30** [comment]
@420imyello auto R should be fixed now, I tested several times

**Comment by 420imyello** [comment]
thanks guys gonna test and feed back ^_^
