### ISSUE TITLE
Few feedback about Yasuo, Kalista

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#154]
1. YasuoPro:
Do nothing in everymode, even an AA.
2. Kalista:
Reborn and Challenger doesn't AA to Flee.
Reborn (or Challenger) doesn't use AA on minions to gapcloser.
Draw E damage on Health bar didn't work on all Kalista.
About Reborn's draw E damage percent. Please round it to unit, it hurts my eyes now!

**Comment by DannyTheGod** [comment]
YasuoPro makes game crash , plsss check BERB :(

**Comment by berbb** [comment]
The Kalista's don't do auto attack to flee because their scripts don't support it and I'm not going to add it. I'll check everything else tho.

**Comment by berbb** [comment]
Yasuo Pro is working fine, but it would help to know when you crashed or a guess of how you think you crashed. You're probably playing OFA.

Fixed the Kalista damage %.
