### ISSUE TITLE
Tamh Kench sometimes makes game Freeze.

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#155]
Tamh Kench sometimes makes game Freeze. Please take a look!

**Comment by berbb** [comment]
I can't reproduce something that only happens sometimes lol. I could try to reproduce it if you gave me some information though. Like, when you froze in the part of the game (mid game, early game, team fighting)

**Comment by lightduy94** [comment]
It freeze for me at Early game. I just tested it in a custom AI game. Seems that it freeze when i'm low health

**Comment by berbb** [comment]
Seems like I don't have TK, can someone else test it and confirm this?

**Comment by berbb** [comment]
Added to to-do list, but I can't do much because I don't have TK.
