### ISSUE TITLE
Hi im gosu random condemn

### ISSUE THREAD

**Issue by DjVrip** [berbb/PortAIO#157]
Hi! 

I play with Hi im gosu, but since yesterday the condemn bug, always condemn on empty (no wall) it happens at least 6 times a game
And I check E (toggle) and uncheck E interrupt and gapcloser but always condemn the support :/

**Comment by DjVrip** [comment]
I forgot to specify it must have an option KS because every time condemn random when there is 5% HP or 10% HP

**Comment by berbb** [comment]
The only time E cast's is if it's on a Gapcloser, Interrupter, E on Next AA, or E to condemn. I pushed an update that changes the E logic.
