### ISSUE TITLE
Valvrave Sharp Yasuo

### ISSUE THREAD

**Issue by primec** [berbb/PortAIO#16]
1) I can't turn off LastHit with Q3.
2) Q1/Q2 works only sometimes while LaneClear, but I want to use it instantly after I press LaneClear button.
3) Harass with Q doesn't work in Hybrid mode, only AA works.

**Comment by berbb** [comment]
Harass champs with Q works now, LC Q/Q3 should be faster, fixed disable Q3 in lasthit.
