### ISSUE TITLE
Challenger Lucian problem

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#160]
Not using auto R
semi r key not working
Can't manual cast r "block r unchecked"

**Comment by berbb** [comment]
Auto R menu option was removed because there was no backline code for it in both PortAIO version and official version.

Will check out manual R and semi-R.

**Comment by inphratiic** [comment]
yeah i experienced this problem too, if u have semi-ult key set to R or block manual R it would not let u use manual ult ( u need to uncheck both and F5 so that u can use manual ult again)

**Comment by berbb** [comment]
Changed Keybind.
