### ISSUE TITLE
iLucian

### ISSUE THREAD

**Issue by Pikachu7** [berbb/PortAIO#162]
don't use e on combo 
use e on jungle clear and killsteal (eq)
but dont use e on combo

**Comment by berbb** [comment]
Will check.

**Comment by tamtuy1990** [comment]
i think you should add holalucian

**Comment by berbb** [comment]
@tamtuy1990 How would that fix this error?...

**Comment by tamtuy1990** [comment]
oh , i don't know about program , you can refer lazy lucian about e on combo

**Comment by Muse30** [comment]
this should be fixed
