### ISSUE TITLE
Fiora doesn't do anything.

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#162]
Fiora doesn't do anything in everymode. Just AA and Tiamat working.

**Comment by berbb** [comment]
Is your EB okay? You've reported that nothings working when I just went in a custom game and tested her and she's working fine, using spells and everything.

**Comment by berbb** [comment]
You're playing on OFA aren't you?

**Comment by lightduy94** [comment]
No. I just play in custom match with AI.
And Kog'maw ChallengerSeries didn't use R for me too. No matter what %HP i set

**Comment by lightduy94** [comment]
And i tested Ezreal too. Working fine but OKTW pred + Spred not as good as it should. But i found that SDK pred are good as 80% of OKTW Pred in bansharp.
Is it normal or not?

**Comment by berbb** [comment]
I can't say if prediction is normal or not, it's the near exact same code but not the same performance, idk. I just pushed an update that should fix the Kog'Maw bug.
