### ISSUE TITLE
Vayne

### ISSUE THREAD

**Issue by TheDudey** [berbb/PortAIO#164]
Idk if ist a bug but both vayne addons are using codem very unfrequently sometimes codem at good Position sometimes just dont use for two Combos or longer... if i refresh working instantly again already updated and deleted appdata

**Comment by KiriharaSenpai** [comment]
yea you should set it a little bit personal configuration no problem with port same on original assembly

**Comment by hardique** [comment]
changed condemn style to marksman/gosu-working pretty good.

**Comment by berbb** [comment]
Sadly, like @KiriharaSenpai said, the original assembly has some issues with the accuracy of the condemn also. But, messing around with the settings should get you where you want to be, have fun!
