### ISSUE TITLE
Slutty Ryze LaneClear Broken

### ISSUE THREAD

**Issue by NoobPolice** [berbb/PortAIO#166]
LaneClear on Slutty Ryze Broken.
Lasthitting working fine.
Jungleclear Working fine.

I enabled the Option Laneclear with T, As well i have enough Mana but put the slider down to 10 % for Laneclear.
Nothin happend. he is just AA minions.

https://github.com/berbb/PortAIO/blob/master/Dual-Port/SluttyRyze/LaneOptions.cs

**Comment by berbb** [comment]
Fixed.
