### ISSUE TITLE
Vayne Settings

### ISSUE THREAD

**Issue by TheDudey** [berbb/PortAIO#167]
Hey Dudes
Can someone share good Setting for vayne.
Both ports...

**Comment by KiriharaSenpai** [comment]
for challenger series im using sharpshooter q logic and gosu e logic

**Comment by hardique** [comment]
VHR 
Condemn-Marksman/Gosu
Tumble-Reborn

**Comment by pellep12** [comment]
I could not get Condemn to work on default settings on VHR..

Are you saying it works if i change it to Marksman/Gosu ?

**Comment by hardique** [comment]
Yes,change it to Marksman/gosu and press F5

**Comment by 3ackdoor** [comment]
Q-Sharpshooter
E-Synx's Auto Carry (Max accuracy 12/12,Try to Q>E when possible)
No AA in stealth > 3 champs
