### ISSUE TITLE
Don't find some utilities

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#168]
Excuse me ik u r busy but i cant find some utilities who i see in ur github like ezevade or baseult 3

Could u explain me ? 

Thx for ur aio

**Comment by hardique** [comment]
eZevade could be found here  https://github.com/rexyrexy/PortedAddons

Baseult-don`t use dat :D

**Comment by IlikeBaconLol** [comment]
Ty <3
