### ISSUE TITLE
Nechrito Riven R2 Prediction

### ISSUE THREAD

**Issue by DannyTheGod** [berbb/PortAIO#169]
i played Riven against Maokai, doesnt use Burt Combo , it casted R2 near Maokai but didnt hit him , sorry for my bad English

**Comment by Lemonadez** [comment]
Maybe prediction gone wrong or Maokai have Evade on

**Comment by DannyTheGod** [comment]
he didnt use script , im sure about that

**Comment by berbb** [comment]
Tested earlier today and it hit most R2's, prediction isn't perfect lol, it's bound to miss a few. And to use Burst Combo make sure you have the enemy selected and after the burst goes off immediately switch to combo key.
