### ISSUE TITLE
Leblanc sometimes not using W ?

### ISSUE THREAD

**Issue by Muse30** [berbb/PortAIO#17]
I am testing lb and sometimes is not using W 

edit : ok  nvm it only happens in the first 2 levels.. but when I get all 3 skills levelup it works, I found this tho : http://prntscr.com/ay4y66

also flee doesnt work

**Comment by berbb** [comment]
Thanks, testing.

**Comment by berbb** [comment]
Fixed flee and not using W at early levels should be fixed. I also fixed 2Chainz :)
