### ISSUE TITLE
console report

### ISSUE THREAD

**Issue by KiriharaSenpai** [berbb/PortAIO#17]
firstly welcome back to your home berbb !! and got this console error on hi im gosu your new vayne port
https://gyazo.com/8c5f27dac1b3ed0d7a3a97733a525b1a
and sometimes e usage way too inaccurate

**Comment by berbb** [comment]
Oh, thanks for reporting this, the E is inaccurate because of that error, hopefully the update I just pushed fixes this problem.

**Comment by berbb** [comment]
Fixed.
