### ISSUE TITLE
SDK Prediction

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#172]
Is there anyway that you can make all scripts be able to use SDK prediction? something like SPredictioner from bansharp. SDK pred seems the most stable out of the preds in the AIO and would enhance it x100

**Comment by berbb** [comment]
There may be a way, I can possibly port SPredictioner and modify it to work with SDK. I'll see what I can do.

**Comment by dankmemer420** [comment]
Alright thanks man, appreciate your work <3

**Comment by berbb** [comment]
Done. Try it out :) (I only tested it on Yas)

**Comment by dankmemer420** [comment]
Alright will give it a go next game, thanks.

**Comment by dankmemer420** [comment]
Still seems iffy. ex: lee just firing q where they are not where they're gonna go.
