### ISSUE TITLE
Gnar

### ISSUE THREAD

**Issue by Swyven** [berbb/PortAIO#174]
![image](https://cloud.githubusercontent.com/assets/2068196/15731906/5f16b60a-282d-11e6-8a68-29835c9cf57d.png)
Not sure if related but I'm having issues with gnar not autoing units seemingly randomly, disabled gapclosers in core menu didn't help, disabling within the script itself didn't either, Allies : Gnar Lulu Yasuo Caitlyn Morgana, Enemies: Elise Lee Sin Master Yi Urgot Ezreal, cleared appdata and still had issues.

**Comment by berbb** [comment]
Alright updated Gnar. The console error is still going to be there but it should have no effect on the game and the not auto'ing should be fixed :)
