### ISSUE TITLE
Lee sin valvare combo = crash

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#175]
All in the title

Thx for ur aio

**Comment by KiriharaSenpai** [comment]
i tried like 7 mins not crashed for me works awesome can you please clear your appdata and updates ur requirement softwares for elobuddy

**Comment by IlikeBaconLol** [comment]
Hi first thanks for ur help ! Can i only delete the portaio data ? or all the eb one ?

**Comment by KiriharaSenpai** [comment]
i recommended to clear all of appdata but theres a way to do it without remove addons when ur eb opened in background clear ur appdata and click update addons

**Comment by IlikeBaconLol** [comment]
Ty a lot !

**Comment by rman200** [comment]
I played many games with it already, no crashes

**Comment by DannyTheGod** [comment]
same

**Comment by IlikeBaconLol** [comment]
About what danny the crashes or ?

**Comment by dankmemer420** [comment]
Yea i crash the first q2 every game, super annoying.

**Comment by DannyTheGod** [comment]
crashes

**Comment by IlikeBaconLol** [comment]
Clear apdata and should work

If u dont wantto lose ur addon clear apdata but as same time let open ur eb and after it udapte all addons, close eb and udapte all addons

It wroked for me tykirihara
