### ISSUE TITLE
Lee Sin Crash

### ISSUE THREAD

**Issue by berkerbey** [berbb/PortAIO#176]
Lee Sin causes crashes while combo mode. 
Enemy team shaco, rengar, zed, malphite, lucian

I dont know but , I think it's about Shaco.

**Comment by inphratiic** [comment]
If u using Valvrave lee sin it is know to crash and they are working on a fix atm ( it's taking sometime because they didn't figured out wich part of the code is causing the crash)

**Comment by berkerbey** [comment]
Yes i was, now using elleesin, it's good.

**Comment by berbb** [comment]
@inphratiic
