### ISSUE TITLE
Vayne Suggestion

### ISSUE THREAD

**Issue by 3ackdoor** [berbb/PortAIO#176]
please add rengar's jump in antigapcloser ;-;

**Comment by KiriharaSenpai** [comment]
am i wrong or it has it already

**Comment by 3ackdoor** [comment]
No, I am sure about it (no in VHR menu).
and please fix Mercurial Scimitar usage (no use against w TF) in ElUtilitySuite

**Comment by berbb** [comment]
Added it in the main Vayne script. But not VHR.
