### ISSUE TITLE
karthus

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#177]
Hi the OKTW karthus addon is bugged , i explain when u press spacebar it s like a click not a permanent following of ur mouse.

ty for ur aio

**Comment by KiriharaSenpai** [comment]
yea u re right it has some issue with orbwalker

**Comment by IlikeBaconLol** [comment]
Idk if i need to keep report buggs or its just annoying stuff for berb ?

**Comment by berbb** [comment]
Bugs are never an annoyance, I appreciate you taking the time to report this to me. And Thanks! I'll check it out.

**Comment by berbb** [comment]
Fixed.
