### ISSUE TITLE
Fizz freezing at 2 min mark

### ISSUE THREAD

**Issue by rman200** [berbb/PortAIO#178]
Whenever I play Fizz the game freezes at around the 2 min mark, after I FC the game and open it again its good to go and doesnt freeze anymore
dont have a clue why that happens :/

**Comment by KiriharaSenpai** [comment]
not crashing for me played like 20 mins not crashed at all clear ur appdata or update or c++ runtimes

**Comment by berbb** [comment]
Clearing your appdata should help this. But internally there's nothing in the code that should endorse this behavior.
