### ISSUE TITLE
Fiddle W channeling is canceled

### ISSUE THREAD

**Issue by ThugDogeNulled** [berbb/PortAIO#18]
When i press the combo key it just use the W but don't block movement or cast of other spells, so the channeling is canceled

**Comment by ThugDogeNulled** [comment]
Not just in combo, harass and lane/jungle clear is the same

**Comment by berbb** [comment]
Pushed a fix, try it out.

**Comment by ThugDogeNulled** [comment]
still canceling :pepe:

**Comment by ThugDogeNulled** [comment]
nevermind, isn't cancelling. thank you, i hadn't updated properly

**Comment by ThugDogeNulled** [comment]
actualy it is cancelling, i don't understand why, looks like the cast of E cancel the channeling

**Comment by berbb** [comment]
Dropped another update, test it again.

**Comment by ThugDogeNulled** [comment]
still canceling, i think it cancels to auto attack

**Comment by inphratiic** [comment]
Maybe orbwalker movement overriding the W check @berbb

**Comment by inphratiic** [comment]
@berbb    

public static bool IsWActive
        {
            get { return ObjectManager.Player.HasBuff("fiddlebuff"); }
        }

So i'm not into the EB API but this check doesn't look ok to me (don't know why, but it's a "feeling")

Maybe u could try messing with it a little.
Also is there anyway we can debug while playing? i could help with these kind of things if we can debug in-game

**Comment by berbb** [comment]
@inphratiic Yeah, it isn't right at all, after applying those fixes it should've stopped but the W buff name is wrong in there. But I couldn't fix the buff name then, because I didn't have fiddle, I asked someone to get it for me and it should be fixed now for sure. Updated!
