### ISSUE TITLE
Mordekaiser Crash?

### ISSUE THREAD

**Issue by pellep12** [berbb/PortAIO#181]
Was playing as Fiddlesticks and had a Mordekaiser in the enemy team, and the game crashed 5~times when he used his ultimate on a low hp target.

**Comment by berbb** [comment]
Will check it out this weekend.

**Comment by pellep12** [comment]
This "bug report" is somewhat shitty tho, since it did not crash everytime i used ult, but like i said; got around 5 crashes in that game and the only factor i could see where that the crashes always occured just as he ultied a low hp target.
