### ISSUE TITLE
Riven combo

### ISSUE THREAD

**Issue by cbozer** [berbb/PortAIO#182]
Recently I tested scripts for riven and any of them is not working fast q Combo. after pressing the spacebar riven runs around the opponent and waiting for cooldowns on E. Sometimes its working but slowly and after 2xq + aa its freezing.

**Comment by cbozer** [comment]
^im talking about nechrito riven, but others just are bad.

**Comment by berbb** [comment]
Adjust the Ping/Spell delay in the menu in a custom game and keep testing it.

**Comment by cbozer** [comment]
^u talking about humanizer?

**Comment by Muse30** [comment]
ping and spell delay in the misc menu of nechrito riven

**Comment by cbozer** [comment]
im set delay first to 20, then to 0 and still same problem.

**Comment by berbb** [comment]
@cbozer How about increasing it?...

**Comment by cbozer** [comment]
i will try increase it

**Comment by cbozer** [comment]
im decreasing and increasing and still same problem. ofc im clearing %appdata%

**Comment by inphratiic** [comment]
for me it works just fine , must be something on your side @cbozer , maybe u have a high ping ingame ( that fucks speed alot)
