### ISSUE TITLE
OKTW Anivia

### ISSUE THREAD

**Issue by iiChopper** [berbb/PortAIO#183]
Casts randomly spells like Q/R on the game without reason. Can you check that?

**Comment by berbb** [comment]
Will check it out this weekend.

**Comment by iiChopper** [comment]
Alright.

**Comment by berbb** [comment]
I couldn't really reproduce it BUT I added some checks to the code to further prevent this from happening.

**Comment by saladinaazir** [comment]
can confirm, am having same problem

**Comment by saladinaazir** [comment]
disabling anti gaplcoser Q,  farming and jungle R doesnt fix the problem
