### ISSUE TITLE
chatlogger doesnt load at all

### ISSUE THREAD

**Issue by KiriharaSenpai** [berbb/PortAIO#183]
as i said in title it doesnt load and console gives some purple error codes thx for hardworks

**Comment by berbb** [comment]
In the process of fixing it.

**Comment by berbb** [comment]
Fixed. Although the time is off, try not to F5 during the game and it'll be fine.

**Comment by myo** [comment]
blame jodus for not fixing game clock offset so finn can copy :^ (
