### ISSUE TITLE
Autosharp PortAIO port seems odd while in play

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#185]
Autosharp PortAIO port seems odd while in play. For ALOT of characters, it hardly moves.. often choosing to stand some distance away (not far far but behind ranged creeps-ish) and occasionally throw spells... Autosharp (VnN port) doesnt seem to display this behavior. The bot is much more flush with combat and active
I do not have defensive play on
I.E. Morgana and ziggs - Both have long, long range spells - however they are rarely cast (not even close to on CD) - not to farm, not to harass, nothing until it decides to toss them out in no discernable pattern

**Comment by berbb** [comment]
I don't seem to be getting it at all, it seems to work fine with me : http://image.prntscr.com/image/2cfbfa60ab9342c9a78fc0b52718fb9d.png

**Comment by myo** [comment]
i have this issue too if u fix hit me up so i can copy

**Comment by lgndz** [comment]
He closed already. 
No worries. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Fri, Jun 3, 2016 at 1:46 PM -0700, "Alex" <notifications@github.com> wrote:












i have this issue too if u fix hit me up so i can copy
