### ISSUE TITLE
Kalista E wrong calculated

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#186]
All Kalista version usually rend earlier than it should and let enemy alive, then E goes on cooldown.
For jungler monster too!
And it doesn't use E to KS Big Dragon / Dragon

**Comment by berbb** [comment]
KS with jungle is beyond fine, I've pushed updates the the E calc on all Kalista scripts but I'm not sure how effective they are. As for dragon, the original authors haven't updated the dragon debuff on the player.
