### ISSUE TITLE
Viktor W Interrupt Gapcloser Issue.

### ISSUE THREAD

**Issue by voidsurfer** [berbb/PortAIO#187]
Sometimes the W to Interrupt Gapcloser on Viktor causes the game to crash. Not sure why, might be an error with EB or an error with the addon itself.

Lurker7 posted it in the discord and i tried to re-enact the bug but with no avail, next game i play it crashed for me so i figured i might aswell post it here!

**Comment by berkerbey** [comment]
With Viktor, Pressing LaneClear button causes weird movements that I can't describe but I think it's about E.

**Comment by berbb** [comment]
Fixed both.
