### ISSUE TITLE
KogMaw's R

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#188]
Kog Maw just turns out not to be using his ultimate at all for me, even to finish killing a very low hp enemy ...
Same issue regardless of the PortAIO addon I use for him from his dual ported addon bundle.

**Comment by Lurker7** [comment]
Ok, it's not an issue related to ur PortAIO's code functionality since as far as I could see its L# versions appropriate to the both of ur ported ones were lacking the same feature (R usage on combo).
However, since they were tweaked recently to include it into their combo for more damage, can you update the at least one of the PortAIO Kog Maw addons to match its newer (and better) form and therefore start casting R during combo for more effectiveness :) ?

**Comment by berbb** [comment]
Challenger Series never changed it's R code. And the only Kog script in PortAIO that has R at the start of the combo is SharpShooter.
