### ISSUE TITLE
Cant install to elobuddy

### ISSUE THREAD

**Issue by xxbattonxx** [berbb/PortAIO#189]
hello im trying to install port aio on elo buddy client and wont allow me to it continually says failed when i hit install

**Comment by berbb** [comment]
Do you have Berb.Common installed?

**Comment by lightduy94** [comment]
1. Install .Net Framework 4.5 and MS Build Tool if you didn't have it installed. It can be found here: https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/
2. You have to installed Berb.Common before install PortAIO. It's here: https://github.com/berbb/EloBuddy/

**Comment by xxbattonxx** [comment]
ok ill give it a try thank you

**Comment by xxbattonxx** [comment]
installing the frame work helped thanks alot guys is there list some where of what champions ar in it?

**Comment by lightduy94** [comment]
All champions are support now. You can test and report bug so @berbb can fix it.

**Comment by xxbattonxx** [comment]
Sweet Ty

Sent from my iPhone

On May 11, 2016, at 10:12 AM, lightduy94 <notifications@github.com<mailto:notifications@github.com>> wrote:


All champions are support now. You can test and report bug so @berbb<https://github.com/berbb> can fix it.
