### ISSUE TITLE
Lucian (LCS) not using spells.

### ISSUE THREAD

**Issue by exorcistqq** [berbb/PortAIO#19]
Tryed in custom game it works. But when im ingame(ranked) it does not use any spell at any mode
Tryed harrass
Tryed combo
LCS Lucian.

**Comment by DannyTheGod** [comment]
Challenger Lucian  has the same problem
and 3 Lucian addons i have used ,,didnt use Extend Q in Harass

**Comment by dankmemer420** [comment]
All working fine for me, have you tried clearing appdata?

**Comment by Shazelol** [comment]
working for me, LCS lucian, and Challenger. Unistall EB and clear appdata.

**Comment by berbb** [comment]
Clearing appdata is the best way to go, if this error is still reoccurring for you, let us know.

**Comment by exorcistqq** [comment]
it happened again. cleared my appdata deleted eb. worked in first game. second game same thing happens. only ilucian works.
