### ISSUE TITLE
SluttyRyze

### ISSUE THREAD

**Issue by yorik100** [berbb/PortAIO#19]
SluttyRyze make crash when combo (only tested combo)

**Comment by berbb** [comment]
Thanks for the report, does it happen every time you press combo? Sometimes? Only one time? And could you list your utilities? Thanks! :+1:

**Comment by yorik100** [comment]
Switched to Exor Ryze after the crash, it crashed instantly in Q cast, then wait for the end of my leavebuster for the list of my utilities, I know I was using ezEvade, Tracker#, Activator#, SPred, L# OrbWalker, All Universall, DZAwareness, PastingSharp and I think some others, but I'm sure with these ones

**Comment by berbb** [comment]
Oh, I removed the L# Orbwalker, try updating it again.

**Comment by yorik100** [comment]
You removed it only for SluttyRyze?

**Comment by berbb** [comment]
I removed it from PortAIO.

**Comment by yorik100** [comment]
So it wasn't using it, because it didn't crashed after I swapped champion addon

**Comment by berbb** [comment]
Right now I'm looking towards Tracker# and Activator# for the crashes, I played with SluttyRyze recently and it didn't crash at all.

**Comment by yorik100** [comment]
:/ because it was only crashing at the first Q used in combo mode with this addon, nvm I'm gonna try after

**Comment by berbb** [comment]
Hopefully it was a one-time crash, I'll wait for the results :)

**Comment by orkenaga** [comment]
Hi yorik. do you remember me ? I am ObeliskTormentor :D

**Comment by yorik100** [comment]
Seems to no longer crash, hi Obelisk

**Comment by berbb** [comment]
Cool! I'll close this for now but if it happens feel free to drop another issue. :smile:
