### ISSUE TITLE
Logo for PortAIO?

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#19]
What do you think about this?

![paio](https://cloud.githubusercontent.com/assets/8278110/14907628/8380c750-0d80-11e6-9a2b-f417ed9d8f86.png)

**Comment by Muse30** [comment]
well im not berb but I like it  XD Kappa

**Comment by berbb** [comment]
Looks nice, I'll try to implement it as a message in the game like OKTW :)
