### ISSUE TITLE
Kalista suggestion and things to be fixed

### ISSUE THREAD

**Issue by 3ackdoor** [berbb/PortAIO#196]
please add this in  to-do in reborn version
- sentinel baron and dragon like ScaryKalista (hope ;-;)
- draw damage E on hpbar on enemies and minions (no works with current draw E dmg and it's easy to see when you fight)
- wall jump

to-fix
- rift scuttler and dragon on E dmg calculation (didn't test baron yet but other like red and blue works great)

**Comment by berbb** [comment]
Crab works well, dragon calculations haven't been fixed yet. The only thing I'll do from the list is sentinel baron & drag.
