### ISSUE TITLE
Problems with zed

### ISSUE THREAD

**Issue by DrHouse12** [berbb/PortAIO#196]
When game is started, script is normally loaded and i go for mid. When enemy is nearly im holding space and then i've got crash.

**Comment by Muse30** [comment]
Valvrave? Is a known issue...

**Comment by dankmemer420** [comment]
At this point you should just add to the readme that it crashes

**Comment by DrHouse12** [comment]
Ah okay, sorry i didnt know that

**Comment by DrHouse12** [comment]
I've getting random crash too with Cho Gath. When enemy has low hp and im holding spacebar i've got crash.

**Comment by inphratiic** [comment]
experienced the crash undertower when enemy is low HP too with sion and gnar so probably the problem isn't in the champion script
