### ISSUE TITLE
Aram bot crash

### ISSUE THREAD

**Issue by YourM0m** [berbb/PortAIO#197]
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at AutoSharp.Auto.HowlingAbyss.ARAMShopAI.Main.BuyItems(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()

**Comment by lgndz** [comment]
Were you using Tham Kench by chance

**Comment by berbb** [comment]
The buy items method has nothing to do with any crashes.
