### ISSUE TITLE
Clear spell queue on death

### ISSUE THREAD

**Issue by sparklinNeko** [berbb/PortAIO#197]
After respawning it randomly casts spells in fountain, which is rather bad in ARAM.

Also ilu berbb!

**Comment by lightduy94** [comment]
Which champion do you play?

**Comment by sparklinNeko** [comment]
I dont remember, just occasionally watch PortAIO play with our AutoSharp and it happens quite often with different champs.

**Comment by berbb** [comment]
I have no idea what that is.
