### ISSUE TITLE
The Cheater

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#198]
I saw this port in the TO DO list ,can t find him on the net 

Is that an utily

A champ addon ?

could u explain me dudes :') ?

Ty for ur aio

**Comment by fluut** [comment]
shows you potential script users in the game

**Comment by IlikeBaconLol** [comment]
What do u mean ?

**Comment by berbb** [comment]
The Cheater tell you who might be scripting in your game.
