### ISSUE TITLE
Jax - LindsNemesis 

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#2]
Jax continue with Randons E '-'(xQx)
ExorAio Jax stop using combo if all spells is enable

**Comment by LindsNemesis** [comment]
Sometimes ExorAIO make this issue berbb 
xQx issue is all time 
for time i using noob jax addon (i think is that the name) is working great!

**Comment by berbb** [comment]
Updated and Tested, Jax's E should only cast when target is in AA range.
