### ISSUE TITLE
Lee Sin Crash

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#2]
<b>Champion Name (eg. Ahri) / Utility (eg. Evade)</b> : Lee Sin

<b>If this is an issue about a champion, is this Champion dual-port supported (Check via PortAIO Misc)? If yes which one?</b> : ValvraveSharp Lee

<b>Issue/Problems (Try to be as detailed as possible)</b> : Lee Sin crashing non stop when trying to Q with combo mode. Tried an older version of Valvrave and I think the issue might be with the collision smite Q

Also I don't have an option to add a label, sorry.

**Comment by dankmemer420** [comment]
Seems to actually not crash after the first game.

**Comment by inphratiic** [comment]
It could be some champion characteristic causing that since it's not happen everygame, i don't have any acc with lee or i would help checking but perhaps u would help berb by telling him wich champs where in the games it crashed

**Comment by dankmemer420** [comment]
Pretty much every champion. Have no idea what could be causing it, it could be collision smite but I have no idea.

**Comment by berbb** [comment]
Here's what I did, I completely disabled Smite Collision, try testing it and see if it affects anything.

**Comment by dankmemer420** [comment]
Alright will test in a couple minutes.

**Comment by berbb** [comment]
If you, @dankmemer420, (or anyone) can confirm that this isn't happening for a second game, then we'll know for sure its Smite Collision.

**Comment by dankmemer420** [comment]
Yeah I haven't crashed all day.

**Comment by dankmemer420** [comment]
Ok now its crashing Zed in combo with valvrave.

**Comment by rpgfreak128** [comment]
valvrave also crashing on Lulu when i Q in or flash in on her

**Comment by berbb** [comment]
Alright, so now, I know 100% sure it's not much of the main Valvrave Champions causing the crash but the Valvrave Common itself. I'll find a fix.
