### ISSUE TITLE
None of the Ahris is working

### ISSUE THREAD

**Issue by shotsrox** [berbb/PortAIO#20]
Okay so i tried oktw ahri and ahrisharp, none of them are appearing on the menu and injecting, idk, it appears on the menu and stuff but just the utilities, even with champion only ticked.

**Comment by Muse30** [comment]
let me check

**Comment by Muse30** [comment]
are you still with this problem? is working fine here http://prntscr.com/b6823h

**Comment by berbb** [comment]
I fixed this error a while ago when Zed was running Ahri scripts just make sure you update and try again.
