### ISSUE TITLE
Orbwalker Target selector

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#201]
So with the new TS it works like EB one 5 equals higer priority or it works like L# one where 1 get's higher priority?

**Comment by inphratiic** [comment]
Also last hit method seems to work fine but laneclear method just won't give the last hit  to minions ( when it can be lasthitted he just change target to another minion and let the one who could be lasthitted die)

**Comment by berbb** [comment]
As for the TS it works like EB. And i'm trying to improve the LC/LH but I'm not sure how, first time messing around with an orbwalker haha.

**Comment by inphratiic** [comment]
sure, i'm just trying to give the most feedback possible so u don't have to lose time actually testing to see what works and what doesn't

**Comment by berbb** [comment]
It should be a lot better now.
