### ISSUE TITLE
Karthus prediction not working

### ISSUE THREAD

**Issue by ZangiefWins** [berbb/PortAIO#202]
Hello. No prediction from OKTW AIO is working for Karthus. It always casts Q where target is, not where target will be.

**Comment by berbb** [comment]
Instead of changing the prediction how about changing the hitchance? There's nothing I can really do cause I have no knowledge on prediction.

**Comment by ZangiefWins** [comment]
Sorry for being such a noob, but how to change the hitchance?

**Comment by inphratiic** [comment]
@ZangiefWins If u using SDKPredictioner click on it and there should be a line saying Hitchanche

**Comment by ZangiefWins** [comment]
The problem was solved by disabling SDK predictioner.
