### ISSUE TITLE
Orbwalker Autowalk Bug

### ISSUE THREAD

**Issue by NoobPolice** [berbb/PortAIO#205]
Sometimes when Pressing Space it Autowalks to a Random Lane block totaly the control of Mouse ( Shuttering ) and While Releaseing Spacebar it keeps going to a random lane.

Autosharpbot is disabled
i played Gosu Vayne Custom game

Deleted %appdata% 
but still persiting problem

**Comment by NoobPolice** [comment]
Another bug. While Recallign you cant abort the recall with Spacebar or another Orbwalker key.

**Comment by dankmemer420** [comment]
The second one is a EB feature i think to stop you from accidentally cancelling recall

**Comment by berbb** [comment]
There's nothing in the code that should force you to a lane other than an autoplay. If you try another vayne will it still happen?

**Comment by NoobPolice** [comment]
> There's nothing in the code that should force you to a lane other than an autoplay. If you try another vayne will it still happen?

Its only related to Gosu Vayne. Challanger and Hiki are fine.

> The second one is a EB feature i think to stop you from accidentally cancelling recall

any way to Disable it ?

**Comment by berbb** [comment]
@NoobPolice Alright that narrows it down, I'll check it out.

**Comment by berbb** [comment]
Alright pushed a fix, please update.
