### ISSUE TITLE
Orbwalker Stutter

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#206]
Idk how to stop it, but the new orbwalker is making me stutter like crazy probably 20 aa resets a sec.

**Comment by berbb** [comment]
Adjust the windup time.

**Comment by dankmemer420** [comment]
Put it at max and its still doing it.

**Comment by berbb** [comment]
Who are you playing?

**Comment by dankmemer420** [comment]
Lucian, also vayne q seems clunky reset

**Comment by berbb** [comment]
Discontinued the orbwalker.
