### ISSUE TITLE
Still can t find some utilities

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#207]
http://i.imgur.com/ETjVWCF.png

I cant see the Sprediction or the baseult, are they from portaio if yes how could i had them ?

**Comment by IlikeBaconLol** [comment]
PS : I love ur aio

**Comment by Acheiro** [comment]
Em don't you see them in the menu?

**Comment by IlikeBaconLol** [comment]
Nah on portaio misc i only see :

Humaniser god jugnle tracker pig blocker elutility and some other one
But any ezevade or baseult or s pred or anything else

**Comment by wwomegaww** [comment]
Same

**Comment by lightduy94** [comment]
Sprediction are already there but it only load for some addons eg: OKTW addons if you enabled Sprediction instead of other Pred.
Baseult is diabled for now! You still can use other EB's Baseult for it

**Comment by IlikeBaconLol** [comment]
Ty
