### ISSUE TITLE
Random Crashes.

### ISSUE THREAD

**Issue by vperpl** [berbb/PortAIO#209]
No idea what / when it hapens.
#1 game I was miss fortune + blitz vs vayne & braum
Crashed 4 times - mostly when i holded space and was casting Q.

#2 game i was vayne (i thought it was her crashing my games) - when akali used W crashed twice.

#3 game -> bots alistar used heal i crashed.

I am using ONLY your aio.
if u have any debugging` shit i can download it & gib u logs.

**Comment by DannyTheGod** [comment]
what script? tell us

**Comment by DrHouse12** [comment]
Maybe script Stealth Revealer doing crashes in #2 game ? For me this script spamming errors in console.

**Comment by berbb** [comment]
Were you using ElUtility?

**Comment by berbb** [comment]
Completely removed Anti-Stealth, hopefully it fixed something.

**Comment by haxorwannabe** [comment]
yes elutility is causin crachs i still dunno witch script but it only crash when u use spacebar near an enemy

**Comment by KiriharaSenpai** [comment]
anti stealth was a so useful feaure and it doesnt crash for me berbb can you make it load with a option like dual port thx so much for portaio

**Comment by lgndz** [comment]
I am victim of the huge crashing problems - I will report back. Heres what Im running;

nabb + ezevade + detARAM + autoFF + Humanizer + SPredictioner + autoplay + autolevel 

Id like to note that running Autosharp RARELY resulted in crashes and could be ran for 8+ hours at a time, detARAM however causes the MOST crashes for me - hoping it was elutility

**Comment by rpgfreak128** [comment]
I am only using the detARAM and it crashes after 15 minutes or so early game is fine

**Comment by lgndz** [comment]
Same. I'm still experiencing crashing with new nabb activator AND elUtility. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Tue, Jun 7, 2016 at 1:01 PM -0400, "rpgfreak128" <notifications@github.com> wrote:












I am only using the detARAM and it crashes after 15 minutes or so early game is fine

**Comment by rpgfreak128** [comment]
Ya and it sucks because DETARAM is so much better than Autosharp =( but its Def a problem with detARAM i even disabled champs from portmics and put utility only and still crashes

**Comment by lgndz** [comment]
100% with detARAM. I've been leaver busted nonstop with detARAM. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Tue, Jun 7, 2016 at 1:08 PM -0400, "rpgfreak128" <notifications@github.com> wrote:












Ya and it sucks because DETARAM is so much better than Autosharp =( but its Def a problem with detARAM i even disabled champs from portmics and put utility only and still crashes

**Comment by berbb** [comment]
Figured it out, AramDetuk should be fixed.
