### ISSUE TITLE
General issues+Khazix

### ISSUE THREAD

**Issue by nightsole** [berbb/PortAIO#210]
**Played Kha 3 times** 
1.seph kha tends to crash in about 25-30 mins it freezes the game completely.
2.Seph khazix randomly jumps around the map in 25-30 mnutes.

**General issues**
1.when pressing space orbwalker keeps going back and forth, yes i deleted %appdata%, it happened only today i played olaf and khazix.

thanks for port AIO , keep up the good work this is one of the best projects out there.

**Comment by berbb** [comment]
Were you using ElUtility?

**Comment by nightsole** [comment]
yes i was, the gank alert , ward and that's it

**Comment by hardique** [comment]
@berbb does ElUtility can be a source of dat bugs?cuz also noticed some fps drop from ElUtil.and still use it,cuz there are a lot of useful functions in it.

**Comment by Shazelol** [comment]
For me ElUtility don't crashes, I only use activator, cleanse, ignite, zhonya, Ultimate leveler. works well 0 crash.

**Comment by nightsole** [comment]
I deleted appdata again and reintalled portaio and the common, now there is a new problem , evade works even when im not selecting it from Elutility.

**Comment by berbb** [comment]
@nightsole It's probably double jump, try turning that off.

**Comment by nightsole** [comment]
Turns out it was, thanks budd
