### ISSUE TITLE
Crashes at ARAMDetFull

### ISSUE THREAD

**Issue by kirabc** [berbb/PortAIO#211]
Problem 1
this script is crashes alot with me, some prints.
http://i.imgur.com/LcqykG7.png
I am using ONLY ARAMDetFull and berb common nothing more
>> i watch some games and see its crashe when my champion go to catch healing on map.

Problem 2 
with kuriso nidale she dont use pounce sometime (this breaking the game)  i'm 'turn off' all pounce logic and sometime she dont use...(you can fix this add a option use "W always"

srry bad english.
Ty for this aio its amazing :)

**Comment by berbb** [comment]
Fixed Nidalee.

**Comment by kirabc** [comment]
Don't load nidale
--->when ultily is activated Portaio dont load nidale scripts
--->only load when i put "champ Only Mode"
PS: Pounce now work great :) ty.

**Comment by berbb** [comment]
@kirabc Uncheck both Utility only and Champs only it will work lol.

**Comment by kirabc** [comment]
i try this..but wont work..only if put only champion mode.
