### ISSUE TITLE
Vayne Q

### ISSUE THREAD

**Issue by ichigodelmito** [berbb/PortAIO#215]
Q still buggy, no attack resets(on all modes) and cursor mode no works

inb4 english

**Comment by berbb** [comment]
Jesus christ, please, please, it would make my life 90% easier IF you told me which Vayne script you're using.....

**Comment by shotsrox** [comment]
is it possible to chose what champion script u wanna use?

**Comment by ichigodelmito** [comment]
Sorry, is challenger series. solo vayne i think

**Comment by berbb** [comment]
Fixed.
