### ISSUE TITLE
ARAMDetFull 

### ISSUE THREAD

**Issue by Joeyzera** [berbb/PortAIO#216]
crash all time
testing: lucian, tk, garen.. crash. :(

**Comment by kirabc** [comment]
i have same problem but he know that, he probably go to fixes it soon.

u can use autosharp (but i get leaveboost all the time with this, because the logic seens broken,,,but works,) better then nothing =p

**Comment by berbb** [comment]
Currently happening to some on the original assembly also, wait for an update.

**Comment by Joeyzera** [comment]
thanks berbb <3
