### ISSUE TITLE
Yasuo and Leblanc.

### ISSUE THREAD

**Issue by Meroto3** [berbb/PortAIO#217]
So, I discovered PortAIO recently, and i'm in love with it already! Thank you so much for that.

I'm here to report issues to help the improvement of PortAIO.

1- I don't know if I'm doing it right, but Popblanc is so bad for me. The combo logic is bad and it does not have an option to Q R(Q) combo!

2- Let's talk about Yasuo now. There are two ported addons (should I call it assemblies?): Valvravesharp and YasuoPro.
Valvravesharp - E logic is so bad. It frequently misses Q3+E and does not use E properly in waveclear.
YasuoPro - It's almost perfect, there is only one problem: W does not work. I'm not sure if the problem here is my configs, but it simply does not cast W.

So, yeah, thats my feedback! Loving all the other PortAIO addons. Keep up the good work and thanks again! :+1:

**Comment by berbb** [comment]
Q>R(Q) combo is the main "combo" key, I'll check out the W for Yas.

**Comment by berbb** [comment]
For LB, I'm dualing it. And I fixed the YasuoPro issue.

**Comment by Meroto3** [comment]
Ok, Yasuo's W is working now. But its casting it EVERY SINGLE TIME, even if i'm not in the skill range. I mean, even if i'm at base, and the enemy casts a skill in my direction, it uses W. And, its casting to mouse position, not against the enemy skill.

**Comment by berbb** [comment]
Will check it out ^

**Comment by berbb** [comment]
http://i.imgur.com/hmsIFjJ.gif - Wasn't able to reproduce it. Try clearing appdata.
