### ISSUE TITLE
SDK vs SDKEx.

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#218]
Just wondering if there's actually a huge difference between the L# sdk and sdkex? i heard the pred is 100x better than the normal SDK and overall performance.

**Comment by berbb** [comment]
There is, but there won't be much difference on the ported version because we don't use it as a core as L# does.

**Comment by inphratiic** [comment]
@berbb have you thought about making portaio have it's own core? i know some EB addons that  have their own core

**Comment by berbb** [comment]
@inphratiic Nope, technically Berb.Common is the Core but I don't use it like one. The EB addons that you're talking about, their core is nothing more than some extensions for easy accessibility.

**Comment by inphratiic** [comment]
@berbb would there be any perfomance improvements if u tried to use b.common as a core?

**Comment by berbb** [comment]
Maybe but Berb.Common was not setup as a core so if I wanted to make it a core I would probably have to port it again.

**Comment by inphratiic** [comment]
@berbb hum, i see

**Comment by dankmemer420** [comment]
@berbb is there anyway you could try it out or nah

**Comment by berbb** [comment]
We already have SDKEx.
