### ISSUE TITLE
Simple Suggestion: Make a toggle in Portaio misc that disables all drawings

### ISSUE THREAD

**Issue by ryroy** [berbb/PortAIO#218]
pretty simple thing to do in my opinion, but it's a huge bother to go through every champion and disable the drawings manually*

**Comment by berbb** [comment]
Easy to do but extremely time consuming. Something called "Hacks.DisableDrawings = true;" exists in the code and will indeed disable all drawings but it also disables shift-menu so I can't do that. The only possible solution left is to go through the 130+ addons and code it in and I'm not really up for that.
