### ISSUE TITLE
Activator request

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#219]
So i know that activator# and nabbActivator are on the to-do list, what i would like to ask is if you could port 1 of those before finishing porting all those champion addons

**Comment by Lemonadez** [comment]
elulity has activator on its own. maybe u are not looking at settings?

**Comment by inphratiic** [comment]
i know but i don't use elutility because it causes me some crashes, that's why i'm asking

**Comment by Muse30** [comment]
ported nabb activator for now

**Comment by inphratiic** [comment]
@Muse30 thank you
