### ISSUE TITLE
Katarina issues

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#22]
it won't jump on minions or teamate on flee mode , can you make it happen ? and i hope priority should be [[ minions/teamate > ward ]], thanks

**Comment by berbb** [comment]
Will check it out today, thanks.

**Comment by berbb** [comment]
Alright, I've made the radius bigger from the mouse to the minion/teammate so its easier to jump to them. Just make sure you have your mouse over or close to the minion/teammate during flee.
