### ISSUE TITLE
GosuMechanics Yasuo Error feedback

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#22]
1.When I press the C key it does not use E
2.When I press the key combination that he sometimes does not use E，I've tried setting E range but still happen. not  E minions Gapcloser Enemy。
Sorry my English is really too bad

**Comment by berbb** [comment]
Thanks! Will check these out.

**Comment by lyn690697457** [comment]
I tried it again found to be the key problem, however, when combined, he still will not use E minions Gapcloser。

**Comment by PortAIOMuse** [comment]
I tried to fix and it uses E to minions but super delayed and only to mouse position so lets wait for berb

**Comment by Muse30** [comment]
alright temporary fix for the E while I look at other options XD

**Comment by lyn690697457** [comment]
I will go to test and feedback

**Comment by lyn690697457** [comment]
OK E no problem tanks。
