### ISSUE TITLE
Evade and Ezevade problem

### ISSUE THREAD

**Issue by orkenaga** [berbb/PortAIO#220]
Evade and Ezevade not good dodge on combo mode, can you fix the problem ?

**Comment by Lemonadez** [comment]
LoL. When you press Combo mode, it only dodge "Dangerous Spell". that why it wont make your character obvious scripting while doing combo mode and dodging every spell while chasing down your opponent.

Look at Evade settings. If not understand settings, dont use evade.

**Comment by IlikeBaconLol** [comment]
#get rekt
