### ISSUE TITLE
Regardind the Fullscreen mode

### ISSUE THREAD

**Issue by shotsrox** [berbb/PortAIO#220]
I know this is not a issue at all but do you plan on making this work 100% on fullscreen mode? Cuz some ppl have lower fps playing borderless mode.

**Comment by terry3041** [comment]
The fullscreen problem is from EB. Not from PortAIO actually

**Comment by shotsrox** [comment]
Idk man, i play on fullscreen without any problems with other scripts, and on L# there's the same problem as on BOL too with some scripts

**Comment by lgndz** [comment]
Its a known compatibility issue with the framework itself, both here at EB as well as L# and BoL. There is nothing the script writer can do. Sometimes it works, sometimes it doesn't. I play Fullscreen with no issue, for example, while you have an issue.

Please close this issue - as this is not a PORTAIO issue
Thanks

**Comment by Muse30** [comment]
bassically it only happens when you alt+tab

**Comment by berbb** [comment]
There's too much code to go through to see what's not making Full Screen work and there's no way to debug it. It's a huge inconvenience, and I'm sorry, but there's no other way to use it without crashing so much.
