### ISSUE TITLE
Issues on Fizz

### ISSUE THREAD

**Issue by Nightmare221** [berbb/PortAIO#221]
your ported fizz script is so good! there is only one little problem that is annoying me
whenever you press Q, it casts E instead of Q, and i cant find the option to disable that
fix pls! ty

**Comment by Muse30** [comment]
pls check the menu before posting lol .. is right there : https://github.com/berbb/PortAIO/blob/master/Champion/Fizz/Program.cs#L886

so change the keybind of flee

**Comment by berbb** [comment]
@Muse30  <<
