### ISSUE TITLE
PrideStalker Rengar

### ISSUE THREAD

**Issue by cbozer** [berbb/PortAIO#222]
In this script are terrible fps drops. I think that this is the best script for Rengo but these FPS ehhhhh. Can u fix this please? :)

**Comment by berbb** [comment]
Just went into a custom game and tested this. The main factor that is effecting this rengar script is the drawings, the text, the mode, the damage indicator are all effecting FPS. The main one effecting FPS is the Damage Indicator, once disabled I gained about 15 FPS back.
