### ISSUE TITLE
YasuoPro still not working for me

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#222]
It's loaded but not working. Windwall and Flee mode still work but Combo, Laneclear, Harass didn't work.
Valvre working fine for me except E usage in laneclear and wasted Knockup on minion EQ combo

**Comment by berbb** [comment]
Clear you appdata and try again.

**Comment by lightduy94** [comment]
Yes. I already tried to clear appdata 2 times but no hope.
Please take a look!

**Comment by lightduy94** [comment]
P/s: Why i can't find option to use Flash / Zhonyas in EzEvade?

**Comment by berbb** [comment]
@lightduy94 It's working 100% for me. I would know because I fixed windwall earlier today. EzEvade? It's not even enabled.

**Comment by lightduy94** [comment]
@berbb EzEvade is already enabled bro Fappa
YasuoPro windwall casting randomly, Q and E not working except for KS

**Comment by berbb** [comment]
Any console logs?

**Comment by lightduy94** [comment]
How can i give you console log? I don't know how to get it!

**Comment by berbb** [comment]
http://i.imgur.com/hus4U4W.png

**Comment by lightduy94** [comment]
I just reinstalled all my Net Framework and it's working now. But YasuoPro have strange E usage in combo. It almosts time just use E on champion, not minion for gap closer. And sometimes it use E on minions backward and let enemy run.
I have evade diabled, tried use waypath on E on / off but still the same.
btw, i love "Combo E to mouse" feature from Valvre, could you add it to YasuoPro too?

**Comment by berbb** [comment]
Valrave and Yasuo Pro are 2 very different scripts, adding it will be a huge pain. One is using SDK and the other is using Common.

**Comment by lightduy94** [comment]
OK. So i have to wait when ValvreSharp fully working :)
Thank you @berbberino <3
