### ISSUE TITLE
Crash nasus 

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#223]
Nasus crash when he fights vayne or yas no error on console.

Ty for PORTaio

**Comment by berbb** [comment]
Ported another Nasus, shouldn't have any problems.

**Comment by inphratiic** [comment]
@berbb this crash still happening ( couldn't figure out  the reason it seems like random), no error in console also

**Comment by berbb** [comment]
There's nothing when using combo that should endorse a crash. All it does is cast W when in range, cast Q, cast E if hitchance is high, cast R if less than HP in menu and ignite when killable.

**Comment by inphratiic** [comment]
idk maybe it was some utility, i'll   play a game with champ only mode and see if it still happens
