### ISSUE TITLE
Ezreal OKTW Q usage errors 

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#224]
As title suggests.

Q is not used in combo at all
----- Q is used when in modes "X" "C" "V" 
---------- When Q IS used, it is only used on minions (this means no harass on champs at all in lane phase.)

Pred used was SPred (if it matters) - all other options (concerning Q) were default

Playing with latest:
ezevade
berb.common
PortAIO

**Comment by lightduy94** [comment]
If you use Spred, you have to diabled check AA windup time to make it work.
But on Ezreal, i recommend you to use SDK Pred. Not really good but it is the best pred for this Ez now!

**Comment by berbb** [comment]
If it's not a prediction related message then clear your appdata. If it is, play around with the prediction and see which one you like.
