### ISSUE TITLE
Still get failed when installing PortAIO

### ISSUE THREAD

**Issue by eternalch40x** [berbb/PortAIO#225]
I m sure i have install Microsoft Build Tool 14.0 but i still get failed when installing PortAIO.
[http://pastebin.com/raw/SzqjEJNa](url)   This link is the log file.

**Comment by Muse30** [comment]
nothing berb can do to be honest :disappointed:

**Comment by Jokiblack** [comment]
https://github.com/berbb/EloBuddy

**Comment by eternalch40x** [comment]
Yes,i have install berb.common

**Comment by eternalch40x** [comment]
I try to reinstall my os.I close the issue now.
