### ISSUE TITLE
Evade even when evade is off

### ISSUE THREAD

**Issue by haxorwannabe** [berbb/PortAIO#226]
there is some random evade on baron attacks and ziggs spells atleast dunno if it happens with another champions.

**Comment by HDown-idk** [comment]
Same problem. EzEvade miss priority. 
Flash away from Lux E for example.
Evade from Lucian E DangerLvl 2 - also use E for lower dangerlvl

**Comment by berbb** [comment]
Which Evade?

**Comment by HDown-idk** [comment]
EzEvade

**Comment by berbb** [comment]
Alright, fixed the dodging when Evade is turned off.

**Comment by nightsole** [comment]
it's not fixed , plz recheck i just played still evades

**Comment by berbb** [comment]
@nightsole Are you using ezEvade?

**Comment by nightsole** [comment]
thanks for the hard work buddy , i kind of feel bad issues those issues bc you do so much , anyways will test it shortly and get back to you

**Comment by HDown-idk** [comment]
How about evade with spells? Flash away from Lux E so curious))

**Comment by nightsole** [comment]
@HDown-idk i dont know what you mean.

@berbb it's fixed now , thanks, you can close the issue.

**Comment by lightduy94** [comment]
@nightsole HDown-idk mean that EzEvade still use Evade spell for lower setted spell danger level.
Eg: I'm set use Flash for Danger level: 5. And Danger level of Lux E is 3. EzEvade still use Flash for Lux E!
P/s: It's is a popular bug on any EzEvade ported on EB. It always use spell to dodge spell no matter what danger level it is if you choose "Activation time" mode!

**Comment by nightsole** [comment]
@lightduy94 I play portAIO without evade , the bug was that it uses it while it's disabled , which is now fixed , you guys probably have a problem with evade while it's enabled so for that open another issue and in it specify your problem, for this issue the problem is resolved.

**Comment by HDown-idk** [comment]
How about "Undodgeable?
