### ISSUE TITLE
Twitch E

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#227]
So seems that the damage calculation on twitch E (OKTW and Nechrito) not working properly, it uses E way too late ( like i can even cast E before the script and be 100% sure it will get the kill).
 On itwitch it didn't even use E at all

**Comment by berbb** [comment]
The E KS Damage in LS's common doesn't calculate poison ticks and since all three twitch scripts use L# common's damage library they all calculate E the same.

http://image.prntscr.com/image/82fbe4c520ba4456b6e3bcd8041151ca.png

**Comment by inphratiic** [comment]
@berbb so basicly it only's recognizes the damage from 1 poison stack?

**Comment by berbb** [comment]
Yeah, it doesn't get the ticks over time (damage over time), and it counts every stack but only pure damage. I'll check the damage calc and try to correct it.
