### ISSUE TITLE
Suggest Port

### ISSUE THREAD

**Issue by Demisemo** [berbb/PortAIO#227]
Hoola Riven The author has been updated to 6.8

Use very smoothly QA soon ,

Nechrito Riven How not to use diet plus QA is not fast enough

Burst Unlike previous press would react immediately

**Comment by berbb** [comment]
I'm not porting Hoola Riven because it's literally like the exact same as Nechrito. Is your ping high? Maybe that's why it's so slow? You can edit the delay's in the menu to adjust speed.
