### ISSUE TITLE
ARAMDetFull

### ISSUE THREAD

**Issue by rpgfreak128** [berbb/PortAIO#228]
Okay some feedback so i think ARAMDetFull is even crashing on the original creator but not sure, i tested this:

ARAMDetFull only 

disabled everything thing else even the champ from portmisc and after 15 minutes or so it crashed early game works fine so hope this helps running windows 10 64bit in borderlessmode and app data recently cleared

**Comment by kirabc** [comment]
I tested the original today 5 matchs and no crashe, probably should have received update. Same with me, crash arround 10 - 20 min (i win a L account with some days '-' end today. :( ).

i test on win 7 64bit.

**Comment by berbb** [comment]
Figured it out, should be fixed.
