### ISSUE TITLE
Ikalista reborn E does not work , error code

### ISSUE THREAD

**Issue by SidaRevamped** [berbb/PortAIO#229]
![image](https://cloud.githubusercontent.com/assets/19193456/15876129/7c7e8262-2cd9-11e6-9c85-ae2cbeb06459.png)

**Comment by KiriharaSenpai** [comment]
just tested it works for me but it calculates es damage wrong like it uses it before enemy die

**Comment by berbb** [comment]
It's working fine, I'm not sure how you're getting that error code unless PortAIO was loaded incorrectly.
