### ISSUE TITLE
Suggestion Debug

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#23]
Is there anyway we can debug while in-game? if it's possible i think would be really helpfull if u tought us how to do it since it would help us report/find the bug's with more precision, and would allow us to maybe come with a fix even before reporting them to you

**Comment by PortAIOMuse** [comment]
http://img5.fotos-hochladen.net/uploads/guide18uwpvsyhxt.png

**Comment by inphratiic** [comment]
Thank you. Never explored that part of the loader. Is it possible to add breakpoints to the code via the console?

**Comment by berbb** [comment]
@inphratiic Unfortunately not, so its harder, but we manage with console logs.
