### ISSUE TITLE
Fioraworld,,, 

### ISSUE THREAD

**Issue by papoa** [berbb/PortAIO#230]
not sure what causes Fiora champ script crash... all i remember was onloadchamp failed something and the value of T,,,,,,(sorry for the lack of the info with the error, didnt made a photo and happened to me twice dont know why,,, i think because a champion pressence in the game)(this were the champs in the game, alistar, jax, irelia, malzahar and jinx,,, my team fiora, sona, cait, oriana and heca

tried a personalized game no probs gonna try ranked again and hope no errors,,
Thanks for this great addon btw ! keep up the good work

**Comment by Muse30** [comment]
fiora addon used?

**Comment by papoa** [comment]
Seems  FioraWorld,, dont know the only addon available with fiora on the portaio

**Comment by dankmemer420** [comment]
I think alot of the crashes are caused by drawings, i turned off all the drawings for valvrave and havent crashed once.

**Comment by papoa** [comment]
yea I play almost with no drawings,, so I dont think is drawings fault ,,, however next time it appears ill try ;)

**Comment by papoa** [comment]
to add more info i have to say I disabled every util and left only the fiora addon alone to see if the utilities were making the error but no the error persisted,

**Comment by berbb** [comment]
The error is fixed.

**Comment by papoa** [comment]
Thanks berbb what was causing the error? 

and thanks for the incredible addon :)
