### ISSUE TITLE
lee crash

### ISSUE THREAD

**Issue by Hidan123** [berbb/PortAIO#231]
lee crash after combo or ward jump

**Comment by berbb** [comment]
Doesn't seem to be happening to me at all. Can someone else confirm this? Maybe with console logs?

**Comment by dankmemer420** [comment]
On my phone right now, but yes valralve lee is crashing the first time i press the combo key with enemies around.

**Comment by berbb** [comment]
I pushed an update for Valvrave's 6.9 update. The results probably have changed...

**Comment by dankmemer420** [comment]
Alright i'll give it a test when im home, cheers for the update man <3

**Comment by dankmemer420** [comment]
@berbb Seems to be fine now regarding crashes, Q2 Seems to have a little delay when Q1 hits, and the smite collision for insec is godly, but doesn't really do it for combo mode just some reports. Thanks again mate

**Comment by Hidan123** [comment]
Still crashing after update second time in ranked :D

**Comment by pellep12** [comment]
The game "crashed" (or rather froze) for me aswell when i was playing Lee, first crash was when i was going to gank and was using combo key.

**Comment by berbb** [comment]
And you're all playing with smite?

**Comment by dankmemer420** [comment]
Yes

**Comment by Hidan123** [comment]
Yes berberino ^^

**Comment by HeheheM** [comment]
yes

**Comment by pellep12** [comment]
Yes, i had smite, was level 3 and had unfinished jungle item so it was just the normal smite.

**Comment by berbb** [comment]
@pellep12 I'm not really up for fixing it, I was thinking the same thing, and I'm just about ready to remove it.

**Comment by berbb** [comment]
I'm not sure why but this can't be reproduced in a custom game, if I have some free time I'll test it in a normal.

**Comment by Hidan123** [comment]
Okay thanks  @berbb  :dancer:

**Comment by dankmemer420** [comment]
Crashed 5 times this game.
