### ISSUE TITLE
hi_i_am_gosu

### ISSUE THREAD

**Issue by hardique** [berbb/PortAIO#231]
Sometimes vayne is stuttering in combo mode.Only i am gosu,other working fine.Also in harass mode sometimes.

APPdata cleared.

**Comment by inphratiic** [comment]
Do u have emotespammer enabled? i experienced that problem with others champions and the cause was emote spammer

**Comment by hardique** [comment]
Nope ,only gosu ,nabbtracker,evade ic

**Comment by inphratiic** [comment]
evadeIC could be causing the stuttering if some skillshots where incoming

**Comment by berbb** [comment]
Stuttering should not be happening because nothing interferes with the Orbwalkers auto attack. The only that that could is if you have the "Auto -> Q -> AA" keybind active.

**Comment by hardique** [comment]
the reason is target selection.it auto changes target,and wanna run to another lane to attack enemy,when u r near enemies on bot for example.
only hi i am gosu ,other assemblies don`t have such issues.
