### ISSUE TITLE
EzEvade

### ISSUE THREAD

**Issue by DannyTheGod** [berbb/PortAIO#232]
it doesn't dodge and draw karthus Q and Zyra Q

**Comment by DannyTheGod** [comment]
LeeSin Q too

**Comment by Requital** [comment]
Also it doesnt have Flash in Evade Spells

**Comment by berbb** [comment]
Evade is something that is way out of my knowledge range, I'm not even sure how it works, its just ported. If, I can't manage to fix these then EzEvade will be dropped.

**Comment by berbb** [comment]
Lee Sin dodge is working fine... 

Had my friend test it with me : http://i.imgur.com/vogrJpH.gif
