### ISSUE TITLE
Hoola Riven

### ISSUE THREAD

**Issue by firedfox05** [berbb/PortAIO#233]
can you please make Hoola Riven

**Comment by Muse30** [comment]
Hoola riven is literally the same as NechritoRiven so no point on doing that

**Comment by firedfox05** [comment]
Hoola riven burst is way much faster than nechrito riven

**Comment by Muse30** [comment]
actually you are right but everything else is the same xD

**Comment by firedfox05** [comment]
can you port that sir?

**Comment by Muse30** [comment]
lets see if berb wants to port hoola burst to Nechrito if not I can do it

**Comment by firedfox05** [comment]
thank you so much sir, looking forward to it :+1:

**Comment by berbb** [comment]
Fine. Added to to-do.
