### ISSUE TITLE
Cho Gath, really bad prediction

### ISSUE THREAD

**Issue by DrHouse12** [berbb/PortAIO#233]
Hey, i just wanna say that script for Cho Gath is good but prediction really sucks.. Almost every Q is missed :c

**Comment by berbb** [comment]
Made some changes and I'm currently testing them right now. If it works well I'll push it.

**Comment by berbb** [comment]
Finished testing and it hit decently well against bots on the highest setting in the menu. Hopefully it works just as well with the new update I just pushed.
