### ISSUE TITLE
Dual Port

### ISSUE THREAD

**Issue by SamisDaShine** [berbb/PortAIO#235]
How i inject dual port ?

**Comment by Requital** [comment]
You dont It automatically injects when you play a champion that has a Dual-Port

**Comment by ichigodelmito** [comment]
Select dual port scripts on menu

**Comment by berbb** [comment]
PortAIO Misc Menu > If the champion is supported there will be a dropbox option to choose which script you want.

**Comment by SamisDaShine** [comment]
Thanks Berb!
