### ISSUE TITLE
Tristana suggest / feature request.

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#236]
Could you add this feature to combo mode? I think this is the best logic for Tristana E usage.
1. Semi-cast E key that cast E to the best priority target in E range. (Default E key)
2. Only Q when E.
Because as an advanced Tristana player in Diamonds, i prefer and always use E by myself so i disabled auto E in combo. Only human can know exact time and target to go all in.
So if i want to all in, i simply will press E (Semi-cast E) key and this addons will cast E and Q for me. If i'm just want to AA to poke, not all in, i still can hold the combo key and this addons will just AA and kiting enemies and when the time to finish come, i simply press E while holding Combo key :)

**Comment by berbb** [comment]
Updated.
