### ISSUE TITLE
detARAM

### ISSUE THREAD

**Issue by rpgfreak128** [berbb/PortAIO#237]
detARAM still crashing saldy again tested it after you updated it cleared app data and only using detARAM i disabled everything else even champion addons from portmics

this is me only trying help the port get better =D no rush just giving feedback

**Comment by lgndz** [comment]
Is it still crashing after 15ish minutes?

**Comment by kirabc** [comment]
still crash with me to 

and same with me..only trying help the port get better '-' 

in my test few times starting crash with 8 min

PS: i will watch a full game and give max info i can take

**Comment by berbb** [comment]
I'll give it one last go, if it doesn't work out I'm removing it, not worth fixing.

**Comment by kirabc** [comment]
@berbb, I think it is easier to fix the logic of AutoSharp than fix detARAM

you can copy sharp logic from this https://github.com/voidsurfer/hotmilkshakes using your aio champions plugin ''-''

**Comment by berbb** [comment]
There's really nothing to fix, the code is nearly the same there's no reason why one should work better than the other when it's basically the same port.

**Comment by kirabc** [comment]
i dont know why but your autosharp stop in midle of map like 3-4 min (your play to safe ) and every game get leave boost for this, i think the Logic is not the same.

**Comment by berbb** [comment]
Removed,
