### ISSUE TITLE
AutoJungle

### ISSUE THREAD

**Issue by berkerbey** [berbb/PortAIO#238]
Crashes after recall. 
Pick: Warwick

**Comment by berbb** [comment]
Most likely when he's buying an item, do you remember what he's bought already so I can test and try to reproduce it?

**Comment by berkerbey** [comment]
It should be Hunter's Talisman.

**Comment by berbb** [comment]
Just tested and it's working fine, did the crash only happen once or was it continuous? If it was just once let's hope it was just that one time.

**Comment by chienhao10** [comment]
@berbb u should wait longer to take out autojungle tho. it is happening the same thing in L#, but only for 1 or 2 users reporting this issue. and they never reply back is it happened once or more than once. but i still not yet found a problem on WW yet.

**Comment by berbb** [comment]
@chienhao10 It's okay, you guys are working hard on it and I'm just doing nothing but porting it. I'll definitely come back to it though in the future.
