### ISSUE TITLE
TheCheater 

### ISSUE THREAD

**Issue by DannyTheGod** [berbb/PortAIO#238]
a game with 9 scripters? no way , i think the prediction might be wrong or something
http://i.imgur.com/l8hylrT.png

**Comment by Muse30** [comment]
lol

**Comment by KiriharaSenpai** [comment]
u re wrong dude if theres a scripter the number he had must be higher than 120

**Comment by Jokiblack** [comment]
what script is this? in photo?

**Comment by harnonsinho** [comment]
its only scripter if have 50+ other less than that is just legit.

**Comment by berbb** [comment]
Regardless, I've already stated that the algorithm is probably outdated.
