### ISSUE TITLE
Kalista rend suggestion

### ISSUE THREAD

**Issue by 3ackdoor** [berbb/PortAIO#239]
I found something work better in challengerseries
adjust rend dmg prediction : set to 80/300
result : work great except crab and dragon

I suggest add this setting in reborn and add hotkey to sentinel to dragon or baron

**Comment by berbb** [comment]
Will do, although I'm not doing the sentinel hotkey to all of them.

**Comment by berbb** [comment]
Added slider to all Kalista's.
