### ISSUE TITLE
Tf - Nida 

### ISSUE THREAD

**Issue by LostLula** [berbb/PortAIO#239]
TF on OKTW dont pick cards at automatic ( tf on OTKW is better because have humanizer on pick)

Nechrito Nidale >> you can add a option for disable Bushwack or put mana manager for this, 
It would be amazing (this script if far way better then kuriso nidale but bushwack spend alot of mana and this broken the gameplay.)

thx for aio and your time.

you can put your paypal account for donation at readme?

**Comment by Muse30** [comment]
I'll check.. @berbb does not take donations so that's why there is no PayPal account

mine is : jrcrack009@gmail.com , I don't do as much as berbb tho so whatever you want

**Comment by Muse30** [comment]
Fixed TF and added the mana slider for Bushwack
