### ISSUE TITLE
Skarner Crashing

### ISSUE THREAD

**Issue by harnonsinho** [berbb/PortAIO#240]
Randomly at combo mode.
Nabb Tracker, Skin Changer and Recall Tracker activated.

**Comment by berbb** [comment]
Was it crashing before 6, after 6 or both?

**Comment by berbb** [comment]
I'm testing it and its not crashing for me. Both pre-6 and post-6, although, it may be skin changer thats crashing because his model changes when he W's so try disabling Skin Changer.
