### ISSUE TITLE
PrideStalker Rengar crash

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#242]
Pridstalker rengar crash whenyou try to use him ; u cant play cant change settings.
any console error
Ty for portaio

**Comment by IlikeBaconLol** [comment]
When u move to pridestalker from elrengar

**Comment by Muse30** [comment]
why did you close this? the error is fixed or? I havent had time to test

**Comment by IlikeBaconLol** [comment]
It looks like i used an addon which was in conflict with a lot of other ones, like for gp and the last thing which i want its to make u waste your time. 
Pridzstalker and elrengar are working perfectly atm !
