### ISSUE TITLE
Kurisu riven burst

### ISSUE THREAD

**Issue by spvrtan** [berbb/PortAIO#244]
Kurisu riven burst is crashing the game, happens all the time when it jumps on an enemy
Edit: Crashing when R is used to kill an enemy also
Edit 2: Okay theres a few issues with the R, i dont know whether its to do with the R1 or R2 sections though, fires backwards sometimes, sometimes doesnt use at all and as i stated above it also crashes

**Comment by berbb** [comment]
I pushed some updates that I'm not confident will fix the crashes but try them out and hopefully the results are better.

**Comment by spvrtan** [comment]
Tried in a custom game, seems to have fixed it! Will try a few normals now and see if it produces the same results. Could you add a keybind for changing R1 and R2 combos? I.e if i press G for R1 it will switch from 'normal kill' to 'hard kill' and if i pressed H for R2 it would switch from 'most damage' to 'kill only' Keep it up berbb :)

**Comment by spvrtan** [comment]
Tested in hexakill, ping kept going over 2000 when in a teamfight, no drops in my internet so not an issue my end, used to do this with some EB addons before, will keep testing

**Comment by Muse30** [comment]
Sure I can add the keybinds... let us know if is crashing again

**Comment by spvrtan** [comment]
shouldnt have closed this until i could test it completely buddy, i've tested it in 2 games, 1 with bots and 1 hexakill, still need to try it in a normal game.. :) although thanks for adding the keybinds if you can, i'll continue to post feedback about this! This is the only script i've EVER used for riven in over a year i've been satisfied with, thanks a lot for the port

**Comment by spvrtan** [comment]
More feedback: burst is kinda buggy, will flash CLOSE to an enemy sometimes rather than on them and W, but it no longer crashes

**Comment by Muse30** [comment]
I added the keybinds cant check the burst combo for now

**Comment by berbb** [comment]
Oh totally forgot about this but immediately after you use burst switch to combo key.
