### ISSUE TITLE
ezevade flashing all spells

### ISSUE THREAD

**Issue by coreAIM** [berbb/PortAIO#246]
ezevade is actaully nearly flashing every single time if my flash is up like lux q for no reason .
never changed the settings
cleaned appdata and did a fresh install but still the same issue .

**Comment by Lemonadez** [comment]
go ezevade settings. and manually change the settings for flash

**Comment by coreAIM** [comment]
no spells were actually on flash lvl , only amumu ulti and lux r was

**Comment by lgndz** [comment]
Try altering Flash settings to "Undodgeable" and see if that stops it from flashing nonstop (what was it set to by default?_)

**Comment by HDown-idk** [comment]
"Undodgeable" have this issue too

**Comment by Requital** [comment]
Everything is fine for me tho

**Comment by berbb** [comment]
Won't be able to fix because I'm not even sure how to fix it. The only way I do know is to re-port it. If all these bugs keep reoccuring then I WILL remove ezEvade.

**Comment by lgndz** [comment]
So weird - I've not had any issues at all with it doing this..

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Mon, Jun 13, 2016 at 7:30 PM -0400, "berbb" <notifications@github.com> wrote:












Closed #246.
