### ISSUE TITLE
Activators

### ISSUE THREAD

**Issue by nightsole** [berbb/PortAIO#247]
Elutilitydoesnt use FOM sometimes and it doesn't use summoner spells sometimes , so i use the other activator which is a lot better btw , problem is the second one freezes the game for me completely, i tried deleting appdata , same , it's better than elutility but only problem is that it freezes the game when i press space, fix plz

**Comment by Muse30** [comment]
I dont use ElUtility but I only tested NabbActivator in custom game and it didnt crash... I will test on a normal game today

**Comment by nightsole** [comment]
test and feedback plz, i get random freezes n crash maybe its just on my end.

**Comment by lgndz** [comment]
Nabb works 100 for me

**Comment by nightsole** [comment]
Then it's on my end , my apologies.
