### ISSUE TITLE
Alistar E crash

### ISSUE THREAD

**Issue by vperpl** [berbb/PortAIO#249]
Seems like whenever alistar uses "E" to heal his allies (enemy team)
it crashes leaague

**Comment by IlikeBaconLol** [comment]
Did u clean appdata ? disabled all utilities ?

**Comment by berbb** [comment]
What utilities & champions are you using?

**Comment by KiriharaSenpai** [comment]
0 crash for me i dont understand how people get crash i never expericenced any crash after public release maybe related with outdated or corrupted c++ runtimes

**Comment by vperpl** [comment]
well, nab tracker, evade,

**Comment by vperpl** [comment]
its pretty damn random thou.
had 2 games with alistar in enemy no crash.
im rly lost, the crash is so fuckin random xD

**Comment by berbb** [comment]
Maybe it wasn't Alistar, can you recall anything else that happened when you crashed?

**Comment by vperpl** [comment]
once i crashed on 3v3 (hexakill) by simply walking near vilemav, had no vision on him. when stepped into shroom it just crashed no idea what is causing it, they are pretty damn random.
occurance is either LOW / none or high.
most crashes occure when enemy team got vayne. so im just switichg than to something else than ur aio. because i just can't trade without a crash with vayne its like gambling 50% chance.
when i get crash ill make u prnt screens & post them here. so u will get a grasp about what was going on in a fight.

**Comment by inphratiic** [comment]
@vperpl maybe try to enable console on EB loader and see if you get any error on it when the crash happens

**Comment by Luc4z** [comment]
I played 3 games with Alistar since yesterday and its fine , use with N Tracker only and fine as well , might be some conflict with another addons

**Comment by vperpl** [comment]
crashes didn't occure for like 30 games so don't rly know what causes it.
as i said some games never crash but some just constantly spam crash on enemy hit.
