### ISSUE TITLE
Darius's W (General)

### ISSUE THREAD

**Issue by yorik100** [berbb/PortAIO#25]
All addons are using W after AA for AA reset, but it use W and attack like there wasn't any AA reset
Example : 1 AA per secs, AA, W and use the W boosted attack after 1 sec (Example attack speed)

In every Darius addons

**Comment by berbb** [comment]
I've recently updated AA resets and the EB orb has also try again and let me know.

**Comment by yorik100** [comment]
Fixed, but with ExorAIO Darius, it make crash when it load, and dosn't load drawings sometime (It crash more than usualy) and another problem non-related to Darius, it crash sometimes when we're using sum spell (I'm using same utilities than before + MasterMind)

Sry for my very bad English

**Comment by berbb** [comment]
I'm planning to change how PortAIO loads champs/utilities so hopefully it will crash less. As for the summoner spell crashes I have no idea what is causing that, nothing in PortAIO has an event that waits for casting manual summoner spells.
