### ISSUE TITLE
evadee

### ISSUE THREAD

**Issue by SamisDaShine** [berbb/PortAIO#250]
Hi
I have enable on portaio evadee and evadee no load.

I go load ez and evadee and no loading. Why/?

Ty for portaio

**Comment by berbb** [comment]
Any console errors?

**Comment by Shazelol** [comment]
U try deleting %appdata% and reinstall port?

**Comment by berbb** [comment]
Were you on hexakill?

**Comment by berbb** [comment]
https://github.com/berbb/PortAIO/issues/254 - Refer here it seems you're having the same issue and most likely will be down to the same solution.
