### ISSUE TITLE
Slatty Ryze

### ISSUE THREAD

**Issue by bestoneuwest** [berbb/PortAIO#252]
I open this issue yesterday but its deleted. I was thinking it is fixed, but now i just finished my game with slatty ryze and got crush 2 times,  then i switch to ELRYZE and it was ok. I like more slatty ryze so if u can see what is the problem.

**Comment by inphratiic** [comment]
so maybe u could give some more info about the crashs like when it happened , what you were doing when it happened, if u only using the sluttyryze or using any other scripts( evade, activator), it's kinda hard for them to troubleshoot if u just say crash no work and nothing else

**Comment by bestoneuwest** [comment]
its slatty ryze 100% bcs i use every time same settings for evade and utility, it crashes in team fight and 1v1 when i hold space, not sure what more info u need...

**Comment by berbb** [comment]
The only thing now that would make it 100% Slutty Ryze is if you turn off everything like utils, evade and other addons and just play Ryze with Slutty Ryze. I played him yesterday and it was doing just fine.

**Comment by bestoneuwest** [comment]
played 3 games today, no crush, everything was ok.

**Comment by berbb** [comment]
Hopefully it stays that way, I'm going to be closing this, but if it is occurs again then make a new issue.
