### ISSUE TITLE
ezevade crash

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#253]
so i experienced this crash quite a few times already ( different champions and different situations ) so i can't really explain when it happens .
here it goes a console error i get when the crash happens:
![ezevade](https://cloud.githubusercontent.com/assets/9076953/15986621/1508b4ee-3004-11e6-95aa-52e583bf611b.png)

**Comment by berbb** [comment]
Won't be able to fix because I'm not even sure how to fix it. The only way I do know is to re-port it. If all these bugs keep reoccuring then I WILL remove ezEvade.

**Comment by inphratiic** [comment]
@berbb  atleast for me it only happens like 2 times in 10 games so it isn't really a annoying crash

**Comment by Muse30** [comment]
@inphratiic ezevade was ported again.. test and hopefully is fixed

**Comment by inphratiic** [comment]
@berbb @Muse30  sadly it happened again with the same error code ( it could maybe be some problem with the port of the function that gives the error, for example it could be returning the wrong values/position/ whatever it returns, it could also be a broken function used by the script on berb.common) PS: i really don't know what is the problem but i'm shooting solutions into the air maybe some of them is correct

**Comment by berbb** [comment]
The error code usually has nothing to do with the crashes. As long as its not crashing anymore then we're good.

**Comment by inphratiic** [comment]
@berbb the thing is that i only get that error code when the game crashes if it won't crash i don't get the error

**Comment by berbb** [comment]
how often does it occur?

**Comment by inphratiic** [comment]
happened only once ( was playing xinzhao top), it also appears that only happens when i'm playing mid or toplane(i guess this has nothing to do with it but never crashed when playing botlane)  and only when i'm low in hp

**Comment by Monnq** [comment]
I played mid and jungle after the new port and didn't encounter a single crash so...

**Comment by inphratiic** [comment]
@Monnq smooth but like i said it doesn't happen every game

**Comment by Monnq** [comment]
Which champion were you playing against when it happened?

**Comment by inphratiic** [comment]
@Monnq mate if u had read the whole issue u would see that it doesn't happen with specific champions, actually it's quite random, the only thing that connect every single crash is the low hp thing

**Comment by Shazelol** [comment]
What is your config in EzVade?, I use Hawk' config for this ezvade = 0 crashes.

**Comment by lgndz** [comment]
I use default ezevade with "Dodge only dangerous" turned on. Smooth setting. All Advanced options turned on. Everything else default
I get no crashing. Report of EzEvade is working like a charm. 

Also- try with Nabbactivator off if you have it on

I might suggest deleting all EB stuff and reinstalling prerequisites and possibly repairing LoL

**Comment by inphratiic** [comment]
@berbb it seems that i'm the only one having that error code so it's probably something on my end, so i'm closing this issue
