### ISSUE TITLE
evades ports doesnt load

### ISSUE THREAD

**Issue by KiriharaSenpai** [berbb/PortAIO#254]
hi have a good day today i cleared my appdata and went in a game then i saw that evade didnt load i tried switching between evades several times but still same

**Comment by berbb** [comment]
Just tested and they are working, when it didn't work were you on hexakill by any chance?

**Comment by KiriharaSenpai** [comment]
nope berbb im on ranked idk but thats occured after i cleared my appdata

**Comment by KiriharaSenpai** [comment]
holy my bad sorry  i forgot to tick evade so sorry thanks for portaio
