### ISSUE TITLE
Darius exor never ult

### ISSUE THREAD

**Issue by SidaRevamped** [berbb/PortAIO#257]
title

**Comment by Muse30** [comment]
weird but pushed an update should work

**Comment by SidaRevamped** [comment]
ok i will test ty man

**Comment by SidaRevamped** [comment]
still does not use ult

**Comment by Muse30** [comment]
it did for me lol .. well I cant test again right now

**Comment by SidaRevamped** [comment]
will test again probably problem on my side

**Comment by SidaRevamped** [comment]
work now ty man , i had clear appdata and working now

**Comment by Muse30** [comment]
oh ok... nice :+1:
