### ISSUE TITLE
Vi Dual port suggestion

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#258]
currently vi wont use Q in combo even actived , and it has magnet melee included but no option to turn off. 

i presonally prefer EndifVi > xQx Vi , thanks

**Comment by Muse30** [comment]
Fixed Vi and added endifVi to the to-Do list

**Comment by Muse30** [comment]
well looks like endif vi was deleted from l# and github

**Comment by Luc4z** [comment]
oh darn it , hope someone has backed it up and can upload it , that one is pretty nice and got more features in it
