### ISSUE TITLE
Respond game

### ISSUE THREAD

**Issue by memsenpai** [berbb/PortAIO#260]
i play riven in game
i use assembly riven ,ezevadee,activator,tracker,skinschanger
in combo some time i got respond game -> taskmanage kill game
i try untick tracker ,skinschanger still respond

**Comment by berbb** [comment]
Which Riven were you using?...

**Comment by memsenpai** [comment]
The first option riven port and kurisu

**Comment by berbb** [comment]
They both crash the game? When you're fighting, farming, walking etcc?

**Comment by memsenpai** [comment]
When combo fighting

**Comment by berbb** [comment]
It's definitely an activator then, I've been using Kurisu Riven and I haven't crashed but if you have with 2 Riven scripts then it's an activator. Which one are you using?

**Comment by memsenpai** [comment]
I use activator in portaio elunity

**Comment by berbb** [comment]
If you can remember, can you tell me who you were fighting? Were you fighting someone with a stealth skill? Or was an alistar in the game and was nearby?

**Comment by memsenpai** [comment]
Volibear ,in game havent alistar

**Comment by berbb** [comment]
Sorry I haven't directed my attention to this issue but has it happened recently?

**Comment by memsenpai** [comment]
yes in 6.11

2016-06-16 14:11 GMT+07:00 berbb <notifications@github.com>:

**Comment by berbb** [comment]
What about 6.12?

**Comment by lgndz** [comment]
I havent had any issues (played 2 game on new patch) using NABB + ezEvade (no FOW/Smooth/All adv checked). 

The last time I had significant issues with not responding was when I was usuing Autosharp

**Comment by memsenpai** [comment]
I still not try it in 6.12
Vào 16-06-2016 22:52, "lgndz" <notifications@github.com> đã viết:

**Comment by berbb** [comment]
When get the chance try it out and let me know.
