### ISSUE TITLE
iKalista crashing

### ISSUE THREAD

**Issue by kimzsabry** [berbb/PortAIO#264]
iKalista is crashing tried different kalista addons all working well but iKalista which is the best one crashes.

**Comment by Shazelol** [comment]
Yes, crash when I use Q manually or in kitting for myself.

**Comment by xGoldenS** [comment]
Confirm i have same bug

**Comment by endergametime** [comment]
I can confirm this. It doesn't crash instantly but when she does a spell maybe or an aa in combo mode

**Comment by berbb** [comment]
Replaced iKalista with Marksman II, iKalista Reborn was the newer version of iKalista anyway.
