### ISSUE TITLE
ezevade ashe ult

### ISSUE THREAD

**Issue by haxorwannabe** [berbb/PortAIO#266]
ashe ult is bugged still try to dodge even when ult is already gone

**Comment by Shazelol** [comment]
No only ashe, also with Draven too. I think in global ultimates bug.

**Comment by SidaRevamped** [comment]
yeah all global ult are so buggy fix needed

**Comment by berbb** [comment]
Won't be able to fix because I'm not even sure how to fix it. The only way I do know is to re-port it. If all these bugs keep reoccuring then I WILL remove ezEvade.
