### ISSUE TITLE
Shaco clone doesn't follow the enemy as it should(underratedaio) and fiddle still cancel w channeling

### ISSUE THREAD

**Issue by ThugDogeNulled** [berbb/PortAIO#27]
Shaco clone doesn't follow the enemy as it should(underratedaio) and fiddle still cancel w channeling.

**Comment by PortAIOMuse** [comment]
tried a lot of thing with the fiddle W but I think is fixed now... can you test again

**Comment by berbb** [comment]
I got enough IP for Fiddle and I'm be testing him out. As for Shaco he should be fixed.

**Comment by ThugDogeNulled** [comment]
still canceling :pepe:

**Comment by ThugDogeNulled** [comment]
if Q and E usage are disabled, only w enabled, the channeling isn't canceled

**Comment by lightduy94** [comment]
I didn't tried Fiddle but i think that fiddle W canceling maybe because of Evade. Make sure that turned off evade before testing Fiddle

**Comment by PortAIOMuse** [comment]
its still canceling you are right.. really fucking weird as sometimes it doesnt

**Comment by inphratiic** [comment]
Does it have any code to cancel the W if enemy killable? it could be that

**Comment by rpgfreak128** [comment]
@berbb some helpful input on this i feel like the W cancel on fiddle is not port or assembly related, its elobuddy related b.c any script with a channel ability cancels for me

**Comment by SidaRevamped** [comment]
royal katarina using a perfect anti-cancel logic probably can make the same for fiddle , i have some time today will check it

**Comment by berbb** [comment]
I honestly feel this is an EB problem, I've used Orbwalker.OnPreAttack and Player.OnIssueOrder (which is used to issue every movement/attack command EB gives) and it's still canceling Drain with an auto attack. Sometimes it goes through and actually works and sometimes it doesn't and cancels w/ auto. Sorry, not sure how to fix it.
