### ISSUE TITLE
Kortatu Syndra

### ISSUE THREAD

**Issue by mar173** [berbb/PortAIO#277]
We need Kortatu Syndra - this one works much better than all others on L#. Your base Syndra works bad, like Elobuddy Syndra i tried L# Kortatu Syndra in game and your PortAIO Syndra on elobuddy - in l# i oneshot all without AP items, with elobuddy cant carry games with Syndra - bad stats - bad combo - bad ulti calculation - bad prediction QE is rly bad on l# this works perfect.

First Game is Kortatu Syndra
Second your PortAIO
Third https://www.elobuddy.net/topic/1039-syndra/

L# is so more OP, + if i played i build start AP with elobuddy and cant do dmg. With L# i build first Tear of the Goddess + Chalice of Harmony and so much dps... kill all enemies in one combo.

http://imgur.com/Avpohci

**Comment by inphratiic** [comment]
well u can't really compare EB to L# since one is paid and the other one is free

**Comment by SidaRevamped** [comment]
dude i re -write the syndra in portAio , just be patient

**Comment by berbb** [comment]
I ported Kortatu's Syndra, test it out. But wait for @SidaRevamped's.
