### ISSUE TITLE
L# Orbwalking

### ISSUE THREAD

**Issue by mar173** [berbb/PortAIO#278]
I see you have all dlls from L# so why not possible to change orbwalker from elobuddy to l# ?

Menu options:
EB Orbwalker, L# Orbwalker
EB Prediction, L# Prediction

**Comment by inphratiic** [comment]
because since L# API != EB API the orbwalker doesn't work like it should

**Comment by Muse30** [comment]
we already tried and it was a mess and to much stuff to fix
