### ISSUE TITLE
Kalista Combo Crash

### ISSUE THREAD

**Issue by omatrixo** [berbb/PortAIO#28]
it's so buggy when i entered the game although i have a very good fps and when i used combo in kalista the client crash

**Comment by KiriharaSenpai** [comment]
lemme try

**Comment by KiriharaSenpai** [comment]
which kalista port do you use reborn or normal one

**Comment by omatrixo** [comment]
normal

**Comment by dankmemer420** [comment]
Use reborn

**Comment by omatrixo** [comment]
okay

**Comment by omatrixo** [comment]
thanks tho

**Comment by KiriharaSenpai** [comment]
yea reborn is better but gonna try normal one for console codes

**Comment by omatrixo** [comment]
btw most of the times it doesn't let me in the game and when i close elobuddy it loads normally any fix?

**Comment by KiriharaSenpai** [comment]
i tested normal one worked awesome

**Comment by KiriharaSenpai** [comment]
be sure all of reqıre software installed on your comp
