### ISSUE TITLE
Crashing randomly

### ISSUE THREAD

**Issue by Requital** [berbb/PortAIO#285]
Playing Vayne
Addons: Challenger Vayne Options: SAC Q/ 360 condemn, EzEvade, NabbTracker,NabbActivator,

While presssing combo key or any other one it crashes randomly. Disabled AntiAlistar

**Comment by Monnq** [comment]
Probably NabbActivator is the one culprit.

**Comment by Shazelol** [comment]
Yes, it's NabbActivator.

**Comment by Muse30** [comment]
looks like nabbactivator is crashing the game.. It did for me too last game, probably I will have to re-port

**Comment by Muse30** [comment]
I ported nabbactivator again.. will test to see if is crashing still

**Comment by lgndz** [comment]
Played two games with no crashing at all using Nabbtracker + ezEvade
