### ISSUE TITLE
Freeze after stun

### ISSUE THREAD

**Issue by mar173** [berbb/PortAIO#286]
ALL RYZE  Addons DON'T USE PASSIVE COMBO -> This is core for Ryze

I have default PortAIO menu settings only changed Ryze addon to sergix Ryze. If Lux stun me then i have freeze and need restart game - i think this is activator or idk.

Ok disabled all utilitys like Anti Alistar etc. -> ALL !
and this is sergix Ryze problem + no draws on sergix ryze. Need rewrite this.

All other Ryze addon no freeze just bad passive combo.

**Comment by Muse30** [comment]
hmm actually all the ryze ports have the best logic possible for the latest changes to ryze passive

**Comment by mar173** [comment]
i tried all ported Ryze and not use correct passive combo
try my Ryze and you will feel the power -> https://github.com/mar173/GTC/blob/master/GTC/Champions/Ryze.cs

**Comment by berbb** [comment]
The combo code is the exact same the Sergix's Ryze so honestly there nothing to rewrite. Also, fixed the drawings.
