### ISSUE TITLE
Kortatu Syndra

### ISSUE THREAD

**Issue by mar173** [berbb/PortAIO#287]
Kortatu Syndra

Prediction:
L# 10/10
PortAIO EB 1/10 - this is not joke...

Cast W:
L# 10/10
PortAIO EB 3/10 (prediction is one but other reason is cast 2x W very slow

QE:
L# 10/10
PortAIO EB 5/10 this prediction wtf...

R:
L# 10/10
PortAIO EB 8/10 better calculation than others eb addons

**Comment by inphratiic** [comment]
Dude, like i already said to you in one of your older issues EB API != L# API, if u wanna cry about prediction go cry on EB site. @berbb and @Muse30 can't do more about that ( they already ported almost every prediction in L# to EB but since the API differences it doesn't have the same perfomance)

**Comment by mar173** [comment]
yes inphratiic i know this and ? This is Elobuddy core problems, slow events etc. so can't be here so fast evade, prediction like in l#. But accuracy can be better, this from PortAIO prediction is worse than in elobuddy - rly bad. You not trust me ? You think this is salz ? This is only a criticism and criticism is good for all. Try in game and then write so shity comments inphratiic... I write this to berbb he is very good not to you inphratiic...

**Comment by inphratiic** [comment]
and btw i bet that ur problem is one that i got some time before that is easily solved, but since u are acting like a dick and not talking to me, i'm not gonna even lose time to try explaining it to you. Have a good day sir :)

**Comment by mar173** [comment]
I don't like you so you can go to hell :)

**Comment by inphratiic** [comment]
the point of you don't liking me just cause i'm trying to explain(i'll say again trying to explain) why you can't have the same perfomance on EB as in L# just proves how little minded u are. Just like u are to leave feedback here , i'm also free to comment on every issue u create ( specially when people already explained to you on issues before why u can't get the same perfomance on both scripting platforms and u keep comparing them in every issue u create).

**Comment by mar173** [comment]
feel free to blame me i don't care about this project anymore

**Comment by inphratiic** [comment]
the thing is that i'm not blaming you... i just want u to understand why u can't have the same perfomance on both scripting platforms so that u stop to say that in L# is better, we all know L# have better perfomance that EB, and if you are using EB it must be because u can't afford or don't want to pay for L#, so if you're not willing to pay u are not in a position to come here and say that L# works better... It just that what i want u to understand, i'm not blaming for anything....

**Comment by mar173** [comment]
EB prediction is much better than PortAIO prediction/tions - i tried in game and you ?

**Comment by Monnq** [comment]
I've been playing some games with Kortatu's Syndra and for me, combined with SDKPredictioner set at Very High it works much better than OKTW Syndra. I guess that there is sth wrong with Sebby's Syndra port, sometimes it misses the QE combo terribly, sometimes doesn't even cast spells, only AA.

**Comment by mar173** [comment]
maybe with sdkpredictioner will be better ye i have all utilities disabled.

**Comment by inphratiic** [comment]
well i'm following this project since the beggining so yes ofc i have tested it on games and for me it doesn't work all that bad

**Comment by Monnq** [comment]
Imho @berbb should check out OKTW, maybe he can fix/tweak something. Kortatu's one works good.

**Comment by SidaRevamped** [comment]
actually i test my change on oktw syndra , probably will pull request soon , i have some problem with the lane clear , but the combo actually work realy good

**Comment by berbb** [comment]
I just made an EBPredictioner. It uses iCreative's AIMBot EB prediction logic and SPredictioners base. It replaces all predictions within PortAIO and uses EB's prediction instead, now if EBPredictioner is giving you a hard time don't come here and act hostile, you can now blame EB.
