### ISSUE TITLE
Gangplank & Heimerdinger

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#29]
-GP forgot how to use his e right
https://s32.postimg.org/fyjwmwp79/Screenshot_52.png

-heim using spells to farm when off
https://s32.postimg.org/u2h2zluwl/Screenshot_51.png

**Comment by Mihawo** [comment]
+1 for the heimerdinger things

**Comment by berbb** [comment]
Fixed heimerdinger, looking into GP right now.

**Comment by berbb** [comment]
Alright, tested GP and I fixed the console error but his combo is correctly executed.
