### ISSUE TITLE
EzEvade doesn't detect FoW spells

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#294]
As stated above, I noticed it when it didn't want to dodge global ults even when FoW dodging was enabled

**Comment by berbb** [comment]
Alright so I tested it and you're definitely right and it's not just global ults sometimes, I had a friend help me test it with Lux here's the results.

FOW Q : Dodged most of the time, a few times hit
Normal Q : Dodged every time

FOW E : Basically never dodged it
Normal E : Dodged pretty decently for a circular skillshot

FOW R : Never dodged, not a single time
Normal R : Dodged decently for a long range skill shot.

This is definitely a problem but a problem I'm not sure how to fix. The first version of the port had this problem and the re-port had this problem. If my guess are accurate I would blame it on EB but EvadeIC and Evade+ on EB have working FOW.
