### ISSUE TITLE
how time consuming would it be to port autosharp to the aio?

### ISSUE THREAD

**Issue by ryroy** [berbb/PortAIO#296]
it feels like it's probably mega time consuming, but it's still worth asking, since it's a really good script, at least for aram, and had a major update this patch and has some really good logic.

**Comment by berbb** [comment]
Not time consuming at all, it was actually easy the first time around. It was on PortAIO before but it took to much time updating away from actually updating PortAIO. Aside from that it simply didn't want to work so I removed it, it's on the to-do list but the only time it will get ported again is if the L#'s version is updated and stable.

**Comment by ryroy** [comment]
hm, but didn't it get a pretty big update? about stability im not sure since i can't really tell, but it seems like both the logic and the autoleveler got updates. I guess I can understand why you're hesitant to port something that's on the "not ready to release" repository, but do give it a look when you have time ^^

**Comment by berbb** [comment]
Maybe later, this isn't promising.

http://image.prntscr.com/image/47bbb15104e747ff9662766cb0a85a43.png
https://i.gyazo.com/68cd3a03b267189b9d5682f980b964f9.png
http://image.prntscr.com/image/47c2edd7c94145fbb8954cf38cb7a0a4.png

**Comment by ryroy** [comment]
hmm, https://github.com/myo/Experimental/tree/master/AutoSharp 
i think they're still using the commercial version. the experimental one seems to have been updated recently, but i wouldn't know without trying it myself.
