### ISSUE TITLE
Activator caused a crash

### ISSUE THREAD

**Issue by BigPhalus** [berbb/PortAIO#297]
was in the middle of a game, had vayne hunter reborn and activator# and a few other EB addons  (plus another EB activator that i forgot to turn off, dont know if thats the issue) ally champion took a tower shot (that would have killed him), my heal went off (activator# auto heal system) and my game frooze from then on. try to reconnect with portaio with the same settings and game was froozen straight when i reconnected, had to reconnect without portaio.

**Comment by berbb** [comment]
Console Errors?

**Comment by BigPhalus** [comment]
I didn't have console enabled when it happened, will try and reproduce it and will recomment here with it

**Comment by Lemonadez** [comment]
u have too many activator that why it crash. You should only have 1 addon check on your Loader.  and that PORTAIO. Un-Checked everything on your Loader.

**Comment by lgndz** [comment]
Just finished another game as Lucian with only PortAIO enabled. nabbtracker + ezevade - no issues

**Comment by berbb** [comment]
Make a new issue if this is still happening with just 1 activator this time :)
