### ISSUE TITLE
God Jungle Tracker/Activator#

### ISSUE THREAD

**Issue by DrHouse12** [berbb/PortAIO#298]
That icon is broken i think . It should be fixed i guess.
https://gyazo.com/b698522d1efb40757ca13534486c4e7e

**Comment by Monnq** [comment]
You probably have ElUtilitySuite jungle tracking too/ God Jungle Tracker doesn't work anyways since packets aren't updated probably.

**Comment by DrHouse12** [comment]
Aahhh yeah its true, i didnt saw that. But i found new error. I've got crash with auto smite in Activator#
https://gyazo.com/4ee68f2d694d523e8d8bec9cc938a0ed

**Comment by berbb** [comment]
This can't be fixed. They're overlapping because you have 2 jungle trackers on... Just turn off the one in ElUtility and you'll be set.

**Comment by berbb** [comment]
@DrHouse12 What were you trying to smite?

**Comment by DrHouse12** [comment]
@berbb I used Activator# and i've got crash on wolfs

**Comment by berbb** [comment]
Just tested this several times in a game and smiting wolfs doesn't cause a crash and I never got that error. Was an enemy near you when you smited wolfs?
