### ISSUE TITLE
Just want to say thank you!

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#3]
First, i wanna say thank you to @berbb who created this awesome PortAIO. Who listen and always try to fix / implement what user suggest / feedback.
Second, i really thank you @Muse30 and all his friends for helping us in these hard days.
I really really thank you all. Especially that you're spent your time in free project for free!

**Comment by Lemonadez** [comment]
I had to register account even tho i dont know how to use this Gitub.

BUT MAN Berbb. I LOVE U DUDE! No gay feelings tho. ^_^ Your AIO is better than the rest of AIO in Elobuddy forum which never been updated.

**Comment by harnonsinho** [comment]
this AIO is the only thing worth using elobuddy.

**Comment by IlikeBaconLol** [comment]
@harnonsinho... eb is free portaio is done for be free for people who cant pay scripts

**Comment by harnonsinho** [comment]
@IlikeBaconLol  I mean this AIO is the only thing good in elobuddy, eb common pred is bad, and 80% of addon database is bad.

**Comment by berbb** [comment]
Thanks for all the kind comments, don't forget to thank @Muse30 also for being my partner in crime!
