### ISSUE TITLE
Kalista

### ISSUE THREAD

**Issue by Jokiblack** [berbb/PortAIO#3]
Kalista bad use E, need update. One hit, and use E.

**Comment by Jokiblack** [comment]
Owner fix https://github.com/iJabbaReborn/Leaguesharp/tree/master/iKalistaReborn/iKalistaReborn

**Comment by berbb** [comment]
Thanks, taking a look at it right now.

**Comment by berbb** [comment]
I just checked both Kalista scripts and none of them use E on 1 stack.

**Comment by Jokiblack** [comment]
Ooo why remove Ikalista, not working Kalista Rework,

**Comment by Jokiblack** [comment]
Reborn woking good
