### ISSUE TITLE
iKalista and Utility

### ISSUE THREAD

**Issue by toughra** [berbb/PortAIO#30]
iKalista inject but utility not inject ( sorry translate)

**Comment by KiriharaSenpai** [comment]
can you provide a screenshor of ur portaio misc menu in game

**Comment by Xelamats** [comment]
Tested out Kalista and it was working perfect. Not sure which one the default one is (if there is more than one) but the one I tried was flawless. <3 Damage indicator is beast af.

**Comment by berbb** [comment]
Check PortAIO misc, make sure "Util only mode? (No champs will load)" is NOT checked! It's loading perfectly :)
