### ISSUE TITLE
kurisu riven combo not working: 

### ISSUE THREAD

**Issue by stanixdor** [berbb/PortAIO#300]
sometimes doesnt use q in combo. after min15-20 doesnt use q in combo neither jungle

**Comment by Monnq** [comment]
The second thing you mentioned - I guess it's a bug with orbwalker, sometimes I also have it when playing other champions

**Comment by stanixdor** [comment]
well its only this addon, nechrito riven uses q correctly during the whole game

**Comment by stanixdor** [comment]
also sometimes the game crahses

**Comment by stanixdor** [comment]
okey i detected where exactly kurisu riven stops using q in combo. lots of times it doesnt use q in combo while your R is activated. When is deactivated it works fine

**Comment by Muse30** [comment]
I close this and leave the other open
