### ISSUE TITLE
kurisu problem exact problem explanation

### ISSUE THREAD

**Issue by stanixdor** [berbb/PortAIO#301]
ok so here is the problem i detected: while your R is activated, a lot of times kurisu riven doesnt use Q, just W and autos, and second R obviously. Its kinda weird because only sometimes uses Q

**Comment by stanixdor** [comment]
also this happens much easier when you have 2 or more near targets

**Comment by berbb** [comment]
Will be testing this soon.

**Comment by berbb** [comment]
I just tested this in a bot game and did this with every situation possible, before though I cleared my appdata.

1v1 bot : Worked
1v2 : Worked
1v3 : Worked
1v4 : Worked
1v5 : Worked and died
