### ISSUE TITLE
Master Yi W reset

### ISSUE THREAD

**Issue by nightgamer** [berbb/PortAIO#302]
Using the default Master Yi script, when it uses w to reset the auto while in combo mode, it just continues to let the w channel instead of immediately canceling it.

**Comment by Muse30** [comment]
whats your "use W below HP" set to?

**Comment by Muse30** [comment]
working fine just tested, change the use W below HP to 100 and it will work

**Comment by nightgamer** [comment]
Thank you!, I really appreciate the team's work on this script!
