### ISSUE TITLE
Compiling Issue?

### ISSUE THREAD

**Issue by PhaxProjects** [berbb/PortAIO#304]
I've reinstall visual studios, and it seems and I've install Berb.Common as well, But when installing PORTAIO it fails

**Comment by toannatkm0** [comment]
Me too Compiling Error

**Comment by lyn690697457** [comment]
Maybe you can try to upgrade Berb.Common？

**Comment by Shazelol** [comment]
Wait for @berbb or @Muse30 for repair this issue.

**Comment by berbb** [comment]
@lyn690697457 <
