### ISSUE TITLE
V2 yasuo error

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#309]
As described above,
Exception occured! Elobuddy might crash!

Type： System.NullReferenceException
Message:Object reference not set to an instance of an object.

Strackrace:
     at YasuoSharpV2.YasuoSharp.onCreateObject<GameObject sender, EventArgs args>
     EloBuddy.GameObject.OnGameObjectCreateNative<GameObject` unit>

**Comment by berbb** [comment]
This is a harmless console error, it shouldn't do much.
