### ISSUE TITLE
Infected Twitch broken

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#311]
at LeagueSharp.SDK.Spell.GetPrediction(Obj_AI_Base unit, Boolean aoe, Single overrideRange, CollisionableObjects collisionable)
   at Infected_Twitch.Event.Modes.Combo()
   at Infected_Twitch.Event.Modes.Update(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()

InnerException(s):
----------------------------------------
Type: System.TypeInitializationException
Message: The type initializer for 'LeagueSharp.Data.Data' threw an exception.

Stracktrace:
   at LeagueSharp.Data.Data.Get[T]()
   at LeagueSharp.SDK.Events..cctor()
----------------------------------------
Type: System.Security.SecurityException
Message: System.Security.Permissions.SecurityPermission

Stracktrace:
   at LeagueSharp.Data.Data..cctor()
----------------------------------------

Does not use nay spells, tried resetting AppData

**Comment by KiriharaSenpai** [comment]
yea itwitch doesnt use e on combo either bot of has some issues but oktw works so good

**Comment by Monnq** [comment]
In @berbb  we trust :D

**Comment by Muse30** [comment]
XD mybad I didnt test.. will check asap

**Comment by Muse30** [comment]
actually I just tested and is working fine aside from E being casted late and that is common error but I dont get that console error

**Comment by berbb** [comment]
Really? It was working pretty well for me, even hot a Penta earlier today with it.

**Comment by KiriharaSenpai** [comment]
for infected it casts it late yea but itwitch doesnt even cast it idk should i configure something in menu btw thanks for your hardworks

**Comment by Monnq** [comment]
http://prntscr.com/bhi1ln all I get everytime I press combo/lane clear key

**Comment by Muse30** [comment]
yeah is the W but everything else works

**Comment by Monnq** [comment]
hopefully you can fix it :P

**Comment by Muse30** [comment]
I did.. will push an update in a minute.. about the E damage is the same in every twich.. is casting late

**Comment by Monnq** [comment]
thanks :)

**Comment by inphratiic** [comment]
@Muse30 regarding twitch E damage it was a problem with elobuddy damage calculation( like kalista E) but iCreative theoretically fixed it some days ago, so it should work i think

**Comment by Muse30** [comment]
@inphratiic  oh ok.. I actually didn't test E ks.. just W

**Comment by Muse30** [comment]
sorry for the delay.. was checking the other 2 ports in the update

fixed
