### ISSUE TITLE
Syndra script - OKTW

### ISSUE THREAD

**Issue by Acheiro** [berbb/PortAIO#312]
Hello,
I would like to ask if you could make it faster. It's kinda like have 500ms delay on Q before it gets cast. Whole combo is humanized so hard and it's really slow. Sometimes spells just don't want to be cast. I would love to see Eskor's Syndra in PortAIO <3

**Comment by Muse30** [comment]
change prediction?

**Comment by berbb** [comment]
As Muse said change prediction, in the PortAIO misc there's an option to change the syndra script and an option to use EBPredictioner which changes all prediction in the game to use EB's prediction which is faster.

**Comment by Acheiro** [comment]
Oops nevermind then didn't see
