### ISSUE TITLE
Here we go again

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#313]
This time it's Valvrave Yasuo Kappa
Drawings are kinda bugged, Q seems not to work when trying to cast combo. Also sth is wrong with auto stacking
========================================
Exception occured! EloBuddy might crash!

Type: System.TypeInitializationException
Message: The type initializer for 'LeagueSharp.SDK.Events' threw an exception.

Stracktrace:
   at LeagueSharp.SDK.Events.IsDashing(Obj_AI_Base unit)
   at Valvrave_Sharp.Plugin.Yasuo.get_IsDashing()
   at Valvrave_Sharp.Plugin.Yasuo.OnDraw(EventArgs args)
   at EloBuddy.Drawing.OnDrawingDrawNative()

InnerException(s):
----------------------------------------
Type: System.TypeInitializationException
Message: The type initializer for 'LeagueSharp.Data.Data' threw an exception.

Stracktrace:
   at LeagueSharp.Data.Data.Get[T]()
   at LeagueSharp.SDK.Events..cctor()
----------------------------------------
Type: System.Security.SecurityException
Message: System.Security.Permissions.SecurityPermission

Stracktrace:
   at LeagueSharp.Data.Data..cctor()
----------------------------------------
========================================

**Comment by berbb** [comment]
An issue with Berb.Common and Events. I just pushed an update that should fix it completely on all SDK addons.

**Comment by inphratiic** [comment]
Seems like berb.common got a little love right @berbb

**Comment by berbb** [comment]
It's going to ;)

Making a few changes now.

**Comment by inphratiic** [comment]
yeah from what i'm "analyzing" , i think that a nice update to b.common(maybe "messing" a bit with the way it's built to be used) would produce a medium/high increase in the addon's perfomance. If it doesn't we can then 100% blame EB beta (if not alpha) API.
PS  ofc this is my opinion and i could be 100% wrong :+1:

**Comment by Monnq** [comment]
#EB_API
https://www.youtube.com/watch?v=cHHLHGNpCSA
