### ISSUE TITLE
Can't get into the game

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#314]
After the recent update, everytime I try to get into the game it just freezes. Tried to inject PortAIO after the game starts but result is still the same.

**Comment by IlikeBaconLol** [comment]
clear apdata + delete elobuddy

**Comment by Monnq** [comment]
Done it, worked for one game, started next - same problem happened.

**Comment by Sharpino** [comment]
you're using evade#?

**Comment by PunchingJay** [comment]
same problem with irelia generellay, cant start game

**Comment by berbb** [comment]
There was some changes with Berb.Common that probably fucked Appdata in the ass so just try clearing appdata.
