### ISSUE TITLE
Lucian LCS issues.

### ISSUE THREAD

**Issue by dongerlel** [berbb/PortAIO#316]
3 issues here.
Sometimes the script bugs out and it stops lasthitting(F5 always helps)
After pointing who to focus champion will go towards them, even if out of range, when holding C or Space, even if the mouse is in a completly different direction(F5 helps)
After some spell, i am not sure which, Q W or E, when the passive is ready to shoot, the champion just stops and waits to use passive on something before moving, F5 doesn't help.
E spell is always casted maximum range which is bad in most cases, dunno if it's script of AIO related

BTW which is the recommended prediction to use for example with ezreal?

I loaded iLucian and the same thing with following marked player happened, so it's something PAIO relater

**Comment by berbb** [comment]
LastHitting problem is definitely not LCSLucian unlike some other scripts included in PortAIO. LCS Lucian doesn't force the target at all so nothing should be overriding the target.

2nd Issue sounds like EB's Orbwalker, LCS Lucian doesn't ever control movement except for Semi Ult. I pushed an update that should fix any activity that should endorse the script to go against Orbwalker Movement.

E at max range is included in the original script, I won't be changing that. Challenger Lucian has a slider to see how far you want to dash.

If any of these issues happen again with other champions, there's a reset orbwalker in PortAIO misc that will fix any last hitting conflicts.
