### ISSUE TITLE
Lucian Laneclear mode

### ISSUE THREAD

**Issue by hardique** [berbb/PortAIO#32]
In Laneclear mode Luc just running and no AA or spells using.

THX for your release,berbb.Awesome work.
also having troubles with ALT TAB and lol crashing,will try borderless mode and will tell if it works.

for everybody : BORDERLESS MODE SOLVES ALT TAB PROBLEM.

tried ezreal - awesome prediction,having troubles with laneclear-no Q usage.

tristana-no Q usage in Laneclear mode.

**Comment by berbb** [comment]
I'm not sure why Lucian is doing that, I just tested and its working fine. I'll add Q in LC mode.
