### ISSUE TITLE
You can not install pls fix

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#325]
Dual-Port\ChallengerSeries\Plugins\Caitlyn.cs(140,263): error CS0121: The call is ambiguous between the following methods or properties: 'LeagueSharp.SDK.Extensions.IsReady(EloBuddy.SpellDataInst, int)' and 'Challenger_Series.Utils.Misc.IsReady(EloBuddy.SpellDataInst, int)'
    Dual-Port\ChallengerSeries\Plugins\Caitlyn.cs(140,162): error CS0121: The call is ambiguous between the following methods or properties: 'LeagueSharp.SDK.Extensions.IsReady(EloBuddy.SpellDataInst, int)' and 'Challenger_Series.Utils.Misc.IsReady(EloBuddy.SpellDataInst, int)'

**Comment by Muse30** [comment]
update berb common

**Comment by lyn690697457** [comment]
I upgraded Berb.Common，but still can not install

**Comment by lyn690697457** [comment]
I'm sure I've updated Berb.Common but still can not install 
so ?
