### ISSUE TITLE
[Suggestion] KeyBind for TF helper in DZAwareness

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#327]
Hey, I have little suggestion. I guess either @berbb  or @PortAIOMuse  can do it. Generally, DZawareness works awesomem, but in later phase of the game it eats some FPS when TF Helper is open. To prevent it, you would need to hide/reveal it from time to time by clicking the small button, which is time consuming especially when the fight is on. My idea is to create a keybind for this (http://prntscr.com/bhul7n) to quickly show the HUD, just like Evade has dangerous key. I guess it would be a nice option :D

**Comment by berbb** [comment]
Done.
