### ISSUE TITLE
ElLeeSin Insec not working properly

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#328]
Sometimes places ward too early or doesn't use ult. If someone can check if everything is all right I will be grateful

**Comment by Muse30** [comment]
my last account was banned so I cant for now keepo

**Comment by Lemonadez** [comment]
Click your enemy and click your ally? that how most Insec work.

**Comment by Monnq** [comment]
dosen't do the job :(

**Comment by Monnq** [comment]
Even when i click to select position where to kick, it Q's to enemy, places ward >in front< of him, not after him, dashes to it and kicks it away, not to my team.

**Comment by berbb** [comment]
Pushed an update, I tested it afterwards and it landed 5/5.
