### ISSUE TITLE
Khazix

### ISSUE THREAD

**Issue by orkenaga** [berbb/PortAIO#330]
Khazix addon is don't work can you fix the problem ?

**Comment by DjVrip** [comment]
https://gyazo.com/ed3929cad8990b78f9694ee76bc7c862
Work for me (3/4 days)

**Comment by berbb** [comment]
I can't fix something when all you say is "don't work".

**Comment by orkenaga** [comment]
I am fix problem, I using one-for-all mode and off tracker, work all champion scripts and utulitys
