### ISSUE TITLE
lissandra

### ISSUE THREAD

**Issue by haxorwannabe** [berbb/PortAIO#331]
every time i pick lissandra i cant even enter in the game with portaio on

**Comment by berbb** [comment]
Have you tried Utility Only Mode to see if it was a Utility causing it?

**Comment by haxorwannabe** [comment]
was in aram and no ididnt try utility only mode coz game crashed in loading scream

**Comment by Muse30** [comment]
do you play on borderless?

**Comment by Lemonadez** [comment]
Maybe DZAwareness if you have it on. I too have this problem with Lissandra and Morgana.

Delete the MenuSaveData on Appdata. Then u can enter the game.

**Comment by haxorwannabe** [comment]
yes i play borderless

**Comment by berbb** [comment]
It's definitely one of the utilities. It happened to me earlier with NabbActivator, are you using NabbActivator?

**Comment by berbb** [comment]
Reverted changes that I'm sure lead to this error, updated.
