### ISSUE TITLE
aatrox

### ISSUE THREAD

**Issue by upza** [berbb/PortAIO#333]
so im currently botting an account andd using your portaio because it works with every champ
it was working perfectly until aatrox was chosen and all it does is show the berb portaio at the start and then crashes

**Comment by berbb** [comment]
Can you tell me who was in the game?

**Comment by upza** [comment]
it was a bot game and the bots were: ashe, trundle, ryze, lux, renekton
the players were: volibear, lulu, master yi, aatrox and teemo

**Comment by berbb** [comment]
Hmm, what utilities are you using?

**Comment by upza** [comment]
portaio and berb.common, evadeIC, Autobuddy, Anti-afk, anti-rito, thugdoge humaniser
I used all utilities in portaio (everything that is default)

**Comment by berbb** [comment]
Alright, I tried to recreate the situation as closely as possible, addons, PortAIO utilities and everything and the crash isn't being reproduced for me.

http://image.prntscr.com/image/ec6797e7829544f1916c264564ca51ef.png - I have all the addons you've stated and I didn't crash. Try deleting EloBuddy in appdata.

**Comment by upza** [comment]
ok, i will do that, thanks for your help
