### ISSUE TITLE
V2 Yasuo Reverse release W

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#334]
Always released to the side or behind
It's too fucking crazy

**Comment by berbb** [comment]
What do you mean?

**Comment by lyn690697457** [comment]
W Always released into the behind

**Comment by lyn690697457** [comment]
W always cast behind

**Comment by lyn690697457** [comment]
Sorry my English is very bad

**Comment by berbb** [comment]
It's okay haha. Does the W dodge the skillshot atleast?

**Comment by lyn690697457** [comment]
Yes

**Comment by berbb** [comment]
But when it it casts behind it doesn't hit anything?

**Comment by lyn690697457** [comment]
Console display properly

**Comment by lyn690697457** [comment]
Maybe you can go to customize the game

**Comment by berbb** [comment]
Updated, fixed.
