### ISSUE TITLE
Ikalista reborn doesnt E champs & jungle.

### ISSUE THREAD

**Issue by BigPhalus** [berbb/PortAIO#336]
It recognises they are killable as it indicates 100% however it never automatically E's champs or jungle, as a side note it does E minions. 
also was wandering what happened to the previous version; Ikalista rework, it used to be available but now it doesnt appear anymore.

**Comment by berbb** [comment]
EloBuddy's API on shields were broken which broke the E calculations because the E calculations also calculate shields and debuffs and what not. Kalista Rework was removed because it was crashing.
