### ISSUE TITLE
e.motion katarina

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#337]
So the feature Cancel the R when no enemies around does not work, would be nice if it could be fixed (if not a manual keybind to stop the ultimate should do the work)

**Comment by berbb** [comment]
Alright, I just pushed a fix and it will only cancel if there is no enemy around you within a range of 600 (R Range + 50) and I did you one better, I also added the manual keybind for any other situation.

**Comment by inphratiic** [comment]
it will not cause the ulti to be automatically canceled by the orbwalker?

**Comment by berbb** [comment]
It shouldn't. The script was designed to automatically disable both autoattacking and movement when Katarina is casting an important spell or has the R active buff on. But keep in mind if you disable Prevent R Cancel your right click will work and it will cancel if you right click.
.
