### ISSUE TITLE
Zed dont use R in combo

### ISSUE THREAD

**Issue by Jokiblack** [berbb/PortAIO#34]
And consolo error https://i.imgur.com/jaM7hES.png

**Comment by KiriharaSenpai** [comment]
dont care about these codes on zed they re meant nothing gonna try for r also u should enable r usage in menu

**Comment by Muse30** [comment]
just so berbb doesnt waste his time ... R is working you have to enable the keybind in combo menu (R settings) and select the champions you want to ult in extra R settings

**Comment by KiriharaSenpai** [comment]
yep exactly what im tryin to mean

**Comment by Muse30** [comment]
whats actually not working is the killsteal like is shown in the console error

**Comment by KiriharaSenpai** [comment]
i asked that berb he said dont worry about it

**Comment by berbb** [comment]
KillSteal is working, that error only happens in the beginning of the game. Besides, the error presented has nothing to do with the killsteal methods other then to check if the skills are ready.
