### ISSUE TITLE
Convenience Fix HoolaYi

### ISSUE THREAD

**Issue by Demisemo** [berbb/PortAIO#340]
The default is not Jungle

Plus ComboW AA is not smooth

**Comment by Muse30** [comment]
will check it out

**Comment by Shazelol** [comment]
Se queda cargando W en el modo "W reset AA". Funciona con los adc's al menos eso noté, pero con otros no.

**Comment by Muse30** [comment]
I'll check in 1 hour

**Comment by berbb** [comment]
Fixed, instead of doing the full W it will force the orbwalker to move after 100ms and will force the orbwalker to Reset its auto attack tick.

@Demisemo The original didn't come with jungle clear.

**Comment by Demisemo** [comment]
@berbb Yes, now will not  jungle clear. There are ways to solve it
