### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by spudgt** [berbb/PortAIO#341]
I found that when the enemy hero in the above, I am a hero in the following , the enemy within my range of skills , enemies and my point is 45 degrees , no matter the anticipation all enemy heroes can not hit 45 degrees. pls fix
all prediction test as same.

**Comment by berbb** [comment]
Have you tried EBPredictioner?

**Comment by spudgt** [comment]
i try ebpredictionet as same

**Comment by berbb** [comment]
Then you can blame EB's prediction, sorry there's really nothing I can do.
