### ISSUE TITLE
Game crashing from time to time - SDKPredictioner problem?

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#343]
Everytime I play with it I sometimes encounter crash. There is nothing in console. Like 5 mins ago I was playing Valvrave Lee with EzEvade, ElUtilSuite and SDKPred enabled. When I pressed the Combo key, game freezed & crashed

**Comment by inphratiic** [comment]
that is probably a crash caused by valvrave lee , it's a known issue for a while and they are still working on a fix

**Comment by DjVrip** [comment]
Same for me, This is the first time it did this to me

**Comment by DjVrip** [comment]
I playing Irelia just have ElUtil & SDK and at the time of spawn (after launching) LoL crash

**Comment by berbb** [comment]
Alright, I just pushed some changes to Berb.Common and PortAIO. Hopefully they fix the issues.

**Comment by lgndz** [comment]
Just leavign feedback -

Still going unresponsive at load in of game. Happens with any champ

**Comment by berbb** [comment]
@lgndz Then its a utility, list your utilities.

**Comment by lgndz** [comment]
Ive been messaging you on Discord but the utilities are as such (from memory since Ihave not been able to load in);

Activator - NABB
Tracker - NABB
SDKPredictioner
EBPredictioner
ezEvade (all advanced options on, FASTEST) (FOW, Dodge only dangerous)
SkinChanger (was activated, didnt use)
UniversalGankAlerter
AutoLevel (god blesS)

**Comment by lgndz** [comment]
Newest test.

Deleted EVERYTHING EB releated and all pre reqs
Reinstalled
Repaired LoL

Loaded DEFAULT PortAIO 
Akali hero

XQX Akali
All default Utilites
Loaded 100%

Modified utils to
ElUtility Suite
NabbTracker
EBPred
ezEvade
UniGank Alerter
UniRecall Tracker

reloaded 100%.


Dont know what this means, but Akali seems to work fine

**Comment by berbb** [comment]
Should be fixed with previous updates.
