### ISSUE TITLE
Syndra is complete trash

### ISSUE THREAD

**Issue by dongerlel** [berbb/PortAIO#345]
Tested both OKTW and Kirusu Syndra both are not using spells when it should be used. Tested every prediction possible. Before the script finally decides to throw Q you are dead already. Also it throws ignite randomly and then is not proceeding with rest of the spells.

**Comment by dongerlel** [comment]
no i tested with prediction from PAIO menu. OKTW, SPrediction, SKD etc

**Comment by berbb** [comment]
Then no, you have not tried "every prediction possible", enable EBPredictioner in the PortAIO misc.

**Comment by berbb** [comment]
When you have EBPredictioner enabled it disables every other prediction so all the predictions on the slider are ineffective and will not work because it is being overridden by EB's Pred.. Since this is now an EB Prediction problem, all I can tell you is set the hitchance slider lower.

**Comment by pellep12** [comment]
I have also tested almost every combination and can agree that Syndra is utter sh*t atm..
Horrible prediction.
