### ISSUE TITLE
One Key To Win?

### ISSUE THREAD

**Issue by Shazelol** [berbb/PortAIO#346]
I try Swain OKTW, but I don't know this key in harass: I press "C" (C is harass in my orbwalker) but this don't harass the enemy, but this laneclear good works. The key "V" don't work for laneclear.
In combo mode(spacebar), Swain don't use "W" at any time with enemy or nothing.

**Comment by PhaxProjects** [comment]
Have you tried to option to reset your orbwalker? If that does'nt work. Clear you Appdata for EloBuddy and reinstall PortAIO and it should be fine.
