### ISSUE TITLE
Issues - Sivir

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#35]
From what I've seen so far:

-----

**Won't auto attack in combo sometimes** - Legit will just not attack anyone while in the combo sometimes. I've changed the prediction and it's repeated with all of them.

**Comment by KiriharaSenpai** [comment]
everything works awesome for me but be sure that for auto attack on oktw menu disable auto attack on combo should be unticked

**Comment by Xelamats** [comment]
That's the thing. I've made sure it was and I've even reloaded everything to see if it was just a one time thing. It kept doing it again. I was against a Blitz and it would never attack them. It would wait for others to come into my range and then attack them. Not sure why.

**Comment by KiriharaSenpai** [comment]
can you provide me screnshots of your oktw settings

**Comment by Xelamats** [comment]
**Default on most other than these changes which I was trying in game (game was 50 minutes):**

Only Champion from portAIO selected.

Changed prediction mode and AIO mode to basically each for about 5 minutes a pop to test them out and auto attack mode to all 3 (same, 5 minutes basically). Happened on all of them. I do have ThugDoge humanizer enabled though with very safe settings so I don't know if that could have interfered somehow. That's all that was changed.

**Comment by KiriharaSenpai** [comment]
maybe these issue related with your humanizer settings cuz i just tested it and for me best sivir addon on eb

**Comment by berbb** [comment]
None of the code in Sivir should be preventing the Orbwalker from working.
