### ISSUE TITLE
Bug report: Viktor

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#35]
Viktor sometimes stutter step when laneclear with E enabled.
And he using W to anti-gapcloser ally's skill. Eg: my team's Fiora use Q then Viktor casted W to anti her gapcloser

**Comment by Lemonadez** [comment]
I dont think that can be fixed, its been like that even all Viktor released, i think it has something to do with minion count to use E.

**Comment by berbb** [comment]
The LC E is pretty normal, annoying and obvious but normal. As for the anti-gapcloser issue, fixed.
