### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kirabc** [berbb/PortAIO#351]
FIrst of all thx for update slutty ryze (is fucking op now thx @Muse30 ) and i test new elzilean is petty good but...@sidarevamped is better \o/

Few suggest for to do list:

UniversalMinimapHack
https://github.com/TheSaltyWaffle/LeagueSharp
(because this is op)

Thresh - The ruler of the soul:
https://github.com/SuperKaisers/KaiserSharp
(this thresh is insane...@muse30 i love your to)

SFXChallenger (Aio)
https://github.com/xQxCPMxQx/LeagueSharp2
(best, vicktor, Orianna and Tf by far.)

PS: i used #activator and #evade today and so far no more crash for me.

**Comment by Muse30** [comment]
what sidarevamped zilean? for the thresh & universal I can add that to the to-do list but the SFX is up to berb.. that looks annoying as fuck to do Keepo

**Comment by lyn690697457** [comment]
zilean Is Muse30 update ，Not sidarevamped upgrade。
Well done @Muse30

**Comment by kirabc** [comment]
@muse30 @SidaRevamped  have a fucking private op zilean for EB '-'

**Comment by Muse30** [comment]
@kirabc well he can upgrate the one in portAIO when he wants like he did before the rework

**Comment by kirabc** [comment]
@muse30 not needs, because if someone need can get right into:

https://github.com/SidaRevamped/Elobuddy

**Comment by SidaRevamped** [comment]
damm guys you found my secret :(

**Comment by SidaRevamped** [comment]
the secret of my private zilean is , i have use ported oktw functions and created a oktw zilean for elobuddy , sebby never created zilean script , so i did .

**Comment by kirabc** [comment]
@SidaRevamped dont tell him...i dont wanna my zilean banned every game =p

**Comment by haxorwannabe** [comment]
also Valvrave Sharp got updated would be nice if u could update it too

**Comment by Muse30** [comment]
@haxorwannabe already updated

**Comment by haxorwannabe** [comment]
oh tks my bad :D
