### ISSUE TITLE
OKTW Input Block?

### ISSUE THREAD

**Issue by pellep12** [berbb/PortAIO#356]
While playing OKTW Syndra i noticed that almost every manual input is blocked for some weird reason..
Have to spamm Q / W / E to make cast spells manualy, any idea why?

::edit::
unrelated to the issue at hand, oktw syndra uses what i consider the WORST prediction ive seen since i started using portaio.

**Comment by berbb** [comment]
What assemblies are you using? And you realize that you can change the prediction right?...

**Comment by pellep12** [comment]
I did change the prediction, i tried almost every single combination.
With and without EB-Pred / SDK-Pred loaded. _(ofc reloaded with F5 after each setting change)_

Utils im using:
Activator - ElUtilSuite
Recall Tracker
God Jungle Tracker
SDKPredictioner _(Tried without aswell)_
EBPredictioner _(Tried without aswell)_

**Comment by berbb** [comment]
Were you using SDK & EBPredictioner at the same time?

**Comment by pellep12** [comment]
Yes.

**Comment by berbb** [comment]
Thats partially why its fucked up. They were both canceling each others input. Did you try Kortatu Syndra?

**Comment by pellep12** [comment]
Yes, Kortatu worked as advertised ;)

**Comment by berbb** [comment]
Then I'm not sure whats the problem just use Kortatu

**Comment by berbb** [comment]
@pellep12 They aren't both enabled by default. http://image.prntscr.com/image/fb53f5d06a1a4b8f84e77a15cf6dfbb6.png

I prefer EBPredictioner (which is left at default) because all the others are ported and maybe unreliable.

**Comment by pellep12** [comment]
No idea why both were enabled for me, i have not touched those settings in a longwhile (since this repo opened up~ish) and those two did not even exist in portaio back then i think.

I would like to add that i really appreciate the work you guys put into this, and i dont want to come off as whiny when reporting possible bugs :).

Ontopic; Disabling one of them does indeed fix the input block i experienced.

**Comment by bestoneuwest** [comment]
Not sure is this the same, but i played today games with OKTW Ashe, Thrust in my viktor, and TF, and when i try go cast some spell manual i need to stop use orbwalk (space,v,c).

**Comment by berbb** [comment]
@bestoneuwest Yeah, that's how it works. As long as you're using an Orbwalker mode it will try to replace the input with a predicted one.

**Comment by bestoneuwest** [comment]
Can somehow i change that ? i was not like that yestarday :S

**Comment by berbb** [comment]
I'll make a change.

**Comment by bestoneuwest** [comment]
nice, bcs its hard to use ashe ulti tristana jump or other spells that are better manual

**Comment by Monnq** [comment]
It was weird for me too when I went on ranked game yesterday and couldn't cast any spell. After disabling EBPredictioner everything was fine, I am using SDKPred

**Comment by Requital** [comment]
Is OKTW Pred working?

**Comment by berbb** [comment]
Fixed up EBPredictioner.

@Requital In OKTW addons it should work fine, but there's not a Predictioner series for it.
