### ISSUE TITLE
Bug: Champion (Sivir and Varus)

### ISSUE THREAD

**Issue by Shazelol** [berbb/PortAIO#36]
I delete appdata first, some times crash with sivir, in autoshield ( i don't know, but i think so) In OKTW, 
Varus Sometimes don't charge Q, and his spam Q in mouse direction.
this happens in urf mode. I don't think in normal game.

**Comment by Lemonadez** [comment]
For Varus Instead of charging Q. it just keep Shooting Q without a charge so it cant hit people at distance.  I tested it too in URF mode.
