### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#36]
**Should we be using the Humanizer providing in portAIO?**

I am currently using ThugDoge Humanizer and am wondering if I should switch over to the one that is provided in your AIO. Not sure if that one is working better alongside all the addons.

-----

What would you guys recommend?

**Comment by KiriharaSenpai** [comment]
im using 3 humanizers in together thugdoge anti rito and berbs humanizer no problem till now

**Comment by berbb** [comment]
You don't have too, using other Humanizers is fine :)

**Comment by Xelamats** [comment]
Awesome. Just making sure :)

@KiriharaSenpai 
Mind sharing your settings with me for what you use? Have you been banned recently or no?

**Comment by iiChopper** [comment]
I am trying to install portAIO but i can't getting failed on instalization ;3

**Comment by berbb** [comment]
@iiChopper Check https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/ and check if you have Berb.Common installed.

**Comment by Xelamats** [comment]
I had to have Berb.Common installed for it to work.

**Comment by iiChopper** [comment]
@berbb @Xelamats Yes you're right, i had to install the Berb.Common. Thanks for your help :)

**Comment by KiriharaSenpai** [comment]
yea i banned recently but didnt use any humanizer idk why but my old acc still alive 
im using default settings

**Comment by Xelamats** [comment]
Ah, I'm using the safest settings I could find/make. Works really well still. Could be a lot faster without them but whatever. It's a low ranked account. Once I get higher up I'll start changing the settings.
