### ISSUE TITLE
PortAIO compilling error

### ISSUE THREAD

**Issue by IlikeBaconLol** [berbb/PortAIO#361]
Already udapted berb common

**Comment by lyn690697457** [comment]
So can't install because EloBuddy upgraded the code

**Comment by lyn690697457** [comment]
So we wait Berb update

**Comment by Muse30** [comment]
yeah an update from EB is causing this.. I cant fix because I am not home

**Comment by IlikeBaconLol** [comment]
rip xD

**Comment by Muse30** [comment]
ok since I don't know when berb is gonna be online use this for now : 
https://github.com/Muse30/PortAIO
install this common first : 
https://github.com/Muse30/Berb.Common

**Comment by IlikeBaconLol** [comment]
love you muse <3

**Comment by hzeuscc** [comment]
@Muse30 I installed your portaio addon but im getting the error "failed" how can fix it?

**Comment by inphratiic** [comment]
@hzeuscc u have to install his berb.common before installing his portAIO

**Comment by hzeuscc** [comment]
@inphratiic already did but i have installed portaio before getting the error "failed"

**Comment by Muse30** [comment]
just delete berb's portaio and common and install both from my github

**Comment by inphratiic** [comment]
@hzeuscc that's because portaio needs berb.common to be compiled ( if it fails to compile it when u installing it it will fail the installation)

**Comment by hzeuscc** [comment]
@Muse30  i tried but when install is berb.common getting the error "failed to download required data" this error appdata was after deleting

**Comment by hzeuscc** [comment]
okay,i fix it now thank you very much :+1:
