### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Rhinoz1** [berbb/PortAIO#364]
major crashes with portAIO... if i dont have league open when the game starts, crash... if i minimize during game, crash... Just yesterday I updated portAIO, played one game, then all of a sudden as soon as league open it crashes. as soon as the message for PortAIO not supporting the all for one game mode starts sliding it crashes. the way it crashes is the screen freezes, i can move mouse and hear sound. I have to ctrl+alt+delete to get out of it. When i do that, and go back, it turns black and i have to wait 2 minutes before it actually closes. help please.
Posting on here as well as EB in case some others are encountering this issue

**Comment by inphratiic** [comment]
Tried to clear app data and check if it still hapenned? u could also try a fresh install of EB to see if it works since i'm not having that issue

**Comment by haxorwannabe** [comment]
first of all u need to play in bordless

**Comment by Rhinoz1** [comment]
i do play boarderless.

**Comment by Rhinoz1** [comment]
just did a fresh install of EB, deleted app data, and reinstalled portaio. did same thing. if i dont have portaio injected it works, but not with it selected.

**Comment by Rhinoz1** [comment]
odd, just tried again and worked..  can minimize now too. :DDD thank you for recommendation, mustve fixed. @inphratiic
