### ISSUE TITLE
valvravsharp LEE sin

### ISSUE THREAD

**Issue by haxorwannabe** [berbb/PortAIO#365]
game crash with any activator without activator also crash from time to time.

**Comment by haxorwannabe** [comment]
after some tests it seems like recall tracker is the problem still testing

**Comment by berbb** [comment]
If you're still testing let me know the results.

**Comment by haxorwannabe** [comment]
seems like the smite is the big problem here i turned off smite in comobo and also in elutility and played for like 10-15min in a bot game w/o any crash

**Comment by haxorwannabe** [comment]
i spend more time testing and so far i dont get crash with nabbactivator smite and smiteGH(not from portaio) but still get crash with elutility smite on

**Comment by haxorwannabe** [comment]
also lee addon dont use Q on jungler

**Comment by kirabc** [comment]
i buy lee now i will make a few tests to

**Comment by kirabc** [comment]
ok...for now no crash with valve lee,

 but elutility and nab activator dont smite dragon baron with option (only smite dragon and baron) up.... butt without this option up both activors work.

and have a OP suggestion for valve:

In Insec Mode "To Mouse Pos" Move champion into target direction.....(default is move to mouse direction.)

**Comment by Hidan123** [comment]
in combo crash

**Comment by berbb** [comment]
Known issue.
