### ISSUE TITLE
ElUtilitySuite Problems

### ISSUE THREAD

**Issue by spvrtan** [berbb/PortAIO#367]
Meant to post this a while ago about titanic hydra, it will not use it in combo as an aa-reset, or at all for that matter. Also since the recent update to EB/PortAio it wont use smite for jungle mobs/dragons/baron etc

**Comment by Muse30** [comment]
for the smite I havent test but looks like the original is also having problems with smite
will check titanic hydra

**Comment by Muse30** [comment]
smite was reworked so report back please

**Comment by BuckFrandon** [comment]
I had the same problem worked fine after update! crashed on chickens once other than that perfect.

**Comment by spvrtan** [comment]
Seems to be working now, though i dont like the lack of options in the reworked mode, the only mob i want it to smite is red/baron/drag so maybe add the option back for what you want to smite? Keep up the great work

**Comment by Muse30** [comment]
sure I'll add that
