### ISSUE TITLE
Game crashing when pressing Combo key (Valvrave Lee Sin)

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#369]
Everytime I am close to an enemy and press Space game freezes and crashes. Thought it's because of EBPredictioner but SDKPRed also crashes it. Game also stops from working when none of these two are enabled. Im using recall tracker, ezevade, elutility suite and nabbtracker also.

**Comment by haxorwannabe** [comment]
i think wut makes this crash is smite i turned off smite in combo and in elutility and so far no crashs

**Comment by berbb** [comment]
The smite issue should be fixed with recent updates.
