### ISSUE TITLE
Seph Cassiopeia will crash game

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#37]
i tried couple times and after i change dual port option to Seph Cassiopeia , i will crash after EB loaded , 
so i can't use PortAIO with Cass now , FeelsBadMan , can you disable "Seph Cass" in option atm ? thanks !

**Comment by berbb** [comment]
Clear app data.

**Comment by berbb** [comment]
Tested and it didn't crash at all on load/switching dual ports/champion only.
