### ISSUE TITLE
Valralvesharp - Lee Sin

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#37]
Doesn't use smite collision for Q, tested multiple times.

**Comment by berbb** [comment]
AS a result to making the Q Pred better, it broke the Q>Smite, I'll look at it later.

**Comment by berbb** [comment]
I've pushed a fixed but I'm not sure if its working, update and test it out :)

**Comment by dankmemer420** [comment]
Will test after this game.

**Comment by dankmemer420** [comment]
Still not using smite.

**Comment by berbb** [comment]
Alright, this time I actually tested it, and it worked, update and try it :)

**Comment by dankmemer420** [comment]
Alright nice man, thanks.
