### ISSUE TITLE
Game is crashing w/Zac

### ISSUE THREAD

**Issue by soulcrash** [berbb/PortAIO#370]
If I play with Zac (w/PortAIO) it does instantly crash the game

**Comment by Muse30** [comment]
are you using any utility ? or just zac

**Comment by Rhinoz1** [comment]
dont load portaio in game, go into custom, make sure boarderless... huyge issue if on full screen. then f6 and check portaio and hit f5 in game. see if fix or not. if not, try fresh install of eb.. clear appdata of eb as well. should fix. i had same issue

**Comment by soulcrash** [comment]
just zac ^^

**Comment by berbb** [comment]
Checked and its working fine, even the combo is cool :)

A clearing of appdata always helps.
