### ISSUE TITLE
Nabb activator feature request

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#372]
Could u add a feature to not use the summoner heal to save allies?

**Comment by Rhinoz1** [comment]
there is one on there, just uncheck the use heal and use it yourself

**Comment by Muse30** [comment]
@Rhinoz1

**Comment by inphratiic** [comment]
@Muse30 i guess u guys didn't understood me xD, i would like it to be automatically used but just to save me, for example it wastes heal too many times trying to save allies that are going to die anyways, i wouldn't mind using it manually but most of the times i forget i have it and don't use it

**Comment by Muse30** [comment]
oh ok so you dont want to use it on allies never.. I got you

**Comment by inphratiic** [comment]
yeah, that's right i only want it to use to save me auttomatically, and then i can manually use it if it can actually save someone

**Comment by Muse30** [comment]
added the option.. is on the type menu

**Comment by inphratiic** [comment]
thank you
