### ISSUE TITLE
Yi issue

### ISSUE THREAD

**Issue by spvrtan** [berbb/PortAIO#374]
Works perfectly fine when theres one target, any more than that and it wont use any abilities or even aa

**Comment by kirabc** [comment]
test it today....its fine...just setup your target selector better

**Comment by spvrtan** [comment]
it has nothing to do with the target selector, without the addon it will aa otehr enemies in range as normal. I dont post issues for no reason

**Comment by Luc4z** [comment]
yes seems like this is the common issue for Yi now .

**Comment by LindsNemesis** [comment]
Yes i have the same problem with YI

**Comment by berbb** [comment]
Pushed a fix, test it out and tell me how it goes.

**Comment by LindsNemesis** [comment]
I Will test now in ascencion mode

**Comment by Luc4z** [comment]
and also it still use Q to dodge everything in menu even not active anything with Q , seems like menu setting is broken

**Comment by LindsNemesis** [comment]
For me is okay AA now i think
i will test another match after i eat something

**Comment by berbb** [comment]
I just tested it in a custom and it worked perfectly fine.
