### ISSUE TITLE
all riven scripts issue

### ISSUE THREAD

**Issue by Rhinoz1** [berbb/PortAIO#375]
No matter what script i use, heaven strike or kurisu or neg, it uses one q and aa. and then stops and just stands there. very irritating...

**Comment by Muse30** [comment]
not portaio problem.. is working fine.. probably you have high ping

**Comment by Rhinoz1** [comment]
ping is 30

**Comment by Muse30** [comment]
try deleting appdata and try again.. is definetly not a problem with portAIO

**Comment by inphratiic** [comment]
@Rhinoz1 u have also the option to use the skills manually :D
