### ISSUE TITLE
Yi Issue

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO#376]
Sometime YI just stop attacking just walk

**Comment by LindsNemesis** [comment]
Example.: In a TeamFight he starts with Q in one enemie and start attacking but stop and just walk

**Comment by Luc4z** [comment]
same here , and also it still use Q to dodge everything in menu even not active anything with Q , seems like menu setting is broken

**Comment by Muse30** [comment]
#374 cant test but lest have only 1 issue for this open
