### ISSUE TITLE
Thresh

### ISSUE THREAD

**Issue by hzeuscc** [berbb/PortAIO#377]
Hey Berbb,u can u do port Thresh - The Chain Warden ? because i dont like oktw thresh addon,this addon is very nice.Pls u can port thresh the chain warden :+1:

**Comment by Muse30** [comment]
what about the other thresh? the ruler.. did you try it

**Comment by hzeuscc** [comment]
Yes,i tried it on leaguesharp,Thresh - The ruler of the soul can u port addon,thanks.

**Comment by hzeuscc** [comment]
@Muse30 can u do that?

**Comment by Muse30** [comment]
yes I add to the to-do list

**Comment by hzeuscc** [comment]
@Muse30 I love u :^3

**Comment by lyn690697457** [comment]
Now the time 19:56
