### ISSUE TITLE
Request [ OneKeyToWin Standalone Prediction ]

### ISSUE THREAD

**Issue by NoobPolice** [berbb/PortAIO#378]
Hey, i Tryed your Ported Genesis Jinx. And the Prediction is Overpowerd.
i Really appriciate your work. But is it possible to Convert this Prediction to a Standalone OKTW Predictioneer ?

is it possible, useing SebbyLib to create a standalone prediction ?

i never miss a E or W with Jinx Genesis.
Great work

**Comment by berbb** [comment]
Sure.
