### ISSUE TITLE
Compatibility Issue - EvadeIC and Draven

### ISSUE THREAD

**Issue by GreatWhite181** [berbb/PortAIO#38]
When using both EvadeIC with Draven from PortAIO, EvadeIC's Draws will stuff up and turn black.
Ive confirmed this is caused by Draven by using Champ mode and Utility mode in Port AIO.
EvadeIC works fine with Utilities by itself and stuffs up with Draven by itself

Dont know if this is an issue with any other champs, only found it with draven.

Thanks for the hard work :)

**Comment by berbb** [comment]
This is an issue that's not on my priority list at all but I'll see what I can do i guess.
