### ISSUE TITLE
Riven FeedBack

### ISSUE THREAD

**Issue by mimu97** [berbb/PortAIO#38]
Dont Work FastHarass or Q MotionCancel
Plz FIX! 
added no flash burstcombo or longRengeCombo 
sry my pool english

**Comment by DannyTheGod** [comment]
what addon ?

**Comment by mimu97** [comment]
NechritoRiven

**Comment by berbb** [comment]
Added to To-Do list.

**Comment by mimu97** [comment]
thanks!
