### ISSUE TITLE
Riven crash

### ISSUE THREAD

**Issue by Hidan123** [berbb/PortAIO#381]
Hi riven is crashing when game start(necherito)

**Comment by berbb** [comment]
Are you playing Ascension?

**Comment by Hidan123** [comment]
Berb i fixed it dunno how LOL and no i was playing normal rift also could u look up the combo because after "w" riven is not using aa sometimes little bit annoying :dancer:

**Comment by Rhinoz1** [comment]
i am having same issue as @Hidan123. does it after first q aa as well. meaning q-aa-wont do anything but stand still

**Comment by 3ackdoor** [comment]
@Rhinoz1 I am having same problem. @berbb please fix dmg indicatorbar, I cant see it clearly(it appears below hpbar)

**Comment by berbb** [comment]
Damage indicator will be removed. And I'll fix the issue where Riven pauses before doing the Q>AA combo.

**Comment by berbb** [comment]
Fixed.
