### ISSUE TITLE
Thresh addon request

### ISSUE THREAD

**Issue by meowmeow1234** [berbb/PortAIO#384]
Hi guys.I like play thresh.Do u port Thresh - As the Chain Warden and Thresh - The Chain Warden? if you help me with this.

**Comment by kirabc** [comment]
use this for thresh:
https://github.com/Muse30/Thresh
just flash >> space and be happy

is pretty good =p

**Comment by meowmeow1234** [comment]
I want to port this addon

**Comment by kirabc** [comment]
k my bad i understand now :)

**Comment by Muse30** [comment]
I will add to the to-do list

**Comment by meowmeow1234** [comment]
@Muse30 When will they be ready

**Comment by Muse30** [comment]
I dont know.. when I feel like porting them.. also I wont port both at the same time

**Comment by Muse30** [comment]
BTW im not doing Vivian's thresh.. that shit is in Chinese XD

**Comment by meowmeow1234** [comment]
@Muse30  what is vivian's thresh :D

**Comment by Muse30** [comment]
@meowmeow1234 Thresh - As the Chain Warden

**Comment by meowmeow1234** [comment]
@Muse30 that's okay? https://github.com/yol0swag/LeagueSharp/tree/master/yol0Thresh in english :D
