### ISSUE TITLE
Cheater

### ISSUE THREAD

**Issue by bestoneuwest** [berbb/PortAIO#386]
It's not and issue, but a question. When this is acctive is says  in all of my games more then 6 ppl use #L common, for some of thme is number 1, for some higher then 9. For me tho it says 0 or sometimes 1. Is this legit or misleading ?

**Comment by berbb** [comment]
I'm not even sure, TheCheater was just something I ported, I didn't care if the calcuations were even right.

Here's what it said on the thread :
"30+ On Preferred Setting Means User Confirmed Scripting 100% no doubt about it, it does constant checks so the number will just get bigger as the game goes on if they are scripting"
