### ISSUE TITLE
Fiora Orbwalk 

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO#387]
ProjectFiora orbwalk for passive dont working for me if need account for test call me

**Comment by LindsNemesis** [comment]
And have the same problem like yi (now for yi is fixed) she dont use aa sometimes and just walk

**Comment by berbb** [comment]
There's a keybind for orbwalking to passive, by default its 'Z', press Z and it will orbwalk to passive. And the second issue, make sure melee magnet is off, it tends to do that.
