### ISSUE TITLE
About the BBS to vote

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#388]
In my personal opinion, I think the delete rule is a good thing. Because now EB plug-in code is not very good, if there are other comparing research platform plug-in code which could encourage the result of more developers to write, not bad do not change if you still insist on this code is right then I think this is a joke. No contrast how can promote the quality improvement?

**Comment by lyn690697457** [comment]
Where are no contrast improvement?

**Comment by lyn690697457** [comment]
I think the EB developers as those on the BBS is in self-deception

**Comment by berbb** [comment]
I agree, but EB just isn't open to the idea of being able to use other people's code outside of EB.

**Comment by lyn690697457** [comment]
EB rules very wrong, it will lead to itself unable to progress。
If it has been so then later there would be no progress of space, look at those developers on the EB
      Why a good plug-in so little? That's because no one wants to compare and then improve their in the past, they always feel good about themselves feel that their code is perfect in my opinion this is the dummist joke them in self-deception

**Comment by lyn690697457** [comment]
Waiting for you to complete PortAIO let it and the original no difference, these people will feel that they are wrong. I hate those who don't want to the improvement of the developer

**Comment by dankmemer420** [comment]
I don't see what the problem is, their code is open source, i feel aslong as you give credits who gives a fuck.

**Comment by Shazelol** [comment]
Fear, If Berbb releases this portAIO in EB, no longer need devs. There are few good scripts, too few, if not all, and doesn't update anything, and complain?
