### ISSUE TITLE
Karthus

### ISSUE THREAD

**Issue by SidaRevamped** [berbb/PortAIO#39]
Karthus laneclear and lasthit does not work at all, the rest work good

**Comment by Sharpino** [comment]
I can confirm

**Comment by berbb** [comment]
Happened to me in URF, will investigate further.

**Comment by Sharpino** [comment]
Please check OKTW Syndra too, same problem

**Comment by SidaRevamped** [comment]
will trying fix it today

**Comment by berbb** [comment]
Fixed.
