### ISSUE TITLE
Yasuo q prediction very bad

### ISSUE THREAD

**Issue by MINTED7** [berbb/PortAIO#39]
the q prediction got worse.it even misses sometimes when the enemy is right right infront of me and walking in a straight line. i tried the eb predictioner but that didnt help either.

**Comment by SidaRevamped** [comment]
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by lyn690697457** [comment]
q prediction  very bad

**Comment by lyn690697457** [comment]
I feel better than the manual release system to predict prospective
