### ISSUE TITLE
El Utility 

### ISSUE THREAD

**Issue by BuckFrandon** [berbb/PortAIO#391]
After smite was reworked it's smiting all mobs and baron, but not doing a hot dang thing to Dragon. lol. If someone could take a look at it that'd be great c:

**Comment by Muse30** [comment]
........... so many updates for smite the past 2 days and is still not working? I will test

**Comment by Monnq** [comment]
Can confirm, doesn't smite dragon. Rest works fine

**Comment by Muse30** [comment]
internet trolling cant test ._.

**Comment by haxorwannabe** [comment]
ELutility smite still make valvravesharp lee sin when click in combo near an enemy

**Comment by BuckFrandon** [comment]
Just tested, still not smiting dragon @Muse30

**Comment by Muse30** [comment]
feelsbadman

**Comment by BuckFrandon** [comment]
It's still good though out smited a diamond jungle main @Muse30 FeelsGoodMan

**Comment by berbb** [comment]
Smite fixed. Working perfectly on dragons.
