### ISSUE TITLE
Evade stops evading to early

### ISSUE THREAD

**Issue by mantas7776** [berbb/PortAIO#392]
Ezevade stops evading morgana stun skillshot to early and champ ends up getting stunned.
EDIT: happens also with some other champs skill shots too, but as that happened to me few days ago I'm not sure which champs.

**Comment by inphratiic** [comment]
also noticed this since a update was made like a week ago to ezevade it dodges the skill but then if u are orbwalking it doesn't stop you from going back in to the "dangerous area"

**Comment by NoobPolice** [comment]
it feels like the dogeingtime is to short it evades for 200 millisecounds then you walk back into the skillshot.

**Comment by Monnq** [comment]
If you train your reflex you can avoid getting back into missile area. It evades fine but removes the draw and movement-blocked area too fast

**Comment by NoobPolice** [comment]
@Monnq  if i would be skileld like that https://www.youtube.com/watch?v=ulN-Df983iQ
i wouldnt script at all. but i need a clean evade :dancer:

**Comment by Monnq** [comment]
^Kappa

**Comment by lgndz** [comment]
Evade# is working 100% in my testing - might recc that if EzEvade is giving you beef

**Comment by Monnq** [comment]
Well I would say it is more like this:
- best dodging & evade spells but also the most obvious evasion: Evade#
- decent dodging and decent evasion spells usage: EzEvade but FoW spell detection is broken

**Comment by Requital** [comment]
Adjust settings in Extra Buffers like extra ping and distance to champ and everything will be ok

**Comment by berbb** [comment]
Yeah, tampering with the delays is the best way to solve this.
