### ISSUE TITLE
Lucian

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#394]
I tried LCS, OKTW, Challenger and none of these working for me (with EBPredictioner enabled, sadly that i didn't try disabled EBPredictioner)

iLucian working fine with EBPredictioner except that sometimes it doesn't use W + never cast extended Q. I disabled EBPredictioner and all working well. And i found that when i use Q, Lucian stop AA, stop move for 0,5 - 1s, just stand and do nothing

**Comment by Monnq** [comment]
Something is broken with EB beta pred afaik

**Comment by Muse30** [comment]
use it without any predictioner... comeon is lucian you dont need to change the prediction xD

**Comment by berbb** [comment]
For some of the Lucians, it has an option in the menu to disable the prediction on the W, try to mess with that.
Its best not to use a predictioner with the lucian addons, it interferes with the extended Q cast and collision calculations.

Will test the Orbwalker failure though.

**Comment by lgndz** [comment]
It is 100% working fine with EBPred for me. I have EBPred set to 75% and it does not affect the Ext Q cast negatively at least.

The pause in combo is real though.
Will mess with Predectioner and see whats up

**Comment by berbb** [comment]
Hopefully fixed the pause in the combo.
