### ISSUE TITLE
Nechrito Rengar

### ISSUE THREAD

**Issue by Hidan123** [berbb/PortAIO#397]
Not casting "e" or "q" at all only w in all combo mods please fix :calling:

**Comment by Muse30** [comment]
Impossible xD but I will check after lcs

**Comment by Hidan123** [comment]
Thanks :ghost:

**Comment by Monnq** [comment]
Are you using DZAwareness?

**Comment by Hidan123** [comment]
No ^^

**Comment by berbb** [comment]
It is working perfectly, hella OP too, try clearing app data or something.
