### ISSUE TITLE
Shadow Tracker and Tracker# - yorik100

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#4]
Hey, is it possible to port these scripts ?

Shadow Tracker : https://github.com/NaviFly/LeagueSharp/tree/master/ShadowTracker
Tracker# : https://github.com/TC-Crew/L-Assemblies/tree/master/Tracker (For the trap tracker (TrapTracker is glitched and we are forced to dodge and it dodge badly and make weirds things + detects Soraka's as a trap))

You can simply ignore this if you don't wanna port something new or you're too lazy

(And you can add a way to have NabbTracker and Tracker# both active at the same time)

Thanks and good luck (I don't care if you don't do it)

**Comment by HDown-idk** [comment]
Soraka best trapperino since 1989 kappa
SFXUtility - best option(

**Comment by berbb** [comment]
Added to to-do.
