### ISSUE TITLE
Orbwalker Identifying full hp creeps as last hit ready

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#4]
Champion Name (eg. Ahri) / Utility (eg. Evade) : portAIO (EzEvade, ElUtility Suite)

If this is an issue about a champion, is this Champion dual-port supported (Check via PortAIO Misc)? If yes which one? : Ashe (OKTW w/ CommonPred, Necherito)

Issue/Problems (Try to be as detailed as possible) : While in any mode, creeps are circled with a "Last Hit Ready" white line as soon as they are acquired by script. This causes the assmb to AA them with no cadence, missing many last hits.

(PS - I dont have an option for labels?)

**Comment by lgndz** [comment]
http://imgur.com/olTJ0JU

Proof about the label =/

**Comment by berbb** [comment]
No ported addon should be doing this, can I see a screenshot of how it's like ingame?

**Comment by lgndz** [comment]
Close this, I think it mighta been an issue with my PC. In testing this afternoon, the drawings were correct and the CS was, more or less, the same as before.

Thanks
