### ISSUE TITLE
Prediction with scripts

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#40]
As far as I could notice while testing several scripts included in this AIO, the prediction that it uses is pretty bad.
Automatic skills often miss enemies, sometimes even when they stand very very close to the champion of a player that uses your AIO.
Didn't find any window in the menu where i could change the type of prediction and its hit chance.
I think it needs to be looked upon

**Comment by KiriharaSenpai** [comment]
idk but prediction is godlike for me doesnt miss 10/7 at least

**Comment by berbb** [comment]
I'll look upon it when you give me the champions being affected by this.
