### ISSUE TITLE
ElDiana

### ISSUE THREAD

**Issue by djole353** [berbb/PortAIO#40]
misaya feature does not work, it will use her ultimate then w and then q after landing, can you fix it?

**Comment by TheKushStyle** [comment]
Probably because eldiana uses leaguesharp casting.

**Comment by berbb** [comment]
The misaya combo is pretty hard to hit in the first place and I'm not sure Nathan/jQuery has updated it in a while. Anyways, I've updated prediction so it should hit faster now.
