### ISSUE TITLE
Kassadin Insta Freeze when i get to lane

### ISSUE THREAD

**Issue by Wa1L** [berbb/PortAIO#401]
I tried both preserved / kassawin and DC the second i get to lane , was against a teemo if that matters

**Comment by PortAIOMuse** [comment]
hmm that doesnt seems to be from portAIO but I will check anyways

**Comment by Lemonadez** [comment]
tested, kassadin working fine no freeze.. I only have 1 Addon check on loader (PORTAIO)
Settings on PortAIO Misc
- Activator Nabb
- Nabb Tracker
- Recall Tracker
- both kassadin Port used during game i take no dc or freeze.

**Comment by Muse30** [comment]
just played a game and no crash / so its probably on your end

**Comment by IlikeBaconLol** [comment]
crashed for me2 worked the last game

**Comment by Muse30** [comment]
alright gonna try again I guess

**Comment by IlikeBaconLol** [comment]
Muse
its when u go mid against gp

**Comment by IlikeBaconLol** [comment]
So muse i did test by trying 1 by 1 all the portaio addons

So the first tiem i went midlane around 1.00 nthg xin apparead crashed with

EvadeIc, presserved kassa eb predictionner tracker activator god jungle trackers and that's all

After i went back only with presserved kassa didnt crash , injected after that all the portaio addons + evadeic and didnt crash.

I cleard apdata before and totaly deleted eb of my computer.

Gl

**Comment by Muse30** [comment]
so the problem is solved? I cant really test for like 3-4 days because I dont have lol installed in this laptop and I get my pc in like 3-4 days

**Comment by IlikeBaconLol** [comment]
No its pretty weird atm its like crashing randomly but only at the begining at the game

**Comment by IlikeBaconLol** [comment]
Doesnt matter of which addons u use it'll crash first time u meet your opponent at a lane i tried mid me

**Comment by Muse30** [comment]
Which utility?

**Comment by IlikeBaconLol** [comment]
Elutility

**Comment by IlikeBaconLol** [comment]
But even disabled it crashed

**Comment by Muse30** [comment]
WUT that's weird

**Comment by IlikeBaconLol** [comment]
I'll retry ? with cleard appdata

**Comment by Muse30** [comment]
well like I said I cant test right now but if its happening with every champion then its probably on your end

**Comment by IlikeBaconLol** [comment]
No just kassa

**Comment by IlikeBaconLol** [comment]
SO 
it crashed WITH ONLY a kassadin portaio addon when i see the enemies for the first time
Preserved kassa

**Comment by Muse30** [comment]
well to be honest I didnt even test preserved kassadin when I did the port so you might be right

**Comment by IlikeBaconLol** [comment]
U should he is love its so fcking op ^^

**Comment by Muse30** [comment]
I cant! xD I dont have league in this laptop

**Comment by IlikeBaconLol** [comment]
So download it and enjoy ur ports bro !

**Comment by Muse30** [comment]
fuck that I am in a hotel the internet here is like 1mb Kappa need to wait 3 days t.t

**Comment by IlikeBaconLol** [comment]
Rip muse :(

**Comment by IlikeBaconLol** [comment]
Gg berb !
And what was wrong if i can ask ?

**Comment by berbb** [comment]
I wasn't about to test it because I don't have Kassadin but I was looking at the damage indicator and I remember it causing crashes before in the earlier days of PortAIO so I disabled it. Hopefully it fixes the crashes while I try a real fix for the HP Bar Indicator.

**Comment by IlikeBaconLol** [comment]
Well done
