### ISSUE TITLE
OKTW Caitlyn still block W

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#402]
You can test it, i cleared appdata, installed new EB but problem still.
It block my W if i cast many W. Please fix it!
I don't use any Humanizer

**Comment by berbb** [comment]
OKTW Caitlyn is made like this. It will block your W if the position of a existing trap is within a distance of 300 from the one you placed. This isn't really a bug but to "fix" this I added a menu option to not let the script block your W cast. It will be listed as "Override Manual W?" in the W Config menu.
