### ISSUE TITLE
Slutty Ryze/PROJECT FIORA/Xerath

### ISSUE THREAD

**Issue by Masyte** [berbb/PortAIO#405]
**The Ryze slutty NOT combando " fast " and always fall the Combar , since the Fiora the " w" not IS RUNNING and xerath OS skillshot station " Bugando " as hitbox**

**Comment by kirabc** [comment]
@Masyte me explica em portugues q eu traduzo pra voce, o ryze creio q esse seja 1 problema universal de todos os ryze nao eh bug do addon...unico ryze limpo eh o do @SidaRevamped 
aki: https://github.com/SidaRevamped/Elobuddy
a questao da fiora e do xerath eu n entendi oq vc quis dizer :+1: 

PS: when he answers I'll translate.

**Comment by Masyte** [comment]
@kirabc A fiora o "W" dela não está funcionando e o xerath não está "combando" direito até o xerath do proprio EB tá mais limpo ^^, não seria possivel pegar o assembly do Kortatu... (Agora que eu vi que  ficou tudo doido a poar que escrevi kkjkjkj tava saindo do estagio ^^ , vlw amigo)

**Comment by LindsNemesis** [comment]
O Da fiora esta realmente com um problema em geral por conta do Orbwalk e do AA as vezes parar é recomendavel utiliza o Joker Fiora por enquanto 
Porém o W pelo menos funciona perfeitamente  pelo menos pra mim o do Project Fiora

**Comment by kirabc** [comment]
@Masyte como assim combando direito? limpou sua app data antes de qualquer coisa? esta demorando para castar skil? ja viu se n eh o target ou prediction mal configurado?

**Comment by Masyte** [comment]
@LindsNemesis  Vlw pela dica <3
@kirabc Sim já fiz como é padrão limpar a app, fiz antes olhei o target e o prediction tbm não achei nada dms e sim está demorando para castar a skill ^^

**Comment by kirabc** [comment]
@mastyle qual o script do xera q ta ruim? nome?

**Comment by Masyte** [comment]
@kirabc OneKeyToWin AIO

**Comment by kirabc** [comment]
@berbb just 1 issue left, Xerath script in OneKeyToWin AIO it takes too long to cast skills (seens prediction inside this script a little broken maybe?)
PS: i dont test just translate.

**Comment by berbb** [comment]
Try different predictions.

**Comment by SidaRevamped** [comment]
slutty ryze always crash when enemy is low

**Comment by HDown-idk** [comment]
Slutty Ryze same problem

**Comment by berbb** [comment]
Alright, since it seems all of this is fixed except for Ryze, I'm closing this since there is already a ryze issue open. https://github.com/berbb/PortAIO/issues/396
