### ISSUE TITLE
NabbActivator's ult auto leveler doesn't work

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#407]
Sorry, it's Activator#

**Comment by Monnq** [comment]
use ElUtilitySuite, it's better

**Comment by lightduy94** [comment]
But ElUltilitySuite doesn't has smite working properly!

**Comment by berbb** [comment]
It does now.

**Comment by lgndz** [comment]
I vouch ElUtil + NabbTRACKER

Prolly the best setup

**Comment by lightduy94** [comment]
@berbb could you look at ElZilean, orbwalker offen doesn't work after combo. I always have to use "Reset orbwalker" to make it work again!

**Comment by berbb** [comment]
- Fixed ElZilean
- Fixed Auto Level Ult on Activator#
