### ISSUE TITLE
Auto Leveler Options

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#408]
@berbb @Muse30 @SidaRevamped 

Any chance that we could get the option to adjust autolevel order from within the EB menu? For example, ashe maxes Q first currently. While this is secret OP, if your against big wave push you need "W" , and such

**Comment by berbb** [comment]
That'd mean making a whole new addon. But there is a addon like that on L#, Universal Leveler, I'll add it to the To-Do list.
