### ISSUE TITLE
Kurisu Riven - Slow combo

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#409]
It gapcloses with E, stands in place for a second, comes to enemy/minion uses W and then casts Q. seems to be slow compared to e.g Nechrito (but nechrito doesn't AA between Q's)

**Comment by stanixdor** [comment]
and the problem of the Q still happens. I dunno how berbb tested it but I've already tested it on 2 different computers cleaning appdata etc, and it still doesn't use properly Q while R is activated

**Comment by Lemonadez** [comment]
turn off any humanizer.. humanizer cause the delay.

**Comment by stanixdor** [comment]
humanizers arent the problem. These riven scripts run so dam smooth using leaguesharp and I personally think that they are ported perfectly. the real problem is elobuddy itself in my opinion

**Comment by berbb** [comment]
@stanixdor I never said I fixed the Q while R, I didn't even know that was an issue.

Anyways, I tested all three of them and they worked perfectly fine before I pushed the update, but now I can't test it because I got banned.

**Comment by IlikeBaconLol** [comment]
@berbb if u need someone /an account for test i can lend u mine
