### ISSUE TITLE
game freeze when use heal

### ISSUE THREAD

**Issue by nongnoobjung** [berbb/PortAIO#41]
1st time use heal on game it always make game freeze i don't know what a problem :(

this happen to me on both activator with oktw

**Comment by berbb** [comment]
Maybe it's not an activator, try playing without any utilites.

**Comment by CPT-imp** [comment]
Same

**Comment by yorik100** [comment]
It's summoners spells in general, they make crash

**Comment by berbb** [comment]
I'm forcing utilities off cause no one seems to be reporting anything with them off.

**Comment by SidaRevamped** [comment]
just disable summoner options in ElUtility and use summoners yoursefl
