### ISSUE TITLE
Crashing when Morgana is in enemy team

### ISSUE THREAD

**Issue by cbozer** [berbb/PortAIO#41]
Same in post. If i playing with turned ON PortAiO (all champs) and morgana is in enemy team i all time when press space got crash.

**Comment by lgndz** [comment]
what champ are you playing
what moduals of PortAIO did you have turned on (champ and utilities? what utilities?)

**Comment by berbb** [comment]
Yeah, I don't know who to fix if you don't give me a champion. If it's happening with all champions then it's a utility error or it's happening on your side. Just provide me with a champion name.

**Comment by cbozer** [comment]
Im playing 1 game as Lee Sin, 1 as Lucian and 3 as Vayne. All time crashing as Vayne when press spacebar and morgana being in my range of AA. Script is Challenegr Vayne and utilities all :x

**Comment by inphratiic** [comment]
I experienced this crash 2 times too playing with vayne i can't remember if morg was on the enemy team but once was with CS vayne and the other with VHR vayne, never happened again so i didn't reported but i'll keep an eye on it and update this if i notice something
