### ISSUE TITLE
ElRengar Crashing

### ISSUE THREAD

**Issue by Requital** [berbb/PortAIO#415]
It crashes whenever you die Addons: NabbTracker, Elutility, EzEvade

**Comment by berbb** [comment]
Good timing, luckily Rengar is free so I was able to test it. Anways, I tested it and I didn't crash at all when I died, and I tested it several times. When this happened was there any console errors? And did it happen constantly?

**Comment by Requital** [comment]
Yeah it did, Idk i dont have console turned on but i will tell you in 1-2 hours if something is appearing

**Comment by Requital** [comment]
Ok so results are: It crashes whenever you use spell or summoner manually while pressing combo nothing appeared in console, and sometimes laneclear/jungleclear stops working after addon using Q

**Comment by berbb** [comment]
Hold that thought real quick this might be EloBuddy's issue : https://www.elobuddy.net/topic/33471-game-crash/

**Comment by Requital** [comment]
But it happened also before 6.13 patch so

**Comment by berbb** [comment]
Then why wasn't the results you just posted in the initial issue?

**Comment by Requital** [comment]
Idk

**Comment by berbb** [comment]
Alright, I'll just keep testing this.

**Comment by Requital** [comment]
Thanks, not trying to troll you or anything just trying to help

**Comment by skipper744** [comment]
when attack akali crash

**Comment by Monnq** [comment]
Are you guys using EvadeIC?

**Comment by skipper744** [comment]
sure

**Comment by Monnq** [comment]
try disabling it then

**Comment by Requital** [comment]
No im using EzEvade i wrote it

**Comment by skipper744** [comment]
can you say me please is better IcEvade or berbb port evade??

**Comment by berbb** [comment]
@skipper744 EvadeIC, it's better developed, better maintained and overall has better quality. 

@Requital Sorry, I haven't been able to find this crash bug at all. To attempt an unlikely fix I pushed updates on ElRengar.
