### ISSUE TITLE
Finally I know why kurisu riven doesnt Q (sorry berbb for being kinda irritating...)

### ISSUE THREAD

**Issue by stanixdor** [berbb/PortAIO#417]
Okay so the thing is simple: the script port works perfectly, but when you buy tiamat/hydra and its available to use (not in cooldown) it simply doesnt cast Q. I cant let you my account if yours is banned

**Comment by berbb** [comment]
It's okay Riven is free so I was able to test it. Anyways I pushed updates to Riven based off this analysis. Go ahead and test it out.

**Comment by stanixdor** [comment]
okay, testing it right now

**Comment by berbb** [comment]
Alright, it should be completely fixed now. I just tested it and it uses Q during R perfectly. I pushed the update as I'm writing this comment so if you're testing this right now it probably doesn't work so you should update PortAIO and continue testing :)
