### ISSUE TITLE
Drop fps

### ISSUE THREAD

**Issue by DannyTheGod** [berbb/PortAIO#42]
can you fix , i usually have 60 FPS but when i use this port, it give me 30 FPS , very annoying, sry bad English

**Comment by KiriharaSenpai** [comment]
men be a spesific which champion do you use or utility cuz i get 70-120 fps around mid game and late game if u dont believe me i can provide a screenshot to you

**Comment by berbb** [comment]
Yeah, I can't help you if you don't tell me what you're using.
