### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#423]
[EloBuddy] Native Exception thrown at: const Native::GameObject::GetType() &

**Comment by DjVrip** [comment]
Same for me, my game crash on combo mode

**Comment by inphratiic** [comment]
Well i guess this last EB update broke some functions cause i'm having console error almost with every addon

**Comment by Muse30** [comment]
if you go to EB you can see a lot of people crashing so is probably from the 6.13 update

**Comment by kirabc** [comment]
@muse30 i test you new el zilean...petty good han '-' rsrsrs i can make a OP suggest for Valvrave Lee? :)

**Comment by Muse30** [comment]
sure

**Comment by kirabc** [comment]
when we press a hotkey of insec "To Mouse"....orbwalk go to mouse direction right? so you can change to go for target direction? this will be insane because we win alot of precision.

my english is petty bad if you can't understand i will explain in another way '-'

**Comment by Paul420** [comment]
I get crash everytime when im using sommoner spells while in combo mode. maybe you can fix that? :)

**Comment by berbb** [comment]
https://github.com/berbb/PortAIO/issues/429
