### ISSUE TITLE
Wondering is it possible to add features in Irelia

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#425]
currently im using best addon >> Irelia reborn from PortAIO , and it don't have flee mode with it , is it possible to add feature in it ? it don't have Flee mode currently , wondering could you guys add it ? like Flee with Q when there's killable minions around cursor . 

i know there's another addon with this feature , or i just copy to here so you guys can put it in easier ? thanks !

**Comment by Muse30** [comment]
added to irelia Reloaded , didnt test tho

**Comment by Luc4z** [comment]
thanks and it works @Muse30  , but it wont check minion is killable or not , Feelsbadman

**Comment by Luc4z** [comment]
why you guys so op ?
