### ISSUE TITLE
Jinx/Yasuo

### ISSUE THREAD

**Issue by Krazy7** [berbb/PortAIO#427]
Have only tested these two, but Yasuo (Seems like all of the available scripts) does not last hit with Q when you are out of AA range, instead he tries to get into AA range to last hit with AA, which denys you from stacking the Q.

Jinx (All of the available scripts) have a stutter feeling, when the enemy is in your lane, the script does not lane clear and does not last hit, at all, the champion just keeps following your cursor.

**Comment by berbb** [comment]
1st problem with Yasuo is an Orbwalker problem, none of the Yasuo scripts use a movement command 
during last hit/laneclear.

As for the Jinx issue, I pushed updates for both of the Sebby's Jinx's that might have problems with this. But the other Jinx's should not have problems with this at all.

**Comment by Krazy7** [comment]
Well how do you fix it then? because this only happens with PortAIO, every script I get from EB's database does not have this problem

**Comment by berbb** [comment]
For which issue Yasuo or Jinx?

**Comment by Krazy7** [comment]
Tested this with the first, second and the last yasuo scripts available (don't remember the names)
And the stutter feeling is with every jinx script, and i've noticed another thing, only checked OKTW for this issue, sometimes when I hold down the lane clear button (V in my case), it seems to act like I am holding the combo button (X in my case), and instead of lane clearing it keeps trying to get within range to attack the enemy.
Also sometimes with OKTW when you hold lane clear it just uses W on enemies while lane clearing, sometimes it even W's into the last position the enemy was seen at before disappearing into fog
