### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Rhinoz1** [berbb/PortAIO#429]
Is EB crashing with PortAIO for anyone or is it working well? i know that EB is only partially functional at the moment so curious if anyone is having problems

**Comment by Sharpino** [comment]
crashed 1 time after the update

**Comment by Paul420** [comment]
I get crash everytime when im using sommoner spells while in combo mode. maybe you can fix that? :)

**Comment by berbb** [comment]
EB's status is still yellow, I haven't been crashing much at all but when it does it happens for no reason.
