### ISSUE TITLE
Thresh addon request

### ISSUE THREAD

**Issue by meowmeow1234** [berbb/PortAIO#430]
https://github.com/yol0swag/LeagueSharp/tree/master/yol0Thresh can u port thresh assembly,thank u :3

**Comment by Muse30** [comment]
not soon.. there are 3 thresh addons but I'll add to the to-do

**Comment by meowmeow1234** [comment]
thank you :M

**Comment by meowmeow1234** [comment]
When will it be ready?

**Comment by berbb** [comment]
Not soon he said, he's ported a couple Thresh addons recently.

**Comment by meowmeow1234** [comment]
@berbb Thank you, I look forward to
