### ISSUE TITLE
Evade # not dodging janna q after the update + exor jhin cancel ult to cast w

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#431]

**Comment by berbb** [comment]
The issue with Jhin shouldn't be happening at all because no orders should be executed when R is activated but I pushed an update to hotfix it.

As for Evade#, what update? I haven't made any large updates on Evade# in a while.

**Comment by Sharpino** [comment]
I think 6.13 update because it was working fine before it and can you check smite ks in elutility?

**Comment by berbb** [comment]
Updated, smite for KS should be fixed.
