### ISSUE TITLE
Lux console errors

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#440]
ellux: https://s32.postimg.org/ba2n3prar/Screenshot_37.png
OKTW: https://s32.postimg.org/8h9fjoqyd/Screenshot_38.png
moon lux: same but no screenshot
and ult prediction is too bad in all addons *tried all predictions*

**Comment by berbb** [comment]
Prediction is out of reach when you tried EB's prediction, can't do much about it. But I'll check the other errors.

**Comment by berbb** [comment]
Updated, all should be fixed.
