### ISSUE TITLE
WHAT THE HELL IS THAT ?

### ISSUE THREAD

**Issue by SidaRevamped** [berbb/PortAIO#441]
i work on gosu mechanics Yasuo and wtf , who coded this? This the more Broken shit in the world wtf , insta penta , dude just need some fixs and insta Challenger

**Comment by Sharpino** [comment]
lmao

**Comment by Hidan123** [comment]
then fix it :+1:

**Comment by SidaRevamped** [comment]
@Hidan123 it is what i'm doing at moment , the cod is realy old , but man some features work so good

**Comment by IlikeBaconLol** [comment]
Yh its such an op addon

**Comment by dankmemer420** [comment]
as far as im aware the guy who made it is proficient in LUA but was new to C#

**Comment by Muse30** [comment]
nice ... thanks for the update to it Keepo
