### ISSUE TITLE
Master Yi suggestion

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#443]
It's really good Master Yi addon, just need some improve and here is my some suggestion:
1. Make option to use Q for killsteal (Will be even better if can list which champion user want to use Q killsteal on, default is all champion).
2. Make option to only use W for AA reset if enemy can be killed with < = 3 AA and > 1 AA.

P/s: I don't have my computer now but i have a question. Does EvadeIC / EzEvade will cancel Yi's W to Evade?

**Comment by Lemonadez** [comment]
Yes Evade/EzEvade will cancel Yi W to dodge dangerous spell such as blitz Q.

**Comment by Luc4z** [comment]
personally think your suggestion should feed back to the L# creator ,because put new stuff with logic in i think it would make berb and muse30 too busy , most they're doing is fixing here tho

**Comment by berbb** [comment]
Done.
