### ISSUE TITLE
[Request]Fake server message.

### ISSUE THREAD

**Issue by Ryuiijin** [berbb/PortAIO#445]
Hello berb, can you port the https://github.com/SwipeDan/LeagueSharp/tree/master/Fake%20Server%20Messages please? I'm pretty sure that addon hasn't got so much object. So it will be easy to port for you if you want. Thank you.

**Comment by berbb** [comment]
I already ported it a while back, I just didn't keep it because it doesn't work like it should.

When I ported it here's what it looked like :
[00:01] Summoner : ------------------------------------------------------------------------
-------------[Server] Example message.

**Comment by Ryuiijin** [comment]
Thank you for information. =) I tested it with bansharp's free version and it doesn't work actually. You are totally right.
