### ISSUE TITLE
Could you import a really good lee Addon?

### ISSUE THREAD

**Issue by Figueira216** [berbb/PortAIO#447]
All the lee addons are just too bad right now... Iwant some addon like moony's one that was a good addon

**Comment by berbb** [comment]
Not all addons ported from L# will be exactly like L#. Instead of requesting addons and saying the others are bad how about reporting the issues on the others?

**Comment by Figueira216** [comment]
Sorry! They are just missing too much q's, they were great but now they looks really bad

**Comment by NoobPolice** [comment]
Solution would be a good Predictioneer i suggested to create a OKTW Predictioneer its currently the best

**Comment by berbb** [comment]
@NoobPolice Done.
