### ISSUE TITLE
Eltristana nat using abiltities

### ISSUE THREAD

**Issue by xxbattonxx** [berbb/PortAIO#449]
hello i played trist yesterday on eltristana port just fine worked amazingly loved it got on today tried to play her ap mid just for fun and none of the abilities casted ever i dont know if its one time thing or what going to play some more soon tried refreshing elo buddy tried re injecting it still just would not cast any thing sorry i cant really give any more info im not to savy with scripting yet tried giving as much as i could. orb wallker would just auto attack when switching from clear to combo etc....

**Comment by xxbattonxx** [comment]
also in adition oktwaio ashe is doing same thing just played couple games was fine then bam today its not casting abilities had to switch to another port

**Comment by berbb** [comment]
This isn't a PortAIO problem. It doesn't make sense for it to work one day and not the other. I can't do anything about this because its all working fine like you said but it doesn't work in some games.

You can try clearing EBs appdata.
