### ISSUE TITLE
Can we have new Karthus ?

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#451]
Currently is OKTW but it too shabby , like simple Aimbot addon because it don't have any specific thing in it for Karthus .

im still using KarthusSharp i think it will be awesome if it in PortAIO , thanks !  

Also now there's one SDK RARE Karthus on L , but seems buggy after i tried it couple games .

**Comment by Muse30** [comment]
yeah I actually ported the rare karthus but it was completely broken.. I'll port karthusharp

**Comment by Luc4z** [comment]
@Muse30 counting on you senpai !

**Comment by Muse30** [comment]
@Luc4z already ported KarthusSharp xD
