### ISSUE TITLE
yasuo not using w

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#452]
tried all yasuo addons, they aren't using w to dodge spells. checked all settings + cleared appdata
https://s32.postimg.org/xilql0u2t/Screenshot_40.png

**Comment by inphratiic** [comment]
played gosumechanics today and it was working pretty good

**Comment by berbb** [comment]
They're all using it fine. For Gosu Mechanics you just need to change the danger level and it will work fine.
