### ISSUE TITLE
Lissandra

### ISSUE THREAD

**Issue by Muse30** [berbb/PortAIO#46]
can you check lissandra again? looks like is still not using any skills

 console : http://prntscr.com/aysvk5

**Comment by berbb** [comment]
Fixed the console error but it had nothing to do with stopping the skills from being used. Update and try again.

**Comment by Muse30** [comment]
:sob: looks like it is still not using any spells wut

**Comment by berbb** [comment]
Not sure, it's using spells for me. Can anyone else confirm this?

**Comment by Muse30** [comment]
really weird maybe is just me idk... killsteal is also working but the problem is when I press spacebar,C,X,V it doent do anything

**Comment by berbb** [comment]
@Muse30 What other addons are you using so I can try to reproduce it?

**Comment by Muse30** [comment]
none only portAIO ... I  also disabled utility .. only having problems with liss :question:

**Comment by KiriharaSenpai** [comment]
lemme try it gonna do feedback gimme 5 minutes

**Comment by KiriharaSenpai** [comment]
tried works awesome

**Comment by Muse30** [comment]
Rip  XD gonna reinstall eb I guess  Kappa

**Comment by KiriharaSenpai** [comment]
just clear ur appdata dude

**Comment by Muse30** [comment]
already done that but the problem is still there.. anyways close this as I am the only one with the problem xD
