### ISSUE TITLE
YasuoSharp2

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#463]
Ult does not fire under specified conditions

Smartult
Ult @ 2
E to safe
R when land

1,2,4 none worked automatically in Combo or otherwise

Worked fine manually

**Comment by berbb** [comment]
I think you mean YasuoSharpv2 haha. I'll check it out.

**Comment by lgndz** [comment]
Thanks, sorry Ill edit

**Comment by berbb** [comment]
Fixed.
