### ISSUE TITLE
Hi, everything loads in portaio BUT THE CHAMPION SCRIPT

### ISSUE THREAD

**Issue by dome661** [berbb/PortAIO#465]
Everything loads like it should, But the champion script doesn't.

**Comment by berbb** [comment]
Which champion?

**Comment by dome661** [comment]
yes, all. It worked fine before, but just really recently doesn't work.

**Comment by berbb** [comment]
In the PortAIO Misc menu do you have Util only mode checked?

**Comment by dome661** [comment]
nvm works in custom, gonna tr
