### ISSUE TITLE
Please read it berb and Muse30

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#476]
I think if the port LeagueSharp SDKEx library code may make the SDK script has a lot to improve the performance
Maybe you should try, it's just my personal guess, I don't know whether to do so will work
I don't know whether EB have this library to the corresponding API code
Maybe I was wrong
But dry your project is very beautiful XD

**Comment by Muse30** [comment]
what @dankmemer420 said

**Comment by lyn690697457** [comment]
I'm sorry I didn't take a closer look at the library files。
