### ISSUE TITLE
Best prediction 

### ISSUE THREAD

**Issue by yashine59fr** [berbb/PortAIO#478]
Hey i played thresh with thresh the ruler wich use 2 L# prediction 
Is it possible to use it with other champions ??

**Comment by Monnq** [comment]
I guess it's about time for a L# Predictioner ( ͡° ͜ʖ ͡°)

/summon @berbb

**Comment by NoobPolice** [comment]
OKTW works fine...

**Comment by berbb** [comment]
Yeah sure why not.

**Comment by berbb** [comment]
Added. Both L# prediction methods are under a predictioner now.
