### ISSUE TITLE
Cant load Utility??

### ISSUE THREAD

**Issue by toannatkm0** [berbb/PortAIO#48]
Cant load Utility??

**Comment by NentoR** [comment]
Yes same here no loading utilities

**Comment by ronniejacks** [comment]
same here

**Comment by Mercin10** [comment]
Hope Berb will fix this soon. I love L# Evade

**Comment by lyn690697457** [comment]
https://github.com/kyn9x/evade/tree/master/Evade  L# EVade

**Comment by lyn690697457** [comment]
This is a separate port

**Comment by xGoldenS** [comment]
I dont know why berbb disable load utility.
Follow me to temp fix.
Go to APPDATA folder from loader.
Open Repositories folder and find PortAIO folder (my folder is 5F4CB821)
Open file Init.cs with Notepad or notepad++ and find //LoadUtility();
Remove // and save.
Back to loader, Recompile PortAIO.
