### ISSUE TITLE
Not responding?

### ISSUE THREAD

**Issue by Admireeee** [berbb/PortAIO#486]
Whenever i'm playing a game no matter what champ script i get not responding..
when i die
90% of the time
ezvade
nabbtracker
activator#
EB predict
and recall tracker

**Comment by berbb** [comment]
Are you playing in borderless?

**Comment by Admireeee** [comment]
yes i am playing borderless
i think it may be i'm manually using summoners?

**Comment by berbb** [comment]
That shouldn't be an issue. Have you tried clearing your app data?

**Comment by Admireeee** [comment]
Will try it now

**Comment by Admireeee** [comment]
working thanks
