### ISSUE TITLE
NabbActivator exhaust summoner usage

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#488]
So i'll try to explain this issue the best i can, Nabbactivor seems to override all manual input when trying to get the exhaust, like when u running away from their team it will walk right up to them to use the exhaust on someone and even if u manual click to get back it just starts to go back and front like a complete retard, no console errors. This doesn't happen every single time but happens like 2-3 times every game

**Comment by berbb** [comment]
Fixed.
