### ISSUE TITLE
ValvraveSharp Lee Sin Crashing 

### ISSUE THREAD

**Issue by iNubbish** [berbb/PortAIO#49]
Champion - Lee Sin
Dual Port - ValvraveSharp
Issue - Crashing during Combo, always when ganking a lane, happened in 3 games before switching to El Lee. Tends to happen pre 20 minutes into the game, sometimes stabilizes after 20 or so minutes into game.
List of Addons enabled - PortAIO, berb.common, LittleHumanizer, SmiteGH, and EzEvade.

**Comment by dankmemer420** [comment]
This is a known issue, read the to-do before making an issue.
