### ISSUE TITLE
Crash Teemo

### ISSUE THREAD

**Issue by Shazelol** [berbb/PortAIO#490]
Crash with Sharpshooter Teemo with against kha'zix when he use hydra and W, E, Q (ignite and corruption potion, active in me) crashes any time.
Edit1: Sharpshooter Teemo two weeks ago, a good logic combo(no R in chasing)

**Comment by berbb** [comment]
There shouldn't be any crashing but it might be because the script tries to anti-gapclose when Kha'Zix jumps. I pushed a fix that should fix this.
