### ISSUE TITLE
OKTW Thresh

### ISSUE THREAD

**Issue by meowmeow1234** [berbb/PortAIO#494]
How to best thresh settings ?

**Comment by Muse30** [comment]
default settings are the best probably

**Comment by meowmeow1234** [comment]
Okay bro and i press e pull,push key but dont walking u can fix it?

**Comment by Muse30** [comment]
yes 1 sec

**Comment by Muse30** [comment]
done, update again

**Comment by meowmeow1234** [comment]
thank u bro
