### ISSUE TITLE
Janna

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO#496]
Janna FreshBooster
Is show error in Chat , and the LCS Janna for me dont is working engage cancel

**Comment by berbb** [comment]
Screenshot of the error?

**Comment by LindsNemesis** [comment]
wait

**Comment by LindsNemesis** [comment]
okay that match my dont is showing more but i remember show in chat FREESBOOTER DONT IS LOADED with a code error number

**Comment by berbb** [comment]
The freshbooster error was probably only a one time thing. And LCS Janna's E is working on engage. It only works for Lucian, Graves, Vayne, Corki, Ekko, Caitlyn, Gnar, Fiora, Kass, Fizz, Riven and Kindred.

**Comment by inphratiic** [comment]
@berbb could u had every single adc to that list pls ?

**Comment by berbb** [comment]
Not every ADC has an engage spell though. There's no other way to determine when someone is going to engage so it only E's on spells like Vayne Q, Lucian E, Corki W, Caitlyn E etc.
