### ISSUE TITLE
[Suggestion] Port Nechrito Thresh

### ISSUE THREAD

**Issue by Monnq** [berbb/PortAIO#497]
We already have some addons for Thresh, why not 1 more ( ͡° ͜ʖ ͡°)

https://github.com/Nechrito/Leaguesharp/tree/master/Dark%20Star%20Thresh

**Comment by inphratiic** [comment]
already ported ^^

**Comment by Monnq** [comment]
holy fuck, they are fast

**Comment by Monnq** [comment]
Well I guess it's kinda broken, I get 5-10 fps, then game freezes :s

**Comment by berbb** [comment]
Fixed.
