### ISSUE TITLE
Make an Ezevade's Dodge only dangerous key from hold active to toggle

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#499]
Line 123 and 124 from Core/Evade.cs shoud be this:
                keyMenu.Add("DodgeDangerousKey", new KeyBind("Dodge Only Dangerous Key (On Hold)", false, KeyBind.BindTypes.HoldActive, 32));
                keyMenu.Add("DodgeDangerousKey2", new KeyBind("Dodge Only Dangerous Key (Toggle)", false, KeyBind.BindTypes.PressToggle, 'Z'));

**Comment by Muse30** [comment]
fixed
