### ISSUE TITLE
LoL Crashing, No apparent reason

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#5]
**Champion Name (eg. Ahri) / Utility (eg. Evade) :** portAIO (EzEvade, ElUtility Suite)

**If this is an issue about a champion, is this Champion dual-port supported (Check via PortAIO Misc)? If yes which one? :** Ashe (OKTW w/ CommonPred, Necherito)

**Issue/Problems (Try to be as detailed as possible) :** LoL.exe crashes out reliably. Went down to bare minimum and still crashing. Crashes when standing still in base as well, requiring no input from player to crash out

Possibly an issue with the port of Ashe? There doesnt exist OKTW Ashe or Necherito ASHE in your Dual Port Section. 

Also I don't have an option to add a label, sorry.

**Comment by lgndz** [comment]
http://imgur.com/olTJ0JU

Proof no label ability while making issues =/

**Comment by berbb** [comment]
Is it just Ashe?

**Comment by lgndz** [comment]
I will get a screenshot when I am home on lunch. I only tested with Ashe this AM. I already cleared the repo folder and reinstalled the add on earlier as well. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 19, 2016 at 6:48 AM -0700, "berbb" <notifications@github.com> wrote:












Is it just Ashe?

**Comment by lgndz** [comment]
Confirmed not just Ashe.

Loaded up Graves and Sivir, all three crash. All test variables are same.

**Comment by Shazelol** [comment]
For me I don't lol.exe crash. I test ashe OKTW. Test again.

**Comment by lgndz** [comment]
I'm going to completely remove everything and reinstall so I'll report back

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 19, 2016 at 12:39 PM -0700, "Shazelol" <notifications@github.com> wrote:












For me I don't lol.exe crash. I test ashe OKTW. Test again.

**Comment by lgndz** [comment]
Hmm, not sure what the deal is but the second full reinstall fixed the issues seemingly.

Thanks for your time!
