### ISSUE TITLE
Utitlies are all amazing .

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#5]
Yasuo Flee mode wont stack Q and lane cleaning wont use it either .

btw can you please put the list back so we can know what we're using ? thanks !

**Comment by berbb** [comment]
I completely deleted the list, I'm not sure if I can get it back. Yasuo laneclearing is horrible right now, people on L# are experiencing it also, just gotta wait for Brian to fix it. I'll check out flee.

**Comment by Luc4z** [comment]
thank you  ! i have to mention again those Utilities you brought us are really amazing .

**Comment by Luc4z** [comment]
i tested god jungle timer with my friend and seems it doesnt work now

**Comment by berbb** [comment]
God Jungle Timer doesn't work on # either. I'll disable it from the AIO.
