### ISSUE TITLE
Crashes (Orianna and Crank)

### ISSUE THREAD

**Issue by Wariacik** [berbb/PortAIO#50]
1. If u choose 6th skin as Orianna game crashes.
2. Game crashes after respawn when playing crank and having "focus camera on respawn (or sth like this)" option on.

**Comment by berbb** [comment]
Just tried with Blitcrank and didn't crash. Turned this option : http://i.imgur.com/DVwFBPn.png - On, then died, Off, then died and nothing happened. Checking Ori right now.

**Comment by berbb** [comment]
Can't reproduce on Ori either, http://i.imgur.com/oMDwi6B.png . Do you play on fullscreen or boderless?

**Comment by iiChopper** [comment]
Had crashes on Ahri too :(

**Comment by berbb** [comment]
@iiChopper Mine is off also and I'm not experiencing any crashes.

**Comment by iiChopper** [comment]
Alright, thanks. i'll keep trying other champions. btw, i am using EvadeIC maybe thats the problem?

**Comment by berbb** [comment]
@iiChopper Maybe, try experimenting.

**Comment by iiChopper** [comment]
@berbb Still playing without crashes. I just had to remove the EvadeIC

**Comment by rpgfreak128** [comment]
@berbb Hey i am also crashing i noticed it only happens when i respawn after dying. But i have only used urgot and he has the stack tear  option on and i feel like that might be causing it.

**Comment by berbb** [comment]
@rpgfreak128 It's not that, it's been happening to other champions also but only to some people.

**Comment by rpgfreak128** [comment]
@berbb alright ill try and mess around for a fox i have windows 10 maybe thats an issue who knows

**Comment by rpgfreak128** [comment]
@berbb okay so its not a fix but it works if you Tab out when you die then you dont crash at rewspawn
