### ISSUE TITLE
Caitlyn - OKTW

### ISSUE THREAD

**Issue by Jhon525** [berbb/PortAIO#505]
Is Crashing for me.

**Comment by berbb** [comment]
Okay?... When? Fighting who? What mode did you crash? Combo, harass, lane clear... Give me a bit  more information please!

**Comment by Jhon525** [comment]
When caitlyn uses the W in dash ending position while I'm in combo mode (Srry for bad english i use google translate)

**Comment by berbb** [comment]
I understood that perfectly. Thanks, I'll try to fix it.

**Comment by berbb** [comment]
Should be fixed.
