### ISSUE TITLE
ExorAIO ezreal

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#509]
Seems like the anti-grab feature is not working

**Comment by berbb** [comment]
Testing this is very weird. Here's the debug message : 
http://image.prntscr.com/image/74ed63c92cf74cd39e483597198776cf.png

1 = Buff Gain Is Called
2 = The conditions are meet
3 (highlighted red) = Cast E now

But whenever 3 was displayed on the debug console Ezreal never E'd. I'm not sure how the original ExorAIO dodges it. There's a VERY slim chance that L#'s core is just simply faster than EB's so it gets the call earlier. Or there's also the chance that this was patched. 

Anyways, I wasn't able to fix this, it's either patched or there's a delay in EB's core. It's best to just use an evade and enable Ezreal's E in Evade Spells.

**Comment by inphratiic** [comment]
NP man, i can actually use it manually against the blitz hook, i just wanted to see if it worked yesterday and it didn't, either way u might want to disable it then so that people don't really count on it :)
