### ISSUE TITLE
Question 2: Best Selector?

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#51]
What would you guys recommend as the best option to choose for the selector? Manual? It's really easy understand who to go for but I despise it when it switches target from at 10hp Support to the ADC who is full HP, haha.

**Comment by GreatWhite181** [comment]
Mine works perfect as is. I would suggest clearing your Elobuddy folder in appdata. Unfortunately this will reset all your settings but this should fix any issues you have been having such as spells not casting, target selector, etc.

**Comment by hardique** [comment]
@GreatWhite181 u have AUTO mode selected in target selector?

**Comment by GreatWhite181** [comment]
@hardique Yep
