### ISSUE TITLE
Can port Yasuo - The Windwalker

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#51]
The script comes from bol, I do not know if you can port.
I'm sorry to trouble you, but I believe a lot of people used it should。

**Comment by Muse30** [comment]
its encrypted

**Comment by lyn690697457** [comment]
I'm sorry he encryption as server validation

**Comment by berbb** [comment]
As @Muse30 said, it's encrypted. But even if I was able to decrypt, it porting decrypted LUA to C# will be extremely difficult probably even impossible.
