### ISSUE TITLE
Smite in Elutiliysuite

### ISSUE THREAD

**Issue by GodForm** [berbb/PortAIO#510]
Smite seems working fine but is not working to use ''in combo'' (didnt tested the Ks with smite)
Also can you add an option or just make the activator to use hydra (tiamat, titanic) after a basic attack or after an ability? 
Because when pressing Combo Key it uses hydra instantly without any reset of basic attack and for exemple with shaco i use my Q to get invisble, im going to do a combo in my enemy but because hydra is in range it will use hydra before i basic attack my enemy and take me out of stealth

**Comment by IlikeBaconLol** [comment]
good idea yh

**Comment by berbb** [comment]
Smite Combo only works if you have red smite. And yeah, I can do add the option to do that, which Activator are you using so I can prioritize that first?

**Comment by IlikeBaconLol** [comment]
Elutility for me

**Comment by GodForm** [comment]
Hey berbb im using the one that i talked about (Elutiliysuite) and i tried with the red smite and didn't worked atleats for me, i remeber using before with jax and worked but i dont think it stills working

**Comment by lightduy94** [comment]
@GodForm i think that you have "Safe 1 smite" is enabled and you have only 1 smite

**Comment by berbb** [comment]
Done.
