### ISSUE TITLE
For Me

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#511]
http://plays.tv/video/577f3f319d369944e6/graves-trick-explained

- Try to do this Berb, it looks cool.

Kappa

**Comment by berbb** [comment]
Okay Berb.

:+1: 

Kappa

**Comment by SidaRevamped** [comment]
WTF

**Comment by IlikeBaconLol** [comment]
HU3

**Comment by Shazelol** [comment]
Now, I'm scared :/

**Comment by lyn690697457** [comment]
XD
