### ISSUE TITLE
ElLee Min Stacks & Insec

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#512]
On the combo menu you can only set the min stacks for passive to 1/2 or 2/2 since the slider doesn't go to 0. Also Insec doesn't work at all.

**Comment by lightduy94** [comment]
You can uncheck "Use Passive" or something like that (i don't remember exactly) and it will not care about passive stack

**Comment by berbb** [comment]
As ^^ said, unchecking "Wait for Passive" should disable the slider and not use it at all. The insec is working fine with EB's orb, I haven't tried it with L#'s yet.
