### ISSUE TITLE
Kurisu Nidalee

### ISSUE THREAD

**Issue by Wa1L** [berbb/PortAIO#513]
Kurisu Nidalee Rarely uses Q , and misses even immobile targets :/ got flamed hard lol

**Comment by Lemonadez** [comment]
Change prediction?

**Comment by GodForm** [comment]
In the menu go to the setting of the skill (javelin toss) and turn off the box ''check hitchange''
it kinda worked for me, try out :)

**Comment by berbb** [comment]
Use a predictioner thats the only way to solve this, if you're using the new Orbwalker don't unless you're in for some bugs.
