### ISSUE TITLE
Feature with anivia for E faster lvl 6

### ISSUE THREAD

**Issue by yashine59fr** [berbb/PortAIO#516]
with Anivia can you add a feature for E before R if the R is ready and in range

**Comment by berbb** [comment]
That would be a misplay. If you miss your Q then you're E'ing a target that isn't chilled which does less damage.

**Comment by dankmemer420** [comment]
On anivia u can e > r and make them chilled before the projectile lands.

**Comment by berbb** [comment]
Oh, he didn't explain it like that. I'll see what I can do.

**Comment by yashine59fr** [comment]
sorry for my englendo xD
