### ISSUE TITLE
Kalista E calculations

### ISSUE THREAD

**Issue by xxbattonxx** [berbb/PortAIO#52]
hello sorry to trouble you but kalistas e calculation ar of by just a bit ive tried all the different kalista ports all about off same amount they rend at like 95% instead of 100 so alot of timmes it misses kills and objectives like drag and baron. thank you

**Comment by Lemonadez** [comment]
Check overkill..there should be always an option like to prevent you from being a scripter. Kalista is insta ban 100% Accuracy of "E" perfect kill always ban after a week :).

**Comment by berbb** [comment]
As @Lemonadez said use Overkill check and set it too 80/300 (as another user recommended).

**Comment by xxbattonxx** [comment]
ok thank you that would explain the ban on my other accnt thanks
