### ISSUE TITLE
Ezreal

### ISSUE THREAD

**Issue by Jokiblack** [berbb/PortAIO#52]
R bad work, fail all and dont use on dragon or baron

**Comment by berbb** [comment]
Have you tried changing the prediction? Also, I want you to know that you can use the manual key to shoot at the target.

**Comment by Jokiblack** [comment]
Change predicion? what you recommend?

**Comment by berbb** [comment]
Try OKTW, and just mess around with it.

**Comment by Jokiblack** [comment]
OKTW predicion have very big spam in console.. no desactive?

**Comment by berbb** [comment]
The spam in the console doesn't effect the performance lmao
