### ISSUE TITLE
Trynda / Kayle Ult and some suggestions

### ISSUE THREAD

**Issue by TehEbil** [berbb/PortAIO#522]
Hey,
at first: you guys doing an awesome job. But you should add an humanizer. I am using one, it blocked about 5.000 clicks of ryze, which means - others would have been banned with such inhuman number of clicks.

What about an improvement of the EB TS? With vayne for example, it's attacking the nearest or some other champion although I marked someone (and no, he does not got 2 stacks).

I wanted to ask you if you're able to add a perfect tryndamere / kayle ult. I don't mean the one which checks if you got 5% health or lower, but one which calculates incoming damage (if you would die) and uses it then to rescue urself. In addition, onBuffLose, it should use Q / heal / cleanse or whatever kayle heal+ms.

I played a bit with that and figured out, that you need:
            Obj_AI_Base.OnProcessSpellCast += OnProcessSpellCast;
            Obj_AI_Base.OnBuffLose += OnBuffLose;
            Obj_AI_Minion.OnBasicAttack += OnProcessSpellCast;
            Obj_AI_Turret.OnBasicAttack += OnProcessSpellCastTower;

All of those negation, because, in EB, OnProcessSpellCast does not involve miniondmg. I failed at calculating incoming tower dmg, the damage was wrong, so I tried to calculate it with the formula:

            var towerDamage = sender.BaseAttackDamage * (1 - (target.Armor*.7f / (100 + target.Armor*.7f)))
            if (TowerIsOuter(sender))
                towerDamage = towerDamage * (1 + 0.375f * WarmingUpStacks + 0.25f * HeatedUpStacks);
            else if (TowerIsInhib(sender))
                towerDamage = towerDamage * (1 + 0.0105f * HeatStacks);

but damage was always wrong then being printed. the next problem is, that one needs to involce dmg distance, e.g. u're getting a tower hit when you're going back and then it follows through the whole map and the script thinks: oh, incoming damage somewhen, activate ult, but, if nexus would not heal, you'd be dead because ur ult only lasts 2-3/6 seconds and tower from mid to nexus needs a bit longer I think (it's just an example, but could happen with other damages, too)

Thank you for your time :)

**Comment by Muse30** [comment]
I cant read everything right now but the first thing that you mention EB TargetSelector, we cant do anything about that, thats on EB so you can report that there.

**Comment by berbb** [comment]
1st : PortAIO comes with 2 humanizers, it's the users choice to use it or not.

2nd : EloBuddy's TargetSelector can't be improved based on the fact that it's closed source and I'm not about to fully control what the Orbwalker hits (which is why I'm trying to port the orbwalker/TS from L# so I can edit it to my will)

3rd : Perfect Tryndamere and Kayle ults wouldn't be too hard if I was using EB's HealthPrediction methods, I'll check that out soon.

**Comment by kirabc** [comment]
@berbb for tryndamere and kayle i think you can copy from elzilean is pretty good =p

**Comment by berbb** [comment]
Pushed an ult logic on kayle. Tryndamere already had that logic. It uses health calcuations that also calculates ping, it's pretty good, comes from EBs orb.
