### ISSUE TITLE
Just test Hoola Riven

### ISSUE THREAD

**Issue by Demisemo** [berbb/PortAIO#523]
Not seem like come Champion

**Comment by Muse30** [comment]
whaT?

**Comment by Demisemo** [comment]
Even strokes Do not use the skills QWE

**Comment by berbb** [comment]
Working fine.

**Comment by Demisemo** [comment]
@berbb 

What is your anticipation ranking

EB、SDK、OKTW、SP、L# order


test:Clear line OK、Heroes do not fight to use the skills 

My question?

**Comment by berbb** [comment]
You need to change the keybinds in the L# Orbwalker, the script said to do so. The scripts combo key is on X, change it to space.

EB > OKTW > SDK > SPred > L#, but they all work decently well don't get me wrong.

**Comment by Demisemo** [comment]
Understand , and I know why he is not using the default COME X
