### ISSUE TITLE
GosuMechanics_Yasuo upgrade logic @Berb@SidaRevamped@Muse30

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#528]
portaio gosu Yasuo Harass not Use E
Maybe you can try to use his logical port
Add TargetSelector and Mode There Orb Walking etc...
Maybe this would further enhance the performance of the script
This is the URL
https://github.com/wearegodz/WeAreGodz/tree/master/GosuMechanics_Yasuo/GosuMechanics_Yasuo

**Comment by lyn690697457** [comment]
I look at his code, the code can be worth a lot of copy

**Comment by SidaRevamped** [comment]
yeah but why you want harass with E? just use Combo Key when you want go in with E

**Comment by Muse30** [comment]
like @SidaRevamped said you can use combo for E , there is no point on using E on harass tbh
