### ISSUE TITLE
minor issue but appreciation also

### ISSUE THREAD

**Issue by nightsole** [berbb/PortAIO#53]
I appreciate all ur work , im not a coder i just registered to commend you on ur work , been followin you  since nulled days , im not kissing your ass im just admiring your port and the hard work you put on to let people enjoy things for free , keep up the good work , also you might wanna take a look at shen i played him and cs with Q is kinda bad, that's all and really thanks.

**Comment by Muse30** [comment]
what is "kinda bad"

**Comment by saladinaazir** [comment]
Adding on to this, akali can't use q to lasthit, but I'm guessing both of these problems are caused by the L# devs themselves.

**Comment by nightsole** [comment]
^
this , q last hit sometimes ignores minions, when it doesnt wave clear misses minions sometimes shen just runs around, rest is good

**Comment by saladinaazir** [comment]
as far as I can tell it just isnt used to lasthit, it is used in waveclear, but just randomly. The lasthitting code just isn't there. I imagine its pretty diffucult to code, as the q travel time is insane and deals very low damage.
