### ISSUE TITLE
Kayle Problem

### ISSUE THREAD

**Issue by Hidan123** [berbb/PortAIO#53]
Yo berb back at it again with the new problem ^^
Kayle is not casting any spells in combo

**Comment by berbb** [comment]
Thanks, will work on it.

**Comment by berbb** [comment]
Just tested and she's using spells.

**Comment by Hidan123** [comment]
Uh then maybe i have something wrong .. for me its just aa ^^

**Comment by berbb** [comment]
Try clearing appdata.

**Comment by hardique** [comment]
@berbb as somebody said,u should add clearing appdata in readme.txt
it will reduce the number of issue topics
