### ISSUE TITLE
ahri# feature request

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#530]
could u possibly add a distance slider for ahri charm? Because i'm playing ahri adc and i want the script to save the charm to when people are sitting right in my face ^^
PS: @berbb u have to try ahri adc, if u survive the early game u carry the game easily
PS2: a feature to save mana for ultimate would be awesome too ^^

**Comment by berbb** [comment]
To break it down : 
1. Add a distance slider to use charm.
2. Add a feature that saves mana for ult.

Got it.

**Comment by berbb** [comment]
Done.

**Comment by inphratiic** [comment]
@berbb gj, but what i was actually asking for the distance slider was a max distance slider, like it would only charm if the target is closer then 400 units for example, and u implemented a minimum distance slider ^^

**Comment by berbb** [comment]
woops, will change it soon.

**Comment by berbb** [comment]
Fixed.
