### ISSUE TITLE
Red Smite ElUtilitySuite

### ISSUE THREAD

**Issue by GodForm** [berbb/PortAIO#531]
Red smite on combo not working for me, tryed all the settings, even with ''save 1 smite charge'' off

**Comment by GodForm** [comment]
hey berb, also shaco addon from ''UnderatedAIO'' have a glitch, in combo with ''block spells in stealth'' when im going to use the combo that should be: Q(invisible) - Basic - Hydra - E or E - Hydra, shaco cancels the basic animation and does E (because it got visible doing the animation)
i also tested Muse30 shaco addon that both look similiar and this glitch dont happen, but this one have draws and the other one not, can you make like a fusion of both or something like that, and fix the error?

**Comment by berbb** [comment]
I'll check out the red smite, but I'm not sure about the shaco canceling the auto attack, I don't think that has anything to do with PortAIO unless you're using L# Orbwalker.

**Comment by GodForm** [comment]
Im not using L# Orbwalker, when i use shaco from Muse30 (that looks almost the same but without draws) it does the combo right, but with this one with ''block spells in stealth'' it should do a basic attack (to get out of stealth) and then continue the combo normally with hydra and E, the problem is that it cancels the animation of that first auto attack and then it does the E straight away without even finished the basic attack so it only deals the damage of the E, the problem is that shaco should finish that first basic attack, thats all

**Comment by berbb** [comment]
Fixed both.
