### ISSUE TITLE
Challanger Irelia not able to Use R in Combo

### ISSUE THREAD

**Issue by NoobPolice** [berbb/PortAIO#535]
The Toogle U for R in Combo usage disapear after i pressed the Key.
it doent stay enabled.

And somehow cant use manually

**Comment by berbb** [comment]
The hotkey for ult is like a semi-manual Xerath ult. Every time you hit it it will use an R stack. The hotkey is the only way to ult, stupid I know but thats how it is on the original script and I guess people actually use it that way. I would try binding that keybind to combo so it would use R when combo.
