### ISSUE TITLE
(Suggestion) Quinn Combo Tweak

### ISSUE THREAD

**Issue by iNubbish** [berbb/PortAIO#54]
Can you make it if the target she's going to combo, check if they're marked with her valor. And instead of automatically E'ing her target, auto attack them, then continue on with the basic combo (E, remarking them, autoattacking to proc the mark, then q'ing for another mark and autoattacking to proc the mark.). 

It'll do much more damage in trades and just in general, since it's doing a total of 3 marks with the combo checking for the already marked target instead of excluding the check and only doing 2.

**Comment by Muse30** [comment]
I ported this for EB some time ago and if I remember correctly it does check for the mark but yeah the rest are good suggestions

**Comment by iNubbish** [comment]
For me, it just went and did the basic combo regardless if the target was marked or not.

**Comment by iNubbish** [comment]
Sorry, the explanation at the top of this thread is kind of confusing. Before doing the combo on a target, check if the target has a mark, and auto attack to proc the mark before the combo. It'll allow extra damage to be done and not overlooked.

**Comment by berbb** [comment]
And if the target doesn't have the mark?

**Comment by iNubbish** [comment]
Just continue on with the combo. The check is simply to get out the most damage possible.

**Comment by Muse30** [comment]
he is talking about OnPreAttack to use AA first when the enemy is marked instead of E or Q right away..

I did it here : https://github.com/Muse30/quinsfs/blob/master/Program.cs (is the same addon ported for eb)

**Comment by iNubbish** [comment]
@Muse30 Thank you, not exactly a coder...

**Comment by berbb** [comment]
The code is pretty much the same, if it's working for yours it should work on mine. But, I'll do something  else so it does what you say.

**Comment by iNubbish** [comment]
The addon itself is wonderful, if the suggestion won't go through then don't force it too. I doubt you will, but I just wanna like say like "DO IT AND MAKE IT BETTER"

Your addon, your diddly do rules <3.

**Comment by Muse30** [comment]
ups it was this part : https://github.com/Muse30/quinsfs/blob/master/Program.cs#L178 it doenst have the mark check but you are the expert here  xD I didnt know what I was doing but that worked

**Comment by berbb** [comment]
@iNubbish If only everyone had your mindset I would've released PortAIO a long time ago. I appreciate it, I'll get it done :)

**Comment by berbb** [comment]
@iNubbish One more thing, if Quinn is in Valor Form should it proceed to go back to Quinn and start off by auto'ing to proc the mark? Or does it just start regularly by using E?

**Comment by iNubbish** [comment]
@berbb I greatly appreciate the work into AIO, and it's free. No point in just pestering you to my liking, especially since you're another human being. Not a minion. xD You had to go through so much bullshit and people that probably just thought you were a program that would produce a good service every now and again. I disagree with that, anyways. Enough like emotional shit <3 

Work this AIO to your liking berbb, I'll just be here to help with what I can :)

**Comment by iNubbish** [comment]
@berbb I feel like it should have a check of whether to do so, since it's much faster to do E, but some butthurt people might want it to auto the proc. If I had to choose, I'd say just start regularly by using E.

**Comment by berbb** [comment]
Alright, it's added, hopefully it does what your suggestion says :)
