### ISSUE TITLE
exor ryze

### ISSUE THREAD

**Issue by Sharpino** [berbb/PortAIO#54]
https://s32.postimg.org/bnti74o45/Screenshot_56.png

and can you fix minimap drawings?
https://s31.postimg.org/kgokkrxzf/2016_07_19_18_43_28.png

**Comment by goddamnguy** [comment]
it's happening on other champs too, for example ziggs

**Comment by berbb** [comment]
The first error can be ignored and the minimap drawings will be added a next time.
