### ISSUE TITLE
Sivir E Gapcloser

### ISSUE THREAD

**Issue by Pikachu7** [berbb/PortAIO#54]
always use all gapcloser. (ally team heros)
sorry my bad english

**Comment by Lemonadez** [comment]
Can you be more Specific? Cuz it never happen to me.

On my PORTAIO i only have Champion, Utility Suite checked.

Maybe You are using EzEvade too?

**Comment by Muse30** [comment]
I'll check

**Comment by Muse30** [comment]
should be fixed
