### ISSUE TITLE
SephKha'zix

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO#544]
Muse30 Or Berb 
In SephKha'zix if Harass Mode is active Hotkey(H)
Kha'zix Combo dont Work

And i think Kill Steal dont working too 
(I Think!, but the first problem is real

**Comment by LindsNemesis** [comment]
Another Issue
Sometimes Kha'zix use spells in WTF places
Like dont have enemies around him but he jump and use w

**Comment by berbb** [comment]
Combo is working perfectly fine. Just turn the harass key off.

- Fixed using random spells.
