### ISSUE TITLE
OKTW Jinx Q switch in Combo

### ISSUE THREAD

**Issue by Sterioss** [berbb/PortAIO#548]
While holding Combo, Jinx does'nt switch between Gun and Rocket like OKTW does with L# (Gun while in range and Rocket as soon as Out of AA range). It basictly stays in the actual Q mode.

**Comment by berbb** [comment]
Fixed. Just don't use L#'s orbwalker, it doesn't work well at all with OKTW Jinx. But when I port the orbwalker in for every champion it should work fine.
