### ISSUE TITLE
AutoJungle and SFXUtility

### ISSUE THREAD

**Issue by Sterioss** [berbb/PortAIO#549]
Best Jungle Bot out-there !
Soresu AutoJungle : https://github.com/Soresu/LeagueSharp.BOT

Heavy Assembly but would love to see it translated :)
SFXUtility : https://github.com/xQxCPMxQx/LeagueSharp2/tree/master/SFXUtility

**Comment by berbb** [comment]
We're not doing auto-play for a while.

And SFXUtility seems like a time tedious project, will add it to the to-do list though.
