### ISSUE TITLE
(Issue) Kalista freezing the game on hard cc?

### ISSUE THREAD

**Issue by iNubbish** [berbb/PortAIO#55]
Played a game of Ranked as Kalista, and whenever I got hooked by Blizcrank it froze the game. Forcing me to just go to Task Manager and just end task. I'll try to recreate it so I can show the errors in console, but just a little issue here until I can actually get time in my day to recreate the issue.

**Comment by iNubbish** [comment]
iKalista:Rework

**Comment by berbb** [comment]
Wasn't able to reproduce it, did you have QSS? Were you level 6 or higher when you were pulled? You may not recall this but did you have balista enabled?

**Comment by iNubbish** [comment]
Didn't have QSS or was 6, since it was during laning phase and switched to another addon after 2 crashes. I had all default settings. I didn't edit a single thing in iKalista.

**Comment by berbb** [comment]
Yeah, I'm not sure about this. I need someone else to confirm this if happening.

**Comment by iNubbish** [comment]
Hopefully it isn't just a hard cc problem, probably another thing triggering it. I'll try poking around for it.

**Comment by fatihcoskun27** [comment]
Yes, it is freezing game.

**Comment by fatihcoskun27** [comment]
I'm not sure that CC is doing this, but freezing is happening. My friend disconnected from the game for like 10 times when he was playing Kalista with this.

**Comment by berbb** [comment]
@fatihcoskun27 Was he using the same Kalista as @iNubbish

**Comment by Xelamats** [comment]
I don't see how you guys are DCing or anything with her. I've been maining her on my account that I've been leveling. Have 5 games so far with mass cc on me, blitz pull into ahri e and morgana stun, etc. and no crash yet. It's perfect for me honestly.

**Comment by iNubbish** [comment]
So far, it's been a one trick wonder sort of freeze. I haven't been able to recreate it in 10 games.
FeelsUnsucessfulMan. Hopefully, it doesn't happen again. Still, it's a tad bit scury that it might happen occasionally.

**Comment by berbb** [comment]
That's good news, let's hope it doesn't happen again.
