### ISSUE TITLE
OKTW/Genesis Jinx R Calculation

### ISSUE THREAD

**Issue by HDown-idk** [berbb/PortAIO#550]
After Ult enemies is still have 50-100 hp. Same on OKTW Graves R, but not always.

**Comment by yashine59fr** [comment]
because they heal or shield

**Comment by HDown-idk** [comment]
Nope. 
it would be seen.

**Comment by berbb** [comment]
The calucations should be a lot more accurate now.

**Comment by HDown-idk** [comment]
Thanks for all
