### ISSUE TITLE
RandomUlt

### ISSUE THREAD

**Issue by HDown-idk** [berbb/PortAIO#551]
I am extremely glad that you decided to port RandomUlt because BaseUlt = instareport. But within a week I did not see any Ult at recall. Also dont show the draw at recall position. Hitchance standart 3/5.

**Comment by berbb** [comment]
Packets are disabled @ EB, unfortunately I can't do anything about it.

**Comment by HDown-idk** [comment]
RandomUtt use packets for what? oO

**Comment by berbb** [comment]
Tracking recall? If I use the OnTeleport method then I may as well be rewriting the whole script.
