### ISSUE TITLE
ExorSIVIR Crash in lane clear

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#552]
ExorSivir
NabbTrack
ElUtil
Evade#
Custom OW

Was clearing lane mid with a Cassio and game crashed out

**Comment by lgndz** [comment]
gonna close because after I loaded back in I was fine rest of game. Weird

**Comment by berbb** [comment]
There was a large possibility that it was the OW. Thanks for reporting that it crashed when you had the OW enabled, it lets me know that the clearing crash is still around, thanks! :smile:

**Comment by lgndz** [comment]
Yea shit no prob. 
It's weird though because it happened in middle of game with nothing else going on - but not any time before or after that. 


Sent from Outlook Mobile, please excuse any errors or shorthand.




On Sun, Jul 10, 2016 at 6:34 AM -0400, "Berb" <notifications@github.com> wrote:












There was a large possibility that it was the OW. Thanks for reporting that it crashed when you had the OW enabled, it lets me know that the clearing crash is still around, thanks! 😄
