### ISSUE TITLE
vayne script

### ISSUE THREAD

**Issue by skipper744** [berbb/PortAIO#557]
what is best vayne script?

**Comment by Monnq** [comment]
vhr and challengerseries

**Comment by skipper744** [comment]
thanks,but when i use vhr have a lot of miss E

**Comment by Monnq** [comment]
Use VHR Revolution logic and use 50/55 value in slider "hitchance" or w/e it's called

**Comment by NoobPolice** [comment]
@Monnq  you mean 50/65 ? :D

**Comment by Monnq** [comment]
y
