### ISSUE TITLE
Hoola Riven Crashs upon Fast Harrase

### ISSUE THREAD

**Issue by NoobPolice** [berbb/PortAIO#561]
http://puu.sh/pXhqV/1a84233602.png

happend 3 times in a row

**Comment by NoobPolice** [comment]
worked fine 2 days ago ... costs me my Promo :'(

**Comment by NoobPolice** [comment]
Orbwalker is so ... delaying and not lasthitting proper .. pls revert all changes. its not good

**Comment by berbb** [comment]
That error has nothing to do with the crashes.
