### ISSUE TITLE
KurisuRiven

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO#562]
KurisuRiven sometimes stop using combo all spells and just walk

**Comment by LindsNemesis** [comment]
![image](https://cloud.githubusercontent.com/assets/19207560/16718061/576f7278-46f2-11e6-952a-81685628fa1b.png) 
![image](https://cloud.githubusercontent.com/assets/19207560/16718062/61f5718e-46f2-11e6-99a5-e36283f857b0.png) 
![image](https://cloud.githubusercontent.com/assets/19207560/16718065/6ae31c1a-46f2-11e6-89ae-b67cf79318d8.png)
![image](https://cloud.githubusercontent.com/assets/19207560/16718071/746747b6-46f2-11e6-955c-cd0259f374b3.png) giving alot execption ocurred too (that dont is all exepection )

**Comment by berbb** [comment]
Those console errors are irrelevant to Kurisu Riven. Are you using L# orbwalker?

**Comment by LindsNemesis** [comment]
Not Using the EB Orbwalker

**Comment by LindsNemesis** [comment]
Berb another issue i detected with EXORAIO with miss fortune
sometimes game freeze

**Comment by LindsNemesis** [comment]
And need close and reopen

**Comment by berbb** [comment]
Ported to L# Orbwalker.
