### ISSUE TITLE
LOL Freezing

### ISSUE THREAD

**Issue by beadwarf** [berbb/PortAIO#563]
The game freeze after a time playing i tried to delete appdata but noting so far.

**Comment by berbb** [comment]
lol, we can't do anything if you don't give us what you're using. champion, utilities, are you using l# orb? give me a bit more then it's just freezing.

**Comment by beadwarf** [comment]
Any champ not using l# orb and i'l list the utilities

**Comment by beadwarf** [comment]
http://prntscr.com/brc07c cant reconnect to tell u game close open and just the background music goes

**Comment by Lemonadez** [comment]
Uncheck all your loader addon. only check PORTAIO.

**Comment by berbb** [comment]
Wow, that's really weird, are you playing borderless or full screen?

**Comment by beadwarf** [comment]
borderless everytime

**Comment by beadwarf** [comment]
i was playing normal right now and after leveling up the ult the game freezed

**Comment by berbb** [comment]
Try a different activator and tell me how it goes.

**Comment by beadwarf** [comment]
Already turned off the activator but noting

**Comment by berbb** [comment]
Have you tried turning off all utilities?

**Comment by beadwarf** [comment]
The tracker is off too i was using l# activator because the other with auto ult level was freezing but keep freezng sometimes

**Comment by berbb** [comment]
The only way to see what is making you crash is to disable every utility and use one at a time to determine what utility is making you crash. Are you using skin changer by any chance?

**Comment by dankmemer420** [comment]
I recommend not using any utilities tbh, I have never crashed once i turned them all off, i only use skinchanger.

**Comment by beadwarf** [comment]
i dont use skinchanger cuz it crash when i try to change

**Comment by berbb** [comment]
I'm honestly not sure why this is happening. You're on borderless, you're not using skin changer, it's happening on every champion, you turned off activator, turned off tracker, and it's still happening. 

This concludes that it's most likely an EloBuddy error unless it's only happening with PortAIO and I'm not sure why this is happening.

Try going to the bottom of this thread and see if re-downloading any of the prerequisites will help you : https://www.elobuddy.net/topic/3110-faq-troubleshooting-read-before-posting-a-thread-0512/
