### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by voidsurfer** [berbb/PortAIO#57]
Could you make it so that we can enable/disable certain champion assemblies? For example i have my own riven and my own darius that i'd like to use but having PortAIO conficts with them.

Eitherway, keep up the good work! :)

**Comment by KiriharaSenpai** [comment]
when you in a game press shift and click portaio misc then you can see there a checkbox says utility only mode bla bla

**Comment by voidsurfer** [comment]
Yeah i am aware of this, but isn't this a permanent setting change that will carry over between matches?

For example if i check Utility Only for Riven and then the next match i play Anivia, will it be Utility Only for anivia aswell?

**Comment by KiriharaSenpai** [comment]
nope if u want use anivia with portaio then you should unclick this option

**Comment by voidsurfer** [comment]
Anyway, it was like i thought. The settings are not champion specific. Hence turning on Champion only for one champion will do it for all.

This is what i asked about, if there could be a feature/function that would create champion specific settings :) i know SebbyAIO has it on L#.

Eitherway, keep up the good work berbinator
