### ISSUE TITLE
Game freezes a lot

### ISSUE THREAD

**Issue by fatihcoskun27** [berbb/PortAIO#58]
My friend says game freezes a lot and it make me disconnect from the game for like 10 times in a game.
He played Jinx & Kalista. Freezed on both.

**Comment by fatihcoskun27** [comment]
I dont use EloBuddy, my friend has not a github account. So I wrote that.

**Comment by iNubbish** [comment]
I have the same problem, I just woke up so I'll be trying to force a crash this morning so I can help berbb fix it.

**Comment by iNubbish** [comment]
I'll also try to force it with Jinx and hope it freezes for the same error as Kalista

**Comment by berbb** [comment]
He should post here because there may be console errors, I haven't experienced any crashes with them. There's freezing going on for a few people, I'm not sure how to fix it because I don't crash.
