### ISSUE TITLE
I can't stop L# OrbWalker

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#580]
I can't stop L# OrbWalker after last update 4 hours ago. I mean checkbox for L# OrbWalker is removed.

**Comment by berbb** [comment]
PortAIO now uses L#'s Orbwalker.

**Comment by NentoR** [comment]
No way to stop it ? I wanna stop it because have small bugs.

**Comment by berbb** [comment]
https://github.com/berbb/PortAIO/issues/577
