### ISSUE TITLE
Safest settings to play human-like for L# OrbWalker

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#582]
What is human-like movement delay and extra windup ? And also other settings that can be humanized.

**Comment by berbb** [comment]
Setting movement delay to something like 100-150 is decent and still performs decently well. Anything above that makes it slow but humanized.

**Comment by NentoR** [comment]
Other options ? This Extra Windup delay ? Can i use SebbyBanWars + L# Orb ?

**Comment by berbb** [comment]
Windup delay isn't technically a humanizer, and yes using you can use those.

**Comment by NentoR** [comment]
Then if this is 0 its not problem ? If i make this to 35 like EB OrbWalker or 50 ?
