### ISSUE TITLE
Evades and OrbWalker

### ISSUE THREAD

**Issue by yorik100** [berbb/PortAIO#584]
Evade# make crash the most of the time went the game start + crashes at somes points (Like Taric's E) and dosn't dodge Azir's soldiers (And ult I think) + It makes lag when evading Ashe's W

ezEvade dosn't dodge Karthus's Q when he is in ghost mode

OrbWalker dosn't attack Illaoi's tentacles + Illaoi's ghost (All ghosts)

PS : DZAwareness HUD is glitched af and Garen script isn't AA resetting with Q

**Comment by yorik100** [comment]
And Garen isn't AA resetting with Q

**Comment by berbb** [comment]
Keep orbwalker issues in the other issue

**Comment by berbb** [comment]
Evades will be dealth with later and I'll fix the Illaoi issue.

**Comment by yorik100** [comment]
Illaoi's passive and ult aren't dodged too

**Comment by berbb** [comment]
The original scripts don't even have them dodged.

**Comment by yorik100** [comment]
Yes but you fixed Yasuo's tornado, why don't fix Illaoi's tentacles
