### ISSUE TITLE
AA resets

### ISSUE THREAD

**Issue by yorik100** [berbb/PortAIO#587]
Some problems with AA reset of Garen's Q and Vi's E (Even with the old OrbWalker)
Maybe there is more problems like this, I'll probably update this report when I'll find another problem related to AA reset

**Comment by NentoR** [comment]
Remove EloBuddy %appdata% folder and try again.

**Comment by yorik100** [comment]
--' It works with 90% of the addons, not these, like the EB one is AA resetting with Garen

**Comment by berbb** [comment]
Made some changes to the Orbwalker go and test it out. After the Orbwalker changes it should AA reset nicely, both Vi and Garen.

I noticed for Garen that if you want to AA reset turn off the Q option in the combo menu so that the script doesn't start with Q and you miss that AA reset.
