### ISSUE TITLE
[EXORAIO RYZE] Skills won't shoot

### ISSUE THREAD

**Issue by FoxyKunDesu** [berbb/PortAIO#589]
Simply put, using combo, lane clear, or anything won't make the script use skills. Had to switch to ElEasy Ryze to save the game. Hopefully this is fixed as ExorAIO seems to be the most updated on L#.

**Comment by Sharpino** [comment]
try to use L# orb

**Comment by NentoR** [comment]
remove %appdata% folder EloBuddy and try again.

**Comment by berbb** [comment]
It should work fine now, although I will be updating this later for the Ryze update.
