### ISSUE TITLE
Caitlyn

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#59]
Orbwalker randomly stops working, i think it's because of traps.

**Comment by berbb** [comment]
That might be an EB error, nothing in the Caitlyn addon disables the movement or attacking within the Orbwalker. I'll check it out :)

**Comment by berbb** [comment]
I wasn't able to reproduce the Orbwalker error, this was hopefully a one time thing, if it happens again comment here.

**Comment by rman200** [comment]
Actually Ive experienced that with OKTW champions..maybe its something with OKTFocus?
Not much of a problem tho, you just have to right click anywhere and its back to normal
