### ISSUE TITLE
Nami

### ISSUE THREAD

**Issue by LindsNemesis** [berbb/PortAIO#591]
Nami Ported Addon dont using E in allies for me #Activator dont using Mikael in Allies And can Improve Smite in all Utility?

(W Is working i test again , But E nothing) 

Another Issue Jax using E in random Moments with xQx Jax
ElZilean dont Ulting

**Comment by berbb** [comment]
Fixed Nami. As for Jax I changed the casting method so that it should cast Q better now. It casts E randomly because it tries to Q>E but the Q never hits. As for ElZilean, it'll be fixed when handling this issuse : https://github.com/berbb/PortAIO/issues/590
