### ISSUE TITLE
OKTW Xerath no using spells

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#592]
Yeah i tested yesterday this OKTW Xerath no using spells. After this i tested ElXerath working fine but this OKTW Xerath need fix

**Comment by Sharpino** [comment]
using l# orb?

**Comment by KiriharaSenpai** [comment]
change predictioner and hitchance

**Comment by berbb** [comment]
Should be fixed. OKTW's Library has been ported to the Orbwalk Manager that supports both orbwalkers.
