### ISSUE TITLE
#l orbwalker 

### ISSUE THREAD

**Issue by haxorwannabe** [berbb/PortAIO#596]
dont atack tibers , elise spiders at least cant test other stuff life malz minions

**Comment by berbb** [comment]
https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577https://github.com/berbb/PortAIO/issues/577

**Comment by IlikeBaconLol** [comment]
ZBEB ZBEB
