### ISSUE TITLE
Big FPS drops after new update + crashing

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#597]
Big fps drops after new update and crasing when i press Ctrl + Alt + Delete I am on Borderless mode

**Comment by berbb** [comment]
http://image.prntscr.com/image/b53e564405444b06a4ccb89999637f09.png

Console logs...

**Comment by NentoR** [comment]
[07/13/2016 21:39:26] <Info>
 Initializing Elobuddy.Loader [0.1.9.14]
[07/13/2016 21:39:26] <Info>
 Deserializing settings.
[07/13/2016 21:39:26] <Info>
 Elobuddy.Loader initialized successfully.
[07/13/2016 21:39:26] <Info>
 Running elobuddy system updater.
[07/13/2016 21:39:30] <Info>
 League hash detected: "2be80894fe6ccd622867857fd26119a3"
[07/13/2016 21:39:30] <Info>
 EloBuddy updated for current patch: True
[07/13/2016 21:39:30] <Info>
 Copied EloBuddy.Core.dll to: "C:\Users\****\AppData\Local\Temp\lBId0u5T0hSWttp\Elobuddy.Core.dll"
[07/13/2016 21:39:30] <Info>
 Copied EloBuddy.Sandbox.dll to: "C:\Users\****\AppData\Local\Temp\lBId0u5T0hSWttp\ImLt6LNfWQZbTZy.dll"
[07/13/2016 21:39:30] <Info>
 Copied EloBuddy.dll to: "C:\Users\****\AppData\Local\Temp\lBId0u5T0hSWttp\bhd6zB4o4bNnn7D.dll"
[07/13/2016 21:39:30] <Info>
 Elobuddy system updater has finished updating.
[07/13/2016 21:39:32] <Info>
 Updating Elobuddy addons.
[07/13/2016 21:39:32] <Info>
 Updating addon: "Berb.Common" with url: "https://github.com/berbb/Berb.Common" and project name: "Berb.Common.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "Ignite Helper" with url: "https://github.com/Toyota7/EloBuddy/" and project name: "Ignite Helper.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "LittleHumanizer" with url: "https://github.com/elosupport/Korean" and project name: "LittleHumanizer.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "TheNewYasuo" with url: "https://github.com/DuckSong/TheNewYasuo" and project name: "TheNewYasuo.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "PortAIO" with url: "https://github.com/berbb/PortAIO" and project name: "PortAIO.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "EvadeIC" with url: "https://github.com/EloBuddy/OfficialAddons" and project name: "EvadeIC.ebaddon"
[07/13/2016 21:39:32] <Info>
 Updating addon: "Mario`s Lib" with url: "https://github.com/mariogk/ItsMeMario" and project name: "Mario`s Lib.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "LazyLucian" with url: "https://github.com/DamnedN00b/EloBuddy" and project name: "LazyLucian.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "GuTenTak_Lucian" with url: "https://github.com/joyhck/Elobuddy-Lucian" and project name: "GuTenTak_Lucian.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "KappaAIO" with url: "https://github.com/plsfixrito/KappaAIO" and project name: "KappaAIO.csproj"
[07/13/2016 21:39:32] <Info>
 Updating addon: "MasterMind" with url: "https://github.com/EloBuddy/OfficialAddons/" and project name: "MasterMind.ebaddon"
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "TheNewYasuo", result: Ready (url: "https://github.com/DuckSong/TheNewYasuo", project: "TheNewYasuo.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\A9D1E7B9")
[07/13/2016 21:39:33] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\A9D1E7B9\TheNewYasuo.csproj".
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "Ignite Helper", result: Ready (url: "https://github.com/Toyota7/EloBuddy/", project: "Ignite Helper.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\658C7C5D")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "Mario`s Lib", result: Ready (url: "https://github.com/mariogk/ItsMeMario", project: "Mario`s Lib.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\8005B62C")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "EvadeIC", result: Ready (url: "https://github.com/EloBuddy/OfficialAddons", project: "EvadeIC.ebaddon", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\542E9C03")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "MasterMind", result: Ready (url: "https://github.com/EloBuddy/OfficialAddons/", project: "MasterMind.ebaddon", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\E165A222")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "KappaAIO", result: Ready (url: "https://github.com/plsfixrito/KappaAIO", project: "KappaAIO.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\D04126E5")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "LittleHumanizer", result: Ready (url: "https://github.com/elosupport/Korean", project: "LittleHumanizer.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\9A14A1C5")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "LazyLucian", result: Ready (url: "https://github.com/DamnedN00b/EloBuddy", project: "LazyLucian.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\7695B688")
[07/13/2016 21:39:33] <Info>
 Finished updating addon: "GuTenTak_Lucian", result: Ready (url: "https://github.com/joyhck/Elobuddy-Lucian", project: "GuTenTak_Lucian.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\B019D6EE")
[07/13/2016 21:39:34] <Info>
 Finished updating addon: "Berb.Common", result: Ready (url: "https://github.com/berbb/Berb.Common", project: "Berb.Common.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\2D739859")
[07/13/2016 21:39:34] <Info>
 Finished updating addon: "PortAIO", result: Ready (url: "https://github.com/berbb/PortAIO", project: "PortAIO.csproj", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\5F4CB821")
[07/13/2016 21:39:35] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\A9D1E7B9\TheNewYasuo.csproj".
[07/13/2016 21:39:35] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\658C7C5D\IgniteHelper\Ignite Helper.csproj".
[07/13/2016 21:39:37] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\658C7C5D\IgniteHelper\Ignite Helper.csproj".
[07/13/2016 21:39:37] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\8005B62C\Mario`s Lib\Mario`s Lib\Mario`s Lib.csproj".
[07/13/2016 21:39:38] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\8005B62C\Mario`s Lib\Mario`s Lib\Mario`s Lib.csproj".
[07/13/2016 21:39:38] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\8005B62C\Mario`s Activator\Mario`s Activator\Mario`s Activator.csproj".
[07/13/2016 21:39:40] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\8005B62C\Mario`s Activator\Mario`s Activator\Mario`s Activator.csproj".
[07/13/2016 21:39:40] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\542E9C03\iCreative\EvadeIC.ebaddon".
[07/13/2016 21:39:40] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\E165A222\Hellsing\MasterMind.ebaddon".
[07/13/2016 21:39:40] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\D04126E5\KappaAIO\KappaAIO\KappaAIO.csproj".
[07/13/2016 21:39:42] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\D04126E5\KappaAIO\KappaAIO\KappaAIO.csproj".
[07/13/2016 21:39:42] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\9A14A1C5\LittleHumanizer\LittleHumanizer.csproj".
[07/13/2016 21:39:44] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\9A14A1C5\LittleHumanizer\LittleHumanizer.csproj".
[07/13/2016 21:39:44] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\7695B688\LazyLucian\LazyLucian\LazyLucian.csproj".
[07/13/2016 21:39:46] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\7695B688\LazyLucian\LazyLucian\LazyLucian.csproj".
[07/13/2016 21:39:46] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\B019D6EE\GuTenTak_Lucian.csproj".
[07/13/2016 21:39:47] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\B019D6EE\GuTenTak_Lucian.csproj".
[07/13/2016 21:39:47] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\2D739859\Berb.Common\Berb.Common.csproj".
[07/13/2016 21:39:53] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\2D739859\Berb.Common\Berb.Common.csproj".
[07/13/2016 21:39:53] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\5F4CB821\PortAIO.csproj".
[07/13/2016 21:40:07] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\5F4CB821\PortAIO.csproj".
[07/13/2016 21:40:07] <Info>
 Finished updating Elobuddy addons.
[07/13/2016 21:40:26] <Info>
 Serializing settings.
[07/13/2016 21:41:26] <Info>
 Serializing settings.
[07/13/2016 21:42:53] <Info>
 Updating addon: "not_set" with url: "https://github.com/TearXD/EloBuddy" and project name: "not_set"
[07/13/2016 21:42:53] <Info>
 Cloning repository: "https://github.com/TearXD/EloBuddy" to directory: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\4BC0C25B".
[07/13/2016 21:42:56] <Info>
 Successfully cloned repository: "https://github.com/TearXD/EloBuddy" to directory: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\4BC0C25B".
[07/13/2016 21:42:56] <Info>
 Finished updating addon: "not_set", result: Ready (url: "https://github.com/TearXD/EloBuddy", project: "not_set", directory "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\4BC0C25B")
[07/13/2016 21:42:59] <Info>
 Installing addon: "https://github.com/TearXD/EloBuddy+Prototype Viktor.csproj".
[07/13/2016 21:42:59] <Info>
 Compiling project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\4BC0C25B\Prototype Viktor.csproj".
[07/13/2016 21:43:01] <Info>
 Successfully compiled project: "C:\Users\****\AppData\Roaming\EloBuddy\Repositories\4BC0C25B\Prototype Viktor\Prototype Viktor\Prototype Viktor.csproj".
[07/13/2016 21:43:01] <Info>
 Successfully installed addon: "https://github.com/TearXD/EloBuddy+Prototype Viktor.csproj"
[07/13/2016 21:43:01] <Info>
 Serializing settings.
[07/13/2016 21:43:26] <Info>
 Serializing settings.
[07/13/2016 22:40:26] <Info>
 Serializing settings.
[07/13/2016 22:42:26] <Info>
 Serializing settings.
[07/13/2016 22:43:26] <Info>
 Serializing settings.
[07/13/2016 22:44:26] <Info>
 Serializing settings.
[07/13/2016 22:45:26] <Info>
 Serializing settings.

**Comment by NentoR** [comment]
EloBuddy crashing my game when i do Ctrl + Alt + Delete its happen only with PortAIO. I am on borderless mode.

**Comment by berbb** [comment]
That doesn't make sense at all, why would CtrlAltDelete crash your game? What utilites do you have on?

**Comment by NentoR** [comment]
I tried without utilities only Berb.Common and PortAIO but it still crashing. It not happen if use EB addon.

**Comment by berbb** [comment]
Which Champion?

**Comment by NentoR** [comment]
Viktor

**Comment by berbb** [comment]
Only Viktor?

**Comment by NentoR** [comment]
Same with annie. Game freeze and crash. Console show errors but after game close console closing too and no save the logs i will send you image if you want.

**Comment by berbb** [comment]
Are you using the L# orbwalker or no?

**Comment by NentoR** [comment]
No

**Comment by NentoR** [comment]
This is what console shows http://i.imgur.com/7dcRdHp.jpg

**Comment by berbb** [comment]
That's an EloBuddy error, not related to PortAIO. That stacktrace/error does not lead anywhere to PortAIO's code. I would've thought it was a Utility error but you already said you tried it with no utilities but it was still crashing.

Try redownloading all the necessary tools to use EloBuddy again : https://www.elobuddy.net/topic/3110-faq-troubleshooting-read-before-posting-a-thread-0512/

**Comment by NentoR** [comment]
Not same error if i use Alt + Tab then i will use Alt + Tab. Problem is maybe Windows 8.1
