### ISSUE TITLE
OKTW perfomance ( probably a bug in code)

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#6]
So what i want to report is that OKTW is not perfoming correctly atleast for me . going to list some of the problems i faced . First played caitlyn and it wouldn't cast Q no matter what (even without ticking the reduced Q usage feature) Then i played anivia and it casted her skills but the Q prediction was way too off (randomly casting Q backwards when had enemies in front, also activating the second Q when there was no champion to stun, it would also try to stun azir soldiers for example) another problem with anivia is that when i casted R to clear a wave as soon as the first minion died it would stop the R( with AutoR activated): It might be a problem with the original assemblie tough.
PS:Couldn't had a label to it

**Comment by spvrtan** [comment]
I have the same issue, it seems a lot of champions dont work properly/at all with OKTW, i'll post back with the champions i experience it with after work

**Comment by berbb** [comment]
It's because the prediction method is different so it's not the same. But I will check out the issues you've reported.

**Comment by lgndz** [comment]
As per issue #5 -

I have done testing with 4 different champs between OKTW and Diabaths port and Challenger Series and Necherito, the only crashing I have, (all other things equal) happens with the OKTW assem selected.

**Comment by DjVrip** [comment]
Same,
I Test OKTW with Kalista/lucian/brand when I change the prediction other than the common prediction combo mode bug (spell which launches anywhere, etc..)

**Comment by lgndz** [comment]
I'm not sure how pred works when you select other ones. I always use common. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 19, 2016 at 3:48 PM -0700, "DjVrip" <notifications@github.com> wrote:












Same,

I Test OKTW with Kalista/lucian/brand when I change the prediction other than the common prediction combo mode bug (spell which launches anywhere, etc..)
