### ISSUE TITLE
Valvrave Sharp Yasuo - primec 

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#6]
LastHit with Q1 and Q2 works perfect after fix. But now I can't turn off LastHit with Q3, even with unchecked checkbox it uses Q3 always.
By the way I want to use Q1 and Q2 always while LaneClear, but it doesn't use it, only sometimes. I want to use Q1/Q2 instantly when I press LaneClear key, is it possible to do?

**Comment by primec** [comment]
1) I can't turn off LastHit with Q3.
2) Q1/Q2 works only sometimes while LaneClear, but I want to use it instantly after I press LaneClear button.
3) Harass with Q doesn't work in Hybrid mode, only AA works.

**Comment by berbb** [comment]
https://github.com/berbb/PortAIO/issues/16
