### ISSUE TITLE
Champion DualPort Option

### ISSUE THREAD

**Issue by yorik100** [berbb/PortAIO#602]
Add an option for choose no script for this champ, because everytime I want to use EB addon, I need to set only utilities and change after I stop using EB addon, so everytime I need to choose this champ (Darius), I need to switch mode, it's annoying if I'm playing Darius and after Illaoi and I switch everytime, Darius and after Illaoi, and I need to change the option and press F5 everytime...

(Sry for my English)

**Comment by dankmemer420** [comment]
There's an option to only use utilities and it will turn off champ scripts if that's what you're trying to ask for.

**Comment by yorik100** [comment]
That's exacly what I said, I need to switch everytime I play another champ than Darius...

**Comment by LindsNemesis** [comment]
Have a Option for that just start the game with PortAIO and another Addon and put Only use Utlity 
this just is two seconds to do ,

**Comment by yorik100** [comment]
That's exacly what I said, I need to switch everytime I play another champ than Darius...

**Comment by Muse30** [comment]
You will still have to press f5 tho

**Comment by yorik100** [comment]
I want a thing for choose in DualPort an option for choose like ManualAddon or something like that, and it will just dosn't load any champion addon for the actual champ that we play, not like utilities only, utilities only isn't stick to the champ that we are playing

**Comment by 98181735** [comment]
Lmao dude wtf are u talking about. In menu u have an option to load only utilities/ or champions pls stop saying bullshit

**Comment by berbb** [comment]
Is it that hard to shift > click misc menu > change option > F5?

2 keyboard click and 2 mouse clicks.
