### ISSUE TITLE
Annie a lot of problems

### ISSUE THREAD

**Issue by NentoR** [berbb/PortAIO#603]
First of all i tried OKTW Annie and this other in dual-port both have problems. With annie i never had this FPS drops from 200-250 FPS to 40 FPS. My normal FPS drops are 100-120 FPS with PortAIO. Annie dont move in combo mode just stay and AA and casting spells when have. I have ping problems in fights with annie i gets moon walk or something like that and i cant see what happen. Played Viktor not problems only with Annie.

**Comment by berbb** [comment]
- Annie is moving perfectly fine in both orbwalkers, tested myself.
- Annie is working fine in both dual-ports, tested myself.
- Ping problems have nothing to do with PortAIO?

Check your keys in the Orbwalker to see if they are the ones you set.

**Comment by inphratiic** [comment]
Meanwhile i'm happy to have 30 fps lane and 20 in TF's ^^
