### ISSUE TITLE
Please fix D-Nidalee Ally heal 

### ISSUE THREAD

**Issue by goddamnguy** [berbb/PortAIO#61]
everything works fine exept this one thing, whatever I change in settings its still not healing allies.

**Comment by goddamnguy** [comment]
spend ~1,5h to figure out how to fix this since I know shit about c# but I did some magic and it works. 

`		private static void AllyAutoE()
        {
			foreach (var hero in ObjectManager.Get<AIHeroClient>().Where(hero => hero.IsAlly))
            if (Player.Spellbook.CanUseSpell(SpellSlot.E) == SpellState.Ready && hero.IsAlly)
            {
                if (Orbwalker.ActiveModesFlags.HasFlag(Orbwalker.ActiveModes.Flee)) return;
                var forms = getCheckBoxItem(Heal, "AutoSwitchform");
                var health = hero.Health
                             <= hero.MaxHealth * getSliderItem(Heal, "AllyHPercent") / 100;
                var mana = Player.Mana >= Player.MaxMana * getSliderItem(Heal, "MPPercent") / 100;
                if (hero.HasBuff("Recall") || hero.InFountain()) return;
                if (E.IsReady() && health)
                {
                    if (IsHuman && mana)
                    {
                        Player.Spellbook.CastSpell(SpellSlot.E, hero);
                    }

                    if (IsCougar && R.IsReady() && mana && forms)
                    {
                        R.Cast();
                        Player.Spellbook.CastSpell(SpellSlot.E, hero);
                    }
                }
            }
		}`

Maybe its trashy but works :)

**Comment by berbb** [comment]
Done. thanks.
