### ISSUE TITLE
Port request 

### ISSUE THREAD

**Issue by TheDudey** [berbb/PortAIO#61]
HEy Berbb,
First ty for coming back to port aio.

We have already some vayne ports would be nice if we have...
https://github.com/HikigayaAss/LeagueSharp/tree/master/HikiCarry%20Vayne%20Masterrace

u cant have engouh vayne addons :)

**Comment by Lemonadez** [comment]
u serious? That Hiki never been updated for 2 months..Its no better than VHR.

**Comment by Muse30** [comment]
well added to the ToDo list but its not a priority right now
