### ISSUE TITLE
Skinchanger causing crashes

### ISSUE THREAD

**Issue by GreatWhite181** [berbb/PortAIO#62]
For me, my skin changer causes a lot of issues. I get a lot of crashes when changing skins for example.

**Comment by qq13330331** [comment]
Close the skin

**Comment by GreatWhite181** [comment]
@qq13330331 well ofcourse that fixes it, but that defeats the purpose of wanting to change skins.

**Comment by qq13330331** [comment]
Waiting for repair .

**Comment by KiriharaSenpai** [comment]
doesnt crash for me works awesome

**Comment by berbb** [comment]
Are you playing on fullscreen? A lot of graphical problems that causes crashes happen in fullscreen.

**Comment by qq13330331** [comment]
Close skin, working 'normal

**Comment by qq13330331** [comment]
The skin, resulting in a crash

**Comment by qq13330331** [comment]
Use of skin, death resurrection crash

**Comment by berbb** [comment]
@qq13330331 Thank you, testing it out right now.

**Comment by berbb** [comment]
Just tested it with Irelia, put on a skin in Skin# and died 3 times, and on respawn nothing happened. I also spammed the Skin changer to different skins and nothing happened.

**Comment by fluut** [comment]
@berbb i just actively used it in a normal game with cassio on skin 1, the skin was loaded in with the auto load-in function and didn't change it. didn't always crash on respawn, out of like 5 deaths 1 was a crash.
