### ISSUE TITLE
Utilities not loading

### ISSUE THREAD

**Issue by ihavethemoon** [berbb/PortAIO#62]
I updated the Port AIO and the common and I went into the game and the Utilities aren't loading it's only showing the credit part of the the sub menu. When I press F5 it still doesn't show more then just credits I have all more then 3 things selected like Gank Alerter and Activator and it's not showing it. The addons load though which is good but sometimes the addons messes up which I guess is due to the common not loading well idk. I deleted it both(Port AIO and the Common)  and redownloaded it and it still only shows the credits only. I'm doing something wrong idk. I have only port aio and the common and mastermind selected when I go into a game. It worked well with mastermind before so I don't think it's that. Maybe EB is messing with it some how I'm a "buddy" member for EB  btw I hope that's not effecting it.

**Comment by goddamnguy** [comment]
utilities are turned off till fix.

**Comment by ihavethemoon** [comment]
ohhhh thank you xD I thought I was stupid or something. Is it right for me to update Port AIO, like does it update the addons in there or does it update by itself? I thought I fked it up by updating it, which I kinda did :/ but if something was wrong i'm grateful he is fixing it.

**Comment by goddamnguy** [comment]
There were crash reports caused by utils so they're off till berb fix them. Anyway u can still turn them on for yourself If u didnt have any problems before

**Comment by ihavethemoon** [comment]
It's fine I'll wait. Thank you :)
