### ISSUE TITLE
D Rengar E Prediction Issue

### ISSUE THREAD

**Issue by KiriharaSenpai** [berbb/PortAIO#62]
hi have a good work i wanna report this issue about d rengar sometimes it casts e way too of position of enemy and sometimes it doesnt even cast it when enemy in e range im using d rengar cuz elrengar is underperforming for me it fails combo

**Comment by Muse30** [comment]
update & try again.. also try changing the hitchance

**Comment by Muse30** [comment]
try again when you can

**Comment by KiriharaSenpai** [comment]
oh thx works now but btw i changed hitchance to medium can you check out elrengar too?

**Comment by Muse30** [comment]
yes.. I think our version is outdated so I will port it again probably
