### ISSUE TITLE
Azir Insec not work

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#63]
I try to set it up, but it still doesn't work

**Comment by toughra12345** [comment]
yeah not work

**Comment by Muse30** [comment]
Testing

**Comment by Muse30** [comment]
well tested in custom and is working fine for me

**Comment by berbb** [comment]
It should working fine, just make sure you select a target by clicking your target (you'll know when you selected a target when there's a red circle around them). If there's no red circle then go into the target selector and turn on manual selector.
