### ISSUE TITLE
PrideStalker Rengar Crash Problem

### ISSUE THREAD

**Issue by rexyrexy** [berbb/PortAIO#65]
When have 5 ferocity and before casting q game is crashing in tripleq mode
And when have 5 ferocity again before casting e game crashes again in gang mode
Oneshot mode works good
I didnt try ap mode

Both same Console debug : http://i.hizliresim.com/0D3A6Y.png

And there is another problem of PrideStalker rengar not casting q when jungleclear

**Comment by berbb** [comment]
Thanks, gonna check this out.

Just to break this down for myself :
- 5 ferocity > before attack event Q = crash
- PrideStalker Rengar not using Q in JG
- Check out the error in the picture

**Comment by berbb** [comment]
Should be okay now.
