### ISSUE TITLE
Lissandra Feedback

### ISSUE THREAD

**Issue by rexyrexy** [berbb/PortAIO#65]
Lissandra doesnt casts spell any Orbwalker mode. Combo,laneclear,jungleclear, harass etc..

**Comment by berbb** [comment]
She does, another user had this problem but it's working completely fine. I'm not sure how to fix it, is there any console errors? Try deleting your appdata?

**Comment by rexyrexy** [comment]
Ok i will try and feedback soon..

**Comment by rexyrexy** [comment]
Okay i deleted appdata EloBuddy folder and now everything works well. Good job :+1:

**Comment by Muse30** [comment]
yeah I was the one with the problem .. all good now
