### ISSUE TITLE
Yasuo Problems

### ISSUE THREAD

**Issue by Hidan123** [berbb/PortAIO#66]
Hello berb yasuo have some problems : 
1.Not last hiting with "e"
2.When flee mode not stacking "q"
3. Also i remember that in yasuo valvaresharp there was a option with slider on "e" so u can set range when its going to jump could u try adn add it in future ^^?

**Comment by berbb** [comment]
1. It's broken in ValvraveSharp also. I'm waiting for Brian to fix it so I can port it over.
2. The only time it stacks Q is when your dashing with E. It doesn't stack Q if you're not dashing.
3. It's not there anymore.

**Comment by Hidan123** [comment]
Okay thanks berb ^^
