### ISSUE TITLE
Freeze upon respawn is still a problem for me

### ISSUE THREAD

**Issue by saladinaazir** [berbb/PortAIO#69]
this is fixed by me just using champion only, but this is still an issue =(

**Comment by berbb** [comment]
Not by all, I can't help you if I can't reproduce it. Honestly, the issue is probably coming from your side.

**Comment by Xelamats** [comment]
@saladinaazir 

**Do the following: **

1. Go to: C:\Users\YOUR_USERNAME_HERE\AppData\Roaming\ and delete the Elobuddy folder you have in there. You'll lose all your settings but it's worth it if the problem goes away.
2. Check and make sure you have the following things: https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/
3. I would suggest to download CCleaner, Malwarebytes Anti-Malware, and whatever Antivirus you want and do a quick scan on all of them. Not really sure if it will help but the worst possible thing that can occur is that you find out you have a virus/malware on your pc and you get to clean it; no harm. 
4. Possibly grab Gamebooster (shuts off a lot of things running on your pc; if it works with it running, it could mean something else is causing you to crash?) and see if that helps.

Just throwing out whatever I think could help.
