### ISSUE TITLE
Vayne Condemn logic's

### ISSUE THREAD

**Issue by inphratiic** [berbb/PortAIO#7]
So when using Challenger Series and VHR vayne the condemn seems not to work ( tried every single logic and messing with the hitchances) and i wasn't able to make the condemn work to even a mediocre level . it simply wouldn't cast condem even in that obvious situations ( enemie with wall behind and me right in front of enemie , basicly a stun that every player can manually land). The odd thing is that after 2 or 3 games messing in rankeds with the settings i decided to go a custom to really give time to it and it worked nicely in the custom (not perfect but it was at the level of EB Auto Carry Vayne condemn) but when playing normals or rankeds it doesn't work at all. It works for gapclosers and interrupts but it doesn't cast condemn at all to try stun an enemie.

**Comment by IlikeBaconLol** [comment]
Use a LABEL

**Comment by berbb** [comment]
This is odd, will check it out.

**Comment by berbb** [comment]
Okay, as for VHR, the original assembly always had a bit of problems with the condemn, but Asuna's settings on VHR is :
- Condemn Method : VH Revolution
- Push Distance : 395
- Accuracy : 33%

As for Challenger Series Vayne try this :
- 360 Hikicarry
If that doesn't suit you, try SAC condemn @ 12 Accuracy and 12 Q->E Position Count.

**Comment by hardique** [comment]
@berbb SPred or common?for VHR Revo

**Comment by DjVrip** [comment]
Same,
I Test OKTW with Kalista/lucian/brand when I change the prediction other than the common prediction combo mode bug (spell which launches anywhere, etc..)

**Comment by berbb** [comment]
SDK is actually really bad on EB, I'd try Common before anything. @hardique

**Comment by inphratiic** [comment]
@berbb so i went for some investigation about hte condemn's logic's, have u tried port the Asuna SoloVayne condemn method? the way it works apears to be better then other condemn logic's(using a rectangle instead of just a simple line)

**Comment by berbb** [comment]
@inphratiic Yeah, I guess I could do that or just port SoloVayne (kappa)

**Comment by inphratiic** [comment]
@berbb  i mentioned that because i don't know how the other's condemn's work( i think they draw a line and then check if it will go against a wall or something) but the rectangle idea is a pretty good idea to work with that "skillshot", if it's not working right after u port it i can give it a look and try to fix it( maybe i decide to create my own condemn logic using rectangles if it's too hard to fix asuna one)
