### ISSUE TITLE
[Request] SharpAI 

### ISSUE THREAD

**Issue by ChallengerI** [berbb/PortAIO#72]
Thread link https://www.joduska.me/forum/topic/207634-610-sharpai-summoners-rift-bot/#entry1587948
coded by imsosharp

**Comment by dankmemer420** [comment]
Already said he isn't going to port it because he wants to respect imsosharps wishes on not porting it to other scripting platforms.

**Comment by ChallengerI** [comment]
Oh okay thanks btw
