### ISSUE TITLE
Preset addons

### ISSUE THREAD

**Issue by Rhinoz** [berbb/PortAIO#73]
I am curious as to if the automatically selected addons for a champion are the best and most efficient addons. Such as OKTW is normally selected for all the champions it supports. Has anybody tested other ones than the predetermined addons?

**Comment by berbb** [comment]
They aren't ranked in any specific order by quality. They are ranked by which was ported first.

**Comment by SidaRevamped** [comment]
@berbb order by quality can be a good idea

**Comment by berbb** [comment]
how would we do that when there's over 200 scripts?

**Comment by dankmemer420** [comment]
I could do it but would take me a while.
