### ISSUE TITLE
[Request] Valvrave 6.10 Update.

### ISSUE THREAD

**Issue by dankmemer420** [berbb/PortAIO#73]
Any chance at updating valvrave to its 6.10 update? 

Github: https://github.com/brian0305/LeagueSharp/tree/master/Valvrave%20Sharp/Valvrave%20Sharp

**Comment by Muse30** [comment]
sure

**Comment by Muse30** [comment]
done.

**Comment by dankmemer420** [comment]
Holy i thought this update would fix the crashes but i crashed the first q, feelsbadman

**Comment by dankmemer420** [comment]
From valvrave:

Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.SDK.Spell.get_Level()
   at Valvrave_Sharp.Plugin.LeeSin.Insec.<>c.<Init>b__25_1(EventArgs args)
   at EloBuddy.Drawing.OnDrawingDrawNative()
========================================


========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.SDK.Spell.get_Level()
   at Valvrave_Sharp.Plugin.LeeSin.OnDraw(EventArgs args)
   at EloBuddy.Drawing.OnDrawingDrawNative()
========================================


========================================
Exception occured! EloBuddy might crash!

Type: System.NullReferenceException
Message: Object reference not set to an instance of an object.

Stracktrace:
   at LeagueSharp.SDK.Extensions.IsReady(SpellSlot slot, Int32 t)
   at Valvrave_Sharp.Plugin.LeeSin.KillSteal()
   at Valvrave_Sharp.Plugin.LeeSin.OnUpdate(EventArgs args)
   at EloBuddy.Game.OnGameUpdateNative()
========================================

The other crashes are from the updated ElUtilitySuite

**Comment by Muse30** [comment]
yes I am aware

**Comment by Muse30** [comment]
yasuo didnt crash for me tho in custom

**Comment by dankmemer420** [comment]
Does the console tell whats wrong with the lee though?

**Comment by Muse30** [comment]
I reverted the changes to test myself

**Comment by dankmemer420** [comment]
Lee only crashes in norms

**Comment by Muse30** [comment]
I will do the changes again.. those console errors were there before..

**Comment by dankmemer420** [comment]
Yeah, but is there anyway to fix them and stop it from crashing?

**Comment by Muse30** [comment]
I will play with ElLee in my next game to test.. valvrave & elutilitysuite are updated again (the console errors were there before the update)

**Comment by dankmemer420** [comment]
Yes and before the update valvrave lee was still crashing because of the console errors that are still there.

**Comment by lightduy94** [comment]
Yasuo Valvre still not using E in laneclear! And still wasting Q3 on minions too!

**Comment by Muse30** [comment]
@lightduy94  not possible... I just tested and is working fine

**Comment by Muse30** [comment]
@lightduy94 there is an option to not use Q3 in every menu

**Comment by lightduy94** [comment]
@Muse30 It wasting Q3 in combo mode when chasing enemies through minions bro!

**Comment by Muse30** [comment]
@lightduy94  I'll check

**Comment by berbb** [comment]
This has been such a big problem and I haven't found a fix to it. It can't be smite collision because I disabled it experimentally and it's still crashing, Valvrave Common has nothing to do with it. The only thing left to do is try to re-port in L# SDK.

**Comment by dankmemer420** [comment]
Idk try anything man, ill keep testing and losing games for you bb <33

**Comment by Monnq** [comment]
Idk if there is something wrong but for me none of Valvrave scripts use spells or anything. And if it does it misses skillshots a lot, movement stuttering occurs. I've checked Lee and Yasuo.

**Comment by dankmemer420** [comment]
Hey ever since you updated all the stuff it seems to be good. To make it stop crashing with valvrave, F5 one time as soon as you enter game and it should be fine. Thanks again Berbb
