### ISSUE TITLE
Morgana dsnt work

### ISSUE THREAD

**Issue by Dunkka** [berbb/PortAIO#75]
Kurisu's morgana script loads but pressing combo harass or laneclear does nothing

**Comment by Dunkka** [comment]
I also seem to crash everytime i respawn, these are the addons i'm currently using https://gyazo.com/5d594a226307a9308cd9322790d8ed8f

**Comment by rpgfreak128** [comment]
@Dunkka this is known i dont think it happens to Berb, but it does 2 me do you happen 2 have Windows 10?

**Comment by Dunkka** [comment]
yes

**Comment by berbb** [comment]
@Dunkka Thanks for giving me the list, will check it out.

**Comment by KiriharaSenpai** [comment]
np for me works so awesome im serious dude

**Comment by berbb** [comment]
Clear you appdata.
