### ISSUE TITLE
[Request] AutoSharp

### ISSUE THREAD

**Issue by Acheiro** [berbb/PortAIO#75]
Hello,
I know you have already a lot of stuff to focus on but I wanted to ask for AutoSharp. AutoBuddy works like it works.. Just bad. I guess we are all getting a lot of leave busters and shit. Could you save us before this? Really appreciated <3

**Comment by fluut** [comment]
check the sharpai commits on the todo

**Comment by Muse30** [comment]
autosharp is on the ToDo list
