### ISSUE TITLE
Lux Script Pred

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#77]
While testing the Lux script, I was surprised by how bad its prediction is :/
It missed like 80% of the skills that I would myself hit easily most of the times.
Furthermore, I didn't see any option in the settings that I could configure to make it better.
Can you do something with it, please?
Thanks in advance :)

**Comment by KiriharaSenpai** [comment]
hmm that is interesting idk but doesnt miss skills for me 10 /6 not godlike but still good than lux addons on eb

**Comment by dsljkeee** [comment]
I can throw a screenshot of the settings of your predictions eb

**Comment by Requital** [comment]
use AimBot by ICreative and make prediction for 80-90%

**Comment by berbb** [comment]
This was highly exaggerated, jesus, I thought you meant everything was bad, only the Q was... Anyways updated, and removed Q through minions.
