### ISSUE TITLE
Game crash after respond after 10-20mins

### ISSUE THREAD

**Issue by chienhao10** [berbb/PortAIO#78]
tried with vayne, urgot,yasuo,riven. game will stuck right after i respond from dead. usually happenes after 10~20 mins in game

**Comment by PhaxProjects** [comment]
Well I tried Vayne earlier, And it was fine, Are you using the Skin-changer? Try turning that off, and see if it works.When I tried using the Skin-changer, I also encounter loads of crashing issues but after turning it off everything seemed fine.

**Comment by saladinaazir** [comment]
i got the same problem =\

**Comment by berbb** [comment]
It'd be helpful to know what other addons you're using...

**Comment by rpgfreak128** [comment]
@berbb Hey i am on windows 10 have berb.common and portAIO only running, i have tried many champion urgot vayne fizz soraka shaco leesin and many more it always crashes on rewspawn i turned on and off the move camera on respawn changes nothing i cleared appdata did a fresh Elobuddy install nothing, playing in bordeless and tried windoewed and full screen still crashes.

**Comment by rpgfreak128** [comment]
@berbb give me ideas tell me what 2 test what data 2 send you and i will try it i really want 2 get this 2 stop crashing ill even TeamView if you want

**Comment by berbb** [comment]
Windows version is does not play a factor in this, I'm running W10 and no crashes. Do you have updated net framework? Google it and try to update it for 4.6.

**Comment by saladinaazir** [comment]
I checked the .net framework version using regedit, it is 4.6.1

**Comment by rpgfreak128** [comment]
@berbb yea same mine is up2date =/

**Comment by berbb** [comment]
Download both of these : 
https://www.microsoft.com/en-us/download/details.aspx?id=48159
https://www.microsoft.com/en-us/download/details.aspx?id=40760

**Comment by rpgfreak128** [comment]
@berbb okay i installed them now what? its really weird the crash only happens from 10 minutes on lol like what could that be

**Comment by berbb** [comment]
@rpgfreak128 People have reported ElUtilitySuite is causing it. If you have time, disable ElUtilitySuite and play through a custom and throughout the custom enable it and look for results.

**Comment by rpgfreak128** [comment]
@berbb Regardless of having ElUtilitySuite on or off i dont crash in custom games...... lol even more weird

**Comment by rpgfreak128** [comment]
@berbb thanks for the help can close this for me it was skinhack causing it but i didnt even have it on it was not saving my seetings but i go it fixed
