### ISSUE TITLE
How can i switch to use jesuisFiora instead of Project?

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#79]
The title say its all. Thank you!

**Comment by Monnq** [comment]
Something was wrong with Obj_ParticleEmitter I guess and Berbb decided to port Project Fiora instead of JeSuis.

**Comment by lightduy94** [comment]
OK. Can i switch to use Valvre instead of YasuoPro too?

**Comment by lightduy94** [comment]
Mybad. YasuoPro instead of Valvre

**Comment by lightduy94** [comment]
Report bug: Yasuo Valvre did'nt use E in laneclear mode if i check Only use E to lasthit. Q pred are weird also

**Comment by Muse30** [comment]
whats the problem with project fiora?

**Comment by berbb** [comment]
Yasuo is bugged in laneclear because it's bugged in ValvraveSharp also and I'm not sure how to fix it. YasuoPro is disabled because it's been outdated for a while and evade on it is not working.
