### ISSUE TITLE
HeavenStrike Ryze - Sharpino

### ISSUE THREAD

**Issue by berbb** [berbb/PortAIO#8]
-using q in laneclear when off
-q prediction sometimes stupid
-console error
https://s32.postimg.org/nkz07o691/Screenshot_47.png

**Comment by yashine59fr** [comment]
xD

**Comment by DrHouse12** [comment]
I have tested HeavenStrike Ryze 5 min ago on new mode in lol and :
- ryze not using any spells in lanecleaner
- thats all
Script works op and amazing.

**Comment by berbb** [comment]
@DrHouse12 Just updated LaneClear, try it again.

**Comment by DrHouse12** [comment]
@berbb Great, i will for 5-10 min because my job :dancer:

**Comment by DrHouse12** [comment]
@berbb Laneclear works properly now, but i think so slowly.. And it dont cast Q+E if Q is in cooldown,

**Comment by berbb** [comment]
Alright, I fixed W no casting. And the second error is an EB error looks like the new game mode. You have to press F6 before switching sides and then F5'ing or let EB inject again.

**Comment by Sharpino** [comment]
can confirm the nexus siege tip, you must press f6 before the switch or the game will crash
