### ISSUE TITLE
Leblanc wont use Q/QR for me .

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#80]
i tried clear my appdata but still the same , seems there's problem with her

**Comment by berbb** [comment]
Checking

**Comment by berbb** [comment]
http://pastebin.com/raw/dVKuALWQ - These are the console logs when I do combo. 

"Combo: Cast R(Q)" is only printed when QR is casted, so Q > (Q)R is working.

**Comment by Luc4z** [comment]
thanks and i found out the issue , two chains key is same as my normal combo key so it conflict , thanks
