### ISSUE TITLE
OKTW mf messing with orbwalking (possible easy fix)

### ISSUE THREAD

**Issue by BigPhalus** [berbb/PortAIO#80]
playing mf was running away from enemies, a minion became last hittable and mf starts walking towards it which was also towards the enemies on her own >>> i believe this has something to do with the new last hitting function sebby has implemented in his scripts, not sure if you guys ported it, just suggesting if u have that might be it.

--> EDIT: on further testing and looking at the code i think its because the Q is set as a higher range than it actually is so what ends up happening is the script is spamming Q on a minion whilst the orbwalker is spamming walk backwards causing the fit the champion is having.
EASY FIX

**Comment by berbb** [comment]
Should be okay now.
