### ISSUE TITLE
Bug report: Kalista, Yasuo

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#81]
Kalista: freeze / crash when combo
Yasuo: doesn't use E in laneclear

**Comment by Muse30** [comment]
kalista : hmm I tested even played a game and no crash..

Yasuo : that error is in the original yasuo from bansharp.. you need to wait untill Brian fixes it for berb to fix it

**Comment by Xelamats** [comment]
Just tested Kalista, no problems on my end either.

**Comment by berbb** [comment]
Try clearing you appdata, and for the Yas issue, it's happening on the original assembly on L# also.
