### ISSUE TITLE
Yasuo R

### ISSUE THREAD

**Issue by Requital** [berbb/PortAIO#83]
It doesnt use R in combo

**Comment by berbb** [comment]
1. Is it even on? Press X.
2. Does it meet the requirements? If the enemy is less than X (%) or enemy count is >= X?
3. If you're trying to KS or w/e, do you have the champion enabled in the KS Menu?

**Comment by Requital** [comment]
Yes I turned it on. Probably it didnt match requirements. Sorry for interrupting

**Comment by berbb** [comment]
Turn on the requirments, if it happens again, tell me along with console errors (if any).
