### ISSUE TITLE
Question about OnTick

### ISSUE THREAD

**Issue by Xelamats** [berbb/PortAIO#84]
Question is directed to @berbb 

- Would having it at a lower value equal less packets being sent, or whatever is sent?
- Could this have an effect on ban chance? 

----
Not looking for a definite answer but just your thoughts on it. Wondering if I should test it on one of my accounts and see exactly how it does through the ban waves. Default is 25 and most bump it up to the max (from what I've been told). Wondering if that could be a problem that is causing people to get detected easier.

Don't know anything of what it really is so I could possibly be 100% wrong with my thoughts of thinking it sends packets or something.

**Comment by berbb** [comment]
I have no knowledge about packets and about how many ticks get sent.
