### ISSUE TITLE
Olaf ^^

### ISSUE THREAD

**Issue by Hidan123** [berbb/PortAIO#85]
Yo berb after the updtae it slighty beter but still it just miss a lot. My tip for better q pred woul be that it always cast it on max range is it possible because it often throw axe in front of enenmy and don't hit ^^

**Comment by berbb** [comment]
Honestly, based on Game knowledge throwing the axe at full range reduces your chance of chasing and 1v1'ing. 

If you're chasing someone and you throw the axe and it hits @ full range and then they go a different direction, you'd have to wait 4-5 seconds for Q to be back up or go catch the axe and completely miss the target. 

Same thing with 1v1'ing, if the target is near their tower and you max range toss the axe into the tower then you missed the chance to perma slow and deal additional damage w/ Q.

I'll try updating the prediction, but there's no way I'm making the axe go max range at all times.

**Comment by berbb** [comment]
Updated Pred. This time I updated it on harass & KS also, so it doesn't miss on those mods.
