### ISSUE TITLE
Failed to compile or w.e appdata cleared

### ISSUE THREAD

**Issue by rpgfreak128** [berbb/PortAIO#85]
is it down for anyone else was working last night? srry for the new issue =(

**Comment by Muse30** [comment]
sorry will fix asa´p

**Comment by Muse30** [comment]
fixed

**Comment by ySpark3** [comment]
Hey, i cant instal the berb.commom

**Comment by Muse30** [comment]
https://www.elobuddy.net/topic/21274-installing-ms-build-tools-140/#comment-159210
