### ISSUE TITLE
elutility

### ISSUE THREAD

**Issue by KiriharaSenpai** [berbb/PortAIO#89]
elutility has no smite on new update and got these console errors https://imgur.com/x3aHO8u

**Comment by Muse30** [comment]
what do you mean has no smite ? : http://prntscr.com/b8dly1
the console errors are there since the re-port

**Comment by KiriharaSenpai** [comment]
id have a tab like this can you look screenshot

**Comment by Muse30** [comment]
im confused now.. whats the problem with smite again? I saw the console error is there since the re-port but has nothing to do with smite

**Comment by KiriharaSenpai** [comment]
idk but it was good but now theres no summs use tab even if i had exhaust

**Comment by StefanBulka** [comment]
El utillity making crashs.

**Comment by Muse30** [comment]
@KiriharaSenpai  well the elutilitysuite update was for Heal & some defensive items .. nothing to do with smite or exhaust or anything else but I will check

**Comment by pellep12** [comment]
Yeah the latest re-port of elutil is VERY unstable :/

**Comment by hardique** [comment]
same here.don`t use Heal,has no botrk and qss for me after update

**Comment by pellep12** [comment]
It dont activate Botrk or Ghost Blade aswell..

**Comment by berbb** [comment]
It should be okay now.
