### ISSUE TITLE
Azir

### ISSUE THREAD

**Issue by Jokiblack** [berbb/PortAIO#9]
Champion Name (eg. Ahri) / Utility (eg. Evade) : **Azir**

If this is an issue about a champion, is this Champion dual-port supported (Check via PortAIO Misc)? If yes which one? :

Issue/Problems (Try to be as detailed as possible) : Dont use 2 W in combo

suggestions: add farm

**Comment by inphratiic** [comment]
I think SidaRevamped fixed the azir W on Muse30 fork of portAIO. I think he wouldn't mind giving it to you berb

**Comment by berbb** [comment]
He added a pull request and I just accepted, update and check again.

**Comment by SidaRevamped** [comment]
I have not azir so  my brother tested for me   and i know Insec still does not work ,but W logic supposed to work.

**Comment by Jokiblack** [comment]
@SidaRevamped  i go test :)

**Comment by Jokiblack** [comment]
@SidaRevamped Isec work but slow :S
