### ISSUE TITLE
For some reason Kalista crashes, Alt Tabing leaves my league crashing

### ISSUE THREAD

**Issue by ixEloHellTourist** [berbb/PortAIO#9]

**Comment by Jokiblack** [comment]
What Kalista? Have two Reborn, and Rework. Reborn woorking good

**Comment by ixEloHellTourist** [comment]
Reborn was crashing on me for some reason, My league client will not respond at times

**Comment by Jokiblack** [comment]
Me work fine... you in menu tick Ikalista Reborn?

**Comment by ixEloHellTourist** [comment]
Yes i did lmao

**Comment by ixEloHellTourist** [comment]
Maybe i pressed F5 And it crashed my client, Alt tab also crashes my client :c

**Comment by ixEloHellTourist** [comment]
But overall this PORTAIO IS AMAZING <3 FREE ELO FOR DAYS

**Comment by Jokiblack** [comment]
Reinstall delet all %appdata% and install new all

**Comment by rajuritik** [comment]
not just kalista ... this make my league crashing after alt tab @berbb any solution bro?

**Comment by ixEloHellTourist** [comment]
yeah same here @rajuritik and @berbb

**Comment by dankmemer420** [comment]
Same here

**Comment by berbb** [comment]
Only Kalista? Regardless, I'll check it out.

**Comment by ixEloHellTourist** [comment]
@berbb alt tab and F5-ing crashes league entirely, Thanks for your hard work tho <3 Appreciate it man :)

**Comment by qq13330331** [comment]
@berbb Blood pool resurrection game collapse.

**Comment by KiriharaSenpai** [comment]
change ur screen mode to borderless

**Comment by Shazelol** [comment]
Works very well .. I played kalista in normals :) excellent

**Comment by berbb** [comment]
Alt tabbed on both Kalista scripts and I haven't gotten crashes. F5'd on both and no crashes. I'm not sure how to help you guys, can you guys post logs if any?

**Comment by dankmemer420** [comment]
I'm pretty sure it was because i didn't update after you removed iKalista, works smooth now.
