### ISSUE TITLE
hi berb Please Port it

### ISSUE THREAD

**Issue by lyn690697457** [berbb/PortAIO#91]
I just want to say now Yasuo script works very bad, maybe you can try Port GosuMechanicsYasuo
Although he has not upgraded, but still work.
Here is the address
     https://github.com/GosuMechanics/LeagueSharp.git
And I really like this port aio，Thank you for sharing it。

**Comment by elolam** [comment]
+1

**Comment by Muse30** [comment]
I tried to do it but end up with some errors xD : http://prntscr.com/b007lf

I'm not at berb level sadly

**Comment by berbb** [comment]
Added to to-do list, I'll try to get it done tomorrow.
