### ISSUE TITLE
Bug report: Kurisu Riven crash when activate R1 in combo

### ISSUE THREAD

**Issue by lightduy94** [berbb/PortAIO#92]
Kurisu Riven crash when activate R1 in combo.
I can't disabled Ability tracker in El Ultilitisuit too!

**Comment by lightduy94** [comment]
I activate only champion mode and it not crash, all ulti i used: ElUltility, Gank alert, recall tracker, mastermind.
And i found that Heaven Strike + Kurisu Riven sometimes not Q in combo

**Comment by berbb** [comment]
Will check it out.

**Comment by berbb** [comment]
Shouldn't be happening anymore.
