### ISSUE TITLE
Lucian Does not Use Ext Q

### ISSUE THREAD

**Issue by lgndz** [berbb/PortAIO#93]
In both iLucian and LCS Series - Extended Q no longer accurately targets the champions. 

In combo mode, it seems as if it is not checking pred and simply using it to hit minons (it isnt missing by a little bit, its way off)

iLucian doesnt actually attempt or use Ext Q at all

**Comment by DannyTheGod** [comment]
same problem

**Comment by lightduy94** [comment]
iLucian doesn't use ext Q in Harass mode for me but in combo mode it still working perfectly!

**Comment by lgndz** [comment]
I appreciate the contribution, but this report is specifically because it is not working in Harass. 
It is working correctly in combo for me - this is why I didn't include it. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 26, 2016 at 7:08 AM -0700, "lightduy94" <notifications@github.com> wrote:












iLucian doesn't use ext Q in Harass mode for me but in combo mode it still working perfectly!

**Comment by lgndz** [comment]
Well on second thought. Maybe i wasn't specific enough so thanks! 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 26, 2016 at 7:08 AM -0700, "lightduy94" <notifications@github.com> wrote:












iLucian doesn't use ext Q in Harass mode for me but in combo mode it still working perfectly!

**Comment by Muse30** [comment]
changed the extended q on iLucian a bit... test again (iLucian only)

**Comment by lgndz** [comment]
Working. Will report after 4pm est

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Thu, May 26, 2016 at 10:16 AM -0700, "Muse" <notifications@github.com> wrote:












changed the extended q on iLucian a bit... test again (iLucian only)

**Comment by lgndz** [comment]
Update:

iLucian does NOT use Ext q to harass (or Q at all it seems) in any mode *EXCEPT* Auto harass - BUT, auto-harass only does Q automatically, however it seems to use it to clear lane creeps AND harass... Might just be pred being shitty though.

**Comment by Muse30** [comment]
will check again

**Comment by Muse30** [comment]
@lgndz  just tested and extended q is working on harass and combo pretty good.. are you sure is iLucian? try deleting your appdata

**Comment by Muse30** [comment]
ok actually is not working on harass

**Comment by lgndz** [comment]
Yes I tried deleting appdata. It works by using Q ON the champ, but not thro minions and such. 

Sent from Outlook Mobile, please excuse any errors or shorthand.




On Fri, May 27, 2016 at 10:26 AM -0700, "Muse" <notifications@github.com> wrote:












ok actually is not working on harass

**Comment by Muse30** [comment]
is using extended Q on minions in combo mode will fix harass tho

**Comment by Muse30** [comment]
should be fixed on iLucian
