### ISSUE TITLE
Vayne is amazing

### ISSUE THREAD

**Issue by DannyTheGod** [berbb/PortAIO#93]
i love your port very much xD 
http://i.imgur.com/6dqlQo2.png. 
Thanks you for the port

**Comment by hardique** [comment]
which Q/E settings do u use,dude?

**Comment by Lurker7** [comment]
Yeah, would also like to know which settings are the best for Vayne cuz with the default ones she really often misses her condemn when I play her with combination of PortAIO :/

**Comment by DannyTheGod** [comment]
Q Logic : Sharpshooter and Prada
E Logic : SAC

**Comment by rman200** [comment]
wasnt able to test vayne yet, does she have a humanizer like kog's?

**Comment by hardique** [comment]
tbh,hunter`s reborn 10x times better.
so waiting for port it from berbb

**Comment by berbb** [comment]
Glad you're having fun with it! Also, VHR might a little different in the ported version, so I'm not sure how it's ported out.
