### ISSUE TITLE
Riven tweak request

### ISSUE THREAD

**Issue by Lurker7** [berbb/PortAIO#95]
Regarding your notes about not porting Hoola Riven and the reason for which you have made such decision, it would be great if you had still ported at least the burst combo function which code is contained in that script and then merge it with Nechrito's Riven, so that its current ineffective burst would get this way better by becoming equal to the Hoola Riven one.
The burst is the only thing that is quite bad in case of the current state of the Riven script in your bundle and that's why I am making such a request.
Thanks for all the work you've done so far. I can't describe how grateful I will be seeing that you have agreed to do it <3

**Comment by Hidan123** [comment]
+1 :D

**Comment by Muse30** [comment]
but isnt the same code? Nechrito's Riven is just a copy of hoola riven

**Comment by Lurker7** [comment]
Yeah but Hoola Riven's burst works unlike Nechrito's Riven's one

**Comment by Muse30** [comment]
hmm will check myself .. is pretty easy to add the code from hoola riven

**Comment by berbb** [comment]
Updated, it but I didn't test it. I'll keep this open for feedback until someone tests it.

**Comment by Hidan123** [comment]
Nechrito updated his riven with flawless walljump could u also add it ^^?

**Comment by Hidan123** [comment]
Well also i tesed riven new burst and its not working at all ^^

**Comment by Lurker7** [comment]
Confirmed, sorry to announce it here despite ur hard work u've put into improving it, but it now doesn't work at all.
Basically stops comboing enemy right after using flash + W towards a selected target.
I think the burst combo must have been ported partially incorrectly ...

**Comment by Muse30** [comment]
no .. the code is correct .. I already told him yesterday about it

**Comment by Lurker7** [comment]
Hmm, strange cuz now it's working for me worse than before o.O

**Comment by Muse30** [comment]
? not using W, R1 and E ? it is for me .. only Q not working

**Comment by Hidan123** [comment]
For me its not even flashing XD it just go towards enemy press hydra q aa ^^

**Comment by Lurker7** [comment]
using only flash and W and then stops doing the combo while holding the burst key ...

**Comment by Muse30** [comment]
I guess use burst key for flash + W and then press spacebar for now XD untill berb can fix it

**Comment by Lurker7** [comment]
Yeah, awaiting a fix from Berb :dancers:

**Comment by berbb** [comment]
Unlike EloBuddy's Orbwalker, L#'s Orbwalker can make new custom modes in the Orbwalker to attack and move like a regular orbwalker mode (Combo, Farm, Lashit etc...).

Until, I find another solution you just have to hold Burst then wait for it then go straight to combo key.

**Comment by Lurker7** [comment]
switch the combo to burst upon pressing a specific key (like T) ?
This way u can enable and disable the burst combo whenever u want, so that it will work just while holding the combo key if it's enabled without having to hold the burst key.
That's how the burst function has been made in case of non ported EB addons for Riven

**Comment by berbb** [comment]
That was my solution, but I won't add it until I re-port in Nechrito.

**Comment by Lurker7** [comment]
OK, take ur time, better to make it precisely than hurry up with it and accidentialy fuck something up :)

**Comment by berbb** [comment]
Updated NechritoRiven with the burst that he has, it should work pretty ok, just make sure to have flash up and a target selected or else it'll go straight too the regular combo.

**Comment by 3ackdoor** [comment]
@berbb No draw damage indicator?

**Comment by Lurker7** [comment]
Sadly, burst still isn't working.
Now it's actually even worse since it doesn't even start executing it for me even after turning it on in the settings along with "Force Flash" and "Force R" options

**Comment by berbb** [comment]
Disable those 2 and try again, not sure why you have them on when the burst does it for you.

**Comment by Lurker7** [comment]
I have tried even only with the "Force Burst" enabled and it also didn't work :\/

**Comment by berbb** [comment]
Is select an enemy enabled in the target selector menu and that you have double clicked an enemy?

**Comment by Lurker7** [comment]
Double clicked??? Lel, I guess it's my bad then since every time I am to choose a target that I wanna focus, I click only once on him since that's how it works in L$ or at least worked when I still was a sub there ...
I will try checking if it works applying ur instructions to my gameplay during a custom game.
