### ISSUE TITLE
[Request] Geass Tristana

### ISSUE THREAD

**Issue by SidaRevamped** [berbb/PortAIO#95]
Pretty perfect and big addon , have not the time to port very big addon like that , if someone doing it will be nice.
https://github.com/KallenStadtfeldGeass/KallenSharp/tree/master/S%2B%20Class%20Tristana
https://www.joduska.me/forum/topic/207500-geass-tristanav61017formal-s-class/

**Comment by Muse30** [comment]
is on the To-do list
