### ISSUE TITLE
Master Yi 

### ISSUE THREAD

**Issue by Demisemo** [berbb/PortAIO#96]
Can Port Better script yet

This version does not currentlyJungle

When the beat is slow is not strong

**Comment by Muse30** [comment]
ported Hoola yi

**Comment by Demisemo** [comment]
@Muse30 

thank you pORT Hoola yi


There is a problem:  He would not put the skills attack 
But also use BOTRK

**Comment by Muse30** [comment]
I'll check

**Comment by Demisemo** [comment]
Option missing

**Comment by Demisemo** [comment]
Understand, just look at the text you have compiled
