### ISSUE TITLE
Teemo almost crash, console error here

### ISSUE THREAD

**Issue by DrogonRocks** [berbb/PortAIO#97]
Hi Berbb
getting this error with teemo ( pic of console error here) http://i.imgur.com/LYPuR6K.png
don't know why, i only use PortAIO and Berbb Common, nothing else, also only use Elutility,humanizer and the addon for the selected champion, with that error so far in 10 matches didn't crash once but im afraid it might, i didn't notice a perfomance issue with that but im reporting it anyway 
good job and keep working in this beastly project <3 
also, just a suggestion, don't make new ports of mages because tomorrow almost all of them will have a "rework" and old ports will be useless, so it's better to wait until devs push an update to their assemblies so you can port them and add them here :)

**Comment by Muse30** [comment]
It will probably not crash I also played teemo yesterday    Kappa

**Comment by berbb** [comment]
Fixed the error.
