### ISSUE TITLE
HI, please add these scripts

### ISSUE THREAD

**Issue by ericshug** [berbb/PortAIO#97]
please add these scripts , thank you for these hard work ,good job. ^^b 
KappaUtility
https://github.com/plsfixrito/Worstaddons
AAsteering
https://github.com/Enelx/EloBuddy
Universal MinimapHack
https://github.com/TheSaltyWaffle/LeagueSharp

**Comment by berbb** [comment]
This is not an EB project. I will not add EloBuddy addons in an All-In-One where we only have LeagueSharp scripts... Hence the name PORT-AIO. And I tried adding Universal Minimap before and it just didn't work.
