### ISSUE TITLE
Over cover Target selector

### ISSUE THREAD

**Issue by Luc4z** [berbb/PortAIO#98]
is it possilbe to let us use L# Target selector than EB ?
because L# TS is more specific i think . thanks

**Comment by Luc4z** [comment]
and by the way XP tracker is awesome

**Comment by SidaRevamped** [comment]
+1

**Comment by lightduy94** [comment]
How can i enabled XP Tracker?

**Comment by berbb** [comment]
Porting TargetSelector would mean disabling EB's TargetSelector  (and I can't do that) and also porting their Orbwalker because it wouldn't work with EB's orbwalker.

@lightduy94 It's in NabbTracker, just make sure you're updated and you'll get it.
